### ISSUE TITLE
Parameter X not Adjustable in Logical Switch Using the LiPo Sensor

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#1013]
Radio is a Horus X10S Express with ETHOS 1.0.11.

When using the LiPo sensor as parameter A in a logical switch A<X, it is not possible to adjust the parameter X. The value for X only changes between 0 and 25,2 V when turning the adjustment knob. As a workaround, I changed A to Rx Voltage, then the parameter X could be adjusted. Afterwards, I changed A back to LiPo, and the previously selected value for X was retained.
The problem also occurs if the lowest cell value is selected as sub-option for the LiPo sensor (did not test any other sub-options).

**Comment by Hobby4life** [comment]
I think you have switched X with A.. A = always a source.. X = the value to compare with.

**Comment by Hartinger** [comment]
You are quite right, shame on me. I have corrected the title and description.

**Comment by guycnicholas** [comment]
@Hartinger not that this fixes the underlying bug, but I always prefer to do my low battery alarm on the lowest cell rather than the pack voltage as a whole, and just in case you don't know how to do that on Ethos, once the "source" is set to LiPo the long press menu allows for a number of options including my fav, lowest.

**Comment by Hartinger** [comment]
That's exactly what I also do, and actually I have found the bug when I tried to adjust the alarm threshold (parameter X of the logical switch) for ther lowest cell. I then verified that the problem also exists when the LiPo value (without any sub-option) is used.

**Comment by bsongis-frsky** [comment]
I don't understand this issue, what do you need to compare exactly?

**Comment by Hartinger** [comment]
The issue is that I cannot adjust parameter X in the logical switch, when LiPo (or a sub-option) is selected as parameter A.
When turing the scroll wheel I can only flip between 0V and 25.2V, no other value can be selected.
See the following screenshots (sorry it is in German).
![Screen1](https://user-images.githubusercontent.com/22352021/135859828-37feabb4-85f5-4806-9ca4-0f9678d51cc8.PNG)
![Screen2](https://user-images.githubusercontent.com/22352021/135859853-880c1ac3-837a-47f5-ba60-ceb182127ba2.PNG)

**Comment by guycnicholas** [comment]
@bsongis-frsky his issues isn't that he cannot adjust a parameter, it's that the range is too small. LiPo has a max voltage of 25.2.

**Comment by guycnicholas** [comment]
Sorry, my mistake. Mine adjusts just fine, but with a limited range

**Comment by Hartinger** [comment]
The problem only occurs if LiPo is selected as parameter A.

**Comment by phHed** [comment]
I have encountered the same problem. Is it due to the fact that “Source A LiPo 2.4” as shown on the Tandem 20X manual example is not available in the X10S Express firmware? Only “LiPo” is available. The second options screen with the individual cells is not available.
![3F891464-7948-49A6-8B85-05C816B43DE0](https://user-images.githubusercontent.com/98419506/151037197-691e799f-ddb8-45e0-b1b6-a4378c314a25.jpeg)
![F013822E-CF79-4005-B2F4-7346F212A698](https://user-images.githubusercontent.com/98419506/151037202-4922579d-7e2d-45ff-a4d4-29baa850cec3.jpeg)

**Comment by Hartinger** [comment]
Today I have retested the issue with ETHOS 1.1.1 and found that the problem is fixed. So maybe someone wants to cl,ose this issue.

**Comment by Hartinger** [comment]
Apparently, the problem has reappeared in ETHOS 1.3.0.
