### ISSUE TITLE
voice file language cross

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1076]
V1.0.12 Ethos in Hebrew
still uses audio->en files
and not audio->he files.

all the OS readouts are still in english.

**Comment by Adelaxie** [comment]
@i3dm Hebrew language brings many issues because it's so different from other languages.
We will pause on Hebrew support on audio files.
Only try to fix the EM issues brought from Hebrew menu supporting.
It cost too much energy already, we will work on something more urgent for now stage.
Hope your understanding.

**Comment by i3dm** [comment]
@Adelaxie 
surely using the right files is just a file path in the code?
