### ISSUE TITLE
BlueTooth Trainer Function disconnects and reconnects intermittently in flight

### ISSUE THREAD

**Issue by pld74** [FrSkyRC/ETHOS-Feedback-Community#1077]
Experiencing Trainer disconnects via BlueTooth in flight during the use of the trainer function. Radio speaks: trainer lost, trainer recovered randomly and the plane does take controls from the other radio, which indicates an actual disconnect of the trainer signal. This disconnect is approx. 2-3 seconds long and multiple disconnects per training flight session.

Any guidance would be appreciated.

Details: TD X20 Radios (Qty 2) running Ethos 11 (Final), ISRM 2.1.14 with SD and Flash contents upgraded respectively.

**Comment by bsongis-frsky** [comment]
Bluetooth?
Cable? 
If cabkle, is your cable OK?

**Comment by KAID-YANG** [comment]
Can this problem always be repeated? Please take a video, thank you!

**Comment by KAID-YANG** [comment]
We tried to reproduce the problem of Bluetooth disconnection, but failed. We need to record the status of steering gear and receiver when the two remote controls are disconnected from Bluetooth. Thank you for your feedback

**Comment by KAID-YANG** [comment]
Just recreate your Bluetooth disconnection and record the status of the two X20s on your phone

**Comment by pld74** [comment]
OK thanks

**Comment by subhrabose** [comment]
** Bluetooth trainer feature not usable **
I've two X20S with both Firmware updated to 1.2.11. I tried to use the "trainer" feature via Bluetooth (first time). I have experienced intermittent "Trainer Lost", "Trainer Recovered" as reported originally in this thread. I tried with both Normal Speed and High Speed Bluetooth, same behavior. The issue is easily reproducible if I walk away with one of the radios 10-12 feet from the other while holding the radio close to my body (flying position). Although during actual flight we were not more than 5 feet from each other (the instructor was 4-5 feet behind the student). Later I tested the issue with another club member's X20S (firmware 1.2.11) to eliminate the possibility of a bad Bluetooth module in one of my radios - the same behavior was reproduced.
I've attached a screenshot of the setup - [Link to screenshot](https://onedrive.live.com/?authkey=%21AF9KN5W0jZuSl0E&cid=63915C2B4E5A1C61&id=63915C2B4E5A1C61%21323107&parId=63915C2B4E5A1C61%21323106&o=OneUp)
The trainer lost and recovered happens within 2 seconds. Sometimes the control surfaces go to a unpredictable position as a result. I almost lost my 78" EF Extra 300 while this happened yesterday but luckily the flyer in the Master was skilled enough to recover the plane from a inverted with nose down position close to the ground. 
We are definitely FrSky X20S and Ethos fan, love the radios (we have 5 among our club members so far). This is certainly a very serious issue for those of us intending to use the Bluetooth trainer feature. Please let me know if I can be of help by providing any other information.

**Comment by imnav8r** [comment]
I have experienced the exact same thing between my X18 and X20S. Both radios have the 1.4.3 firmware update and have been configured correctly with the X18 as Master and the X20S as Slave using the wireless Bluetooth function. I am using the left momentary pushbutton on the back of the X18 to transfer control to the X20S. Consistently getting "Trainer Lost" and Trainer Recovered" alerts even though we are standing right next to each other. Does anybody have a source for a cable I can use instead of the Bluetooth?

**Comment by jeffgrain** [comment]
any 3.5mm mono male to male will work just fine.. you can even use a stereo cable..

**Comment by imnav8r** [comment]
Okay thank you very much for the information!

**Comment by subhrabose** [comment]
imnav8r, I found out that if you are standing side by side within 4 feet then the link works fine for all practical purposes... not ideal but workable.

**Comment by pld74** [comment]
Any idea what is the designed distance between radios when using BT connectivity?

**Comment by pld74** [comment]
> I did find that setting the channel count from the default 16 to 8 decreased the latency of the signal.. and improved the connection.. as for the designed distance between radios... only FrSky can answer that.. but testing found it as mentioned 4 to 5 feet ... and even that proved unreliable since I did get " trainer lost " error.. so it comes back to a cable being the only reliable means with frsky..
> 
> On another note.. some time ago I did the DIY hack of installing a Rx in the module bay of my old X9D and binding it to the buddy box.. with great range and success

Thanks. I will await further information from FRSKY-RC with a possible fix to this to get ready for the 2023 flying season.

**Comment by pld74** [comment]
> > I did find that setting the channel count from the default 16 to 8 decreased the latency of the signal.. and improved the connection.. as for the designed distance between radios... only FrSky can answer that.. but testing found it as mentioned 4 to 5 feet ... and even that proved unreliable since I did get " trainer lost " error.. so it comes back to a cable being the only reliable means with frsky..
> > On another note.. some time ago I did the DIY hack of installing a Rx in the module bay of my old X9D and binding it to the buddy box.. with great range and success
> 
> Thanks. I will await further information from FRSKY-RC with a possible fix to this to get ready for the 2023 flying season.

But you can provide the link to the hack, am curious.

**Comment by jeffgrain** [comment]
here is the link.. BUT !!!  be very careful..  the pinouts in the back are not what you might think.. so read everything carefully .. as to which pins you are connecting to.. also the pwr pin is not regulated so what ever your Tx battery is that is what will be on the power pin.

https://www.instructables.com/Simple-Taranis-X9D-Wireless-Trainer-Using-SBUS-Rec/

**Comment by mawzthefinn** [comment]
FYI - the new FWTM modules will bring a factory receiver-based trainer system to the table. Lite and JR versions now available.

They do require 1.5.0 for support, as that's where SBus trainer support in the module bay is added.
