### ISSUE TITLE
Low RSSI signal

### ISSUE THREAD

**Issue by jufelap** [FrSkyRC/ETHOS-Feedback-Community#1102]
My question is.

Is there a difference in output signal strength between the FCC and EU versions?
Why can't the output power be adjusted the same as at 900 MHz?

I have the EU version and I get a low RSSI alarm at 500 meters! Radio X20S receiver GR6.
Antenna arrangement is correct, shouldn't be a problem.
I have the latest software on both the Radio and the receiver.

The other issue is that it is a DLG model.
So I am flying with a 1 cell lipo.

Does the output power have to do with the voltage and with 2 cells would my problem disappear?

However, almost everyone uses 1 cell because they can't fit the bigger battery or they need to charge it after a very short time :-(

**Comment by Ceeb182** [comment]
In 2.4Ghz FCC or LBT, the transmission power is exactly the same. So this does not influence the transmission range. The biggest difference between the FCC and European regulations (LBT for Europe) is on the transmission conditions: in FCC you transmit successively on a series of channels of the 2.4GHz band without worrying about the current occupation of the channel, in LBT you transmit successively on a series of channels of the 2.4GHz band but if the current channel is already occupied then the radio switches to the next channel to avoid radio frequency pollution (this is the LBT=Listen Before Talk principle). From my point of view, this difference is imperceptible.

In 900Mhz, the difference between the FCC and European regulations are more important because the authorized powers are different according to the uses, the emission frequencies are different (FCC = 900MHz, EU = 815MHz) and the occupation rate of the bands are different.

Concerning the receiver battery voltage, if I stick to the technical documentation the minimum voltage indicated is 3.5V, so it is possible to go up to 8% of the capacity of a single Lipo cell (it is wise to set an alarm at 10-15%, i.e. 3.6V). 

Being only a user, I leave it to FrSky to confirm or correct information presented here.

**Comment by EngelMT** [comment]
You have a problem with hardware or mounting situation for sure. We checked the real range with a FPV and flight controller controlled plane. With GR8 receiver 3.6 km and with R8 Pro 3.7 km up to the point off fail safe.

By the way. In Europe the ETSI rules not allow to use more then 100 mW output with 2.4 GHz.

**Comment by pld74** [comment]
> You have a problem with hardware or mounting situation for sure. We checked the real range with a FPV and flight controller controlled plane. With GR8 receiver 3.6 km and with R8 Pro 3.7 km up to the point off fail safe.
> 
> By the way. In Europe the ETSI rules not allow to use more then 100 mW output with 2.4 GHz.

Any idea what FCC 2.4 power output is?

**Comment by Ceeb182** [comment]
The transmit power in the 2.4GHz band is identical in FCC and EU-LBT: it is 100mW i.e. 20dBm (according to FCC test documents ID: XYF-TDX20HDSP and European standards)
