### ISSUE TITLE
No  throttle reverse function

### ISSUE THREAD

**Issue by 00steven** [FrSkyRC/ETHOS-Feedback-Community#12]
There are multiple ways to let the throtle stick work in teh folowing manner.
Botom is maximum power 
Top is minimum/no power
The only way to have a correct trigger on the timer is by special function. 

There should be an easy way to let the radio know you use the throtle revers. 
As long as this is not the case I wil go back to open tx.

**Comment by Hobby4life** [comment]
Outputs menu, reverse output of throttle channel. this is how it is done in OTX too.

**Comment by 00steven** [comment]
Not true! There is a function in the plane setup menu to select throttle reverse
![16168492117078157583928891263500](https://user-images.githubusercontent.com/12456410/112721196-ecc56c80-8f02-11eb-874c-61f85b36dce6.jpg)

**Comment by Hobby4life** [comment]
This is just the thing why I stepped into OTX in the first place.. I want to have full control of in every model. No prea-djusted things.
Therefore I prefer to reverse it in Outputs. So I can decide per model. As Ethos does offer the same approach I like to use that again in Ethos too.

**Comment by 00steven** [comment]
I don't get it why something easy should be difficult.
I don't like make a logical switch just so I can start a timer at the right throttle position. 

Last thing I say about it. I hope to see a change.

**Comment by dobosatti** [comment]
I can't set up a basic thing with ETHOS.
That the throttle base position is reversed. That's how I use gas. (see picture)
It’s ridiculous that ETHOS doesn’t know. During my 35-year RC career, all the radios I used knew this feature. Why doesn't ETHOS know?
When turned on, it warns you that the throttle is in the wrong place. I can't start the timer with the throttle either, because the clock is already running when the Tx is turned on.
![IMG_20210414_084955](https://user-images.githubusercontent.com/32070803/114668447-09cead80-9d01-11eb-8458-e7ada2e88123.jpg)

**Comment by dobosatti** [comment]
This problem is still not solved !!!
When is the solution expected?

**Comment by dobosatti** [comment]
Problem solved!
Thanks!
