### ISSUE TITLE
Log Switches and "Not controlled by trainer".

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1219]
Why is this setting possible here?

![image](https://user-images.githubusercontent.com/16795828/146401422-1120fa74-8e95-4619-b24b-7b7d6ca83b5b.png)

**Comment by Hobby4life** [comment]
If you have a logic switch controlled by a function that only master may controll.. you can disable slave here.

**Comment by EngelMT** [comment]
O.k. thanks for explaining.

**Comment by EngelMT** [comment]
I would like to open again here. I think this function is wrong at this point.  Wouldn't it have been possible to integrate this as an option directly in the teacher / student menu without logical switches.

I see the great danger that ETHOS will become more and more extensive, but also more and more confusing.  We have long been a long way from software that can be operated easily and without a manual.

**Comment by Hobby4life** [comment]
> I would like to open again here. I think this function is wrong at this point. Wouldn't it have been possible to integrate this as an option directly in the teacher / student menu without logical switches.
> 

No, because then other functions are automaticly be disabled too.

> I see the great danger that ETHOS will become more and more extensive, but also more and more confusing. We have long been a long way from software that can be operated easily and without a manual.

We must accept that at one point a good reference manual is needed due its flexibility.

**Comment by hrenz** [comment]
but there is no symbol to recognize this funktion

**Comment by Hobby4life** [comment]
> but there is no symbol to recognize this funktion

Symbol? can you explain?

**Comment by bsongis-frsky** [comment]
I do agree about changing the name, I will need your idea about it, it's sometimes difficult to find a perfect name in a few words.
I would also agree about removing this function, but it is powerful without adding any complexity to the beginner. So you will have to find a better way to achieve the same result ;)

**Comment by Hobby4life** [comment]
> So you will have to find a better way to achieve the same result ;)

No not me, I've been working hard for months to provide examples to get this "basic" feature in ethos. I have already given many examples here on git and on skype.

Nicholas eventually came up with this method himself. This function should not be lost, perhaps the option in logic switches is not in the right place. then something has to be found. this option is simply most important for a good trainer system.

The idea is so very simple, 

Before coming up with ideas again, try the following logic function in a trainer configuration.

![screenshot-2021-12-17-27118](https://user-images.githubusercontent.com/55426642/146500572-9cf6d3c4-bf88-4214-9b04-eddbb524dabb.png)

**Comment by bsongis-frsky** [comment]
Don't take it bad. I have myself pushed Luo for his idea which is excellent.
But perhaps Andreas and hrenz will come with a better idea.
I have some experience of this problem which is difficult to solve in OpenTX.
Here we have source options and it resolves many design issues.

**Comment by bsongis-frsky** [comment]
Changed by "Ignore trainer input". 
Feel free to reopen if you come with a better idea for the same flexibility!

**Comment by hrenz** [comment]
With your description it is already clear to me what you do with it.
Automatically return to the teacher when you move the teacher stick. 
This is also available in openTx as a 3 line program.

But the option has no symbol so that you can see it in the overview.
Switches have symbols, Not ! , EDGE Alt Gr197 
Encoders have inverse -
Ignore trainer Input is in the list of logical switches
not to recognize.
If you do this, you should give a fixed name to it
e.g. Autoreturn to teacher 
------------------------
The other is:
This all belongs to the menu teacher/student
which is currently only rudimentary available
because you just allow everything.  
You have to be able to enable/disable Sticks/encoders, switches, log switches like Jeti and Powerbox do.

The student should not wildly switch his switches and 
thus disturb functions of the Lerer transmitter. 
He gets max 1,2,3,4 sticks/encoder and 1,2,3,4 switches 
depending on his abilities.
