### ISSUE TITLE
Throttle cut "trigger value" must react on channel value instead of THR stick value.

### ISSUE THREAD

**Issue by prikrylm** [FrSkyRC/ETHOS-Feedback-Community#127]
Throttle stick on minimum on the acro mode means full throttle to heli motor, so in this case is not good to unlock motor by Throttle lock switch.

**Comment by MIKE-DAILEY** [comment]
We are not able to change the existing Throttle Cut feature because it currently meets the requirements of glow, gas and most EP applications.  Suggest you create a custom cut feature for your application.  Please see example Free Mix cut and you can replace Active condition switch SD with a logic switch to meet your requirements.        

![screenshot-2021-04-26-47106](https://user-images.githubusercontent.com/11791852/116116224-ea346f00-a688-11eb-995f-3b3887db7af0.jpg)


![screenshot-2021-04-26-47111](https://user-images.githubusercontent.com/11791852/116116244-eef92300-a688-11eb-97a4-a6f6c93d64ca.jpg)
.

**Comment by prikrylm** [comment]
I think, check "trigger value" based on stick position is not good idea in the same manner as control the stopwatch with THR stick position, because of helicopters THR stick min position on acro mode means full trhottle value on thr channel. Is it problem not to check stick value but to check the mix row value before it is written to channel, as OpenTX do?

**Comment by bsongis-frsky** [comment]
In OpenTX you can decide what is the Engine channel to check
- it can be the Thr stick (90% cases)
- it can be an analog
- it can be any channel
Is it what you need for your application?

**Comment by prikrylm** [comment]
I'm flying helicopters a lot and THR stick position and value on thr channel are different values, so I need to check output of mixer row, not the stick position. Now, in case of ETHOS v1.0.3 it can be reached by two mixer rows for throttle, but it looses elegance of single "clever" throttle mixer row.

**Comment by bsongis-frsky** [comment]
Would you please double check your OpenTX settings? What is your Throttle / Engine source? A stick or a channel?

**Comment by prikrylm** [comment]
Heli engine source in OpenTX is "logical" input or channel,  it cannot be thr stick directly. See (almost) sipmplest 3d heli example settings: [heli_X12S.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/6382189/heli_X12S.zip)

Otherwise unless thrcut is not emergency feature, probably works fine. (https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/132)

**Comment by bsongis-frsky** [comment]
As explained above, your throttle source in opentx is "Channel 4"

**Comment by prikrylm** [comment]
I've been thinking about it and I'm probably using ThrCut inappropriately.
