### ISSUE TITLE
missing offsets for ailerons / flaps

### ISSUE THREAD

**Issue by strgaltdel** [FrSkyRC/ETHOS-Feedback-Community#138]
Hello,

at least for gliders, it is almost always necessary to give wing servos a substantial offset.
This is a tribute to the very asymmetrical deflections of flaps and ailerons.

"Offset" means that I shift the operating point / "neutral point" of the servo without changing end points or "scaling" in the respective direction of rotation.

![offset](https://user-images.githubusercontent.com/20392683/116201345-b1080780-a739-11eb-8bff-f0def2070b63.jpg)

At the moment, this can be done with additional free mixers,
However, this counteracts the basic idea of making Ethos as simple, clear and easy to use as possible.

I therefore suggest to integrate a parameter for offset per servo in the settings of aileron and flaps.

Regards

**Comment by Hartinger** [comment]
I would prefer just one offset value for ailerons and one for flaps (and one for any additional pair of flaps).
The principle to compensate differences of the servos in the outputs should be maintained IMHO.
The mixers should define the logical signal flow, assuming identical servo pairs.

**Comment by strgaltdel** [comment]
Following the "ease to use" mantra i do completely agree.
But an single value should apply to ONE pair of flaps,
in an 6..8 flap config there might be differences between inner and outer ailerons etc..

**Comment by aalain8** [comment]
Hello,
Did you see that the subtrim is possible in the outputs.

**Comment by Hartinger** [comment]
Hello,
subtrim should be used to compensate for small differences in the servos.
Contrary to that, the offset for wing servos in a glider setup is part of the logical mixer programming.
Whilst subtrim could be used as a workaround, this would contradict the general principle that outputs are the means to adapt to the "real world".

**Comment by RC-SOAR** [comment]
Agree, an offset is needed to cater for asymmetric flap movement. However the offset needs to be at the mixer level.

A key point is that It is a constant offset, applied regardless of flight mode, other mixes etc.

On my Ethos setup I am using a separate 'always on' Free mix for this. It's easy to do, the problem is that not everyone knows that it's required, or why.

**Comment by RC-SOAR** [comment]
This diagram describes why the offset is required, and how it's implemented at the mixer level. It's taken from my OTX setups, but same principle applies for Ethos.

![Pana_receipt_0001](https://user-images.githubusercontent.com/6317479/120805199-69954800-c53d-11eb-8d65-1e76411993bf.jpg)

**Comment by strgaltdel** [comment]
totally agree,

as mentioned above, you could implement "wing servo offsets" by using free mixer or the predefined flap mixer, using the max-functionality.
One mixer could define offsets for all wing servos.

![offset](https://user-images.githubusercontent.com/20392683/120807972-d9f59680-c548-11eb-949f-f489a70fc891.jpg)

But, in my opinion, increasing the number of mixers means less comfort and no "ease of use", which counterfights the ethos-mantra.

**Comment by RC-SOAR** [comment]
> as mentioned above, you could implement "wing servo offsets" by using free mixer 
> _or the predefined flap mixer_, using the max-functionality.

Problem is the offset must be active even if the host mixer is disabled. For example, if you had offsets defined in the Butterfly mix, but it was inactive, the offset would still need to be applied. I think this would be confusing.

**Comment by bsongis-frsky** [comment]
@RC-SOAR I remember we discussed this issue and we considered we had the solution, no?

**Comment by strgaltdel** [comment]
Ich kehre zurück am 09.08.2021.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] missing offsets for ailerons / flaps (#138)" gesendet am
27.07.2021 12:14:20.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by RC-SOAR** [comment]
> @RC-SOAR I remember we discussed this issue and we considered we had the solution, no?

I don't recall the exact details, but just to summarise a typical a four-wing F3X glider setup:

- Ailerons - travel can be treated as symmetrical, usually. But if not, the following also applies to ailerons.
- Flap surfaces - travel is _asymmetrical_  measured from neutral. The servo centre will be 'floating', between the flap neutral and the lower end point. 
- An offset mix is required to map bring the flaps to neutral with crow stick at idle.
- Assuming properly adjusted outputs, the offset mix is the same on both sides.

The offset must be 'Always On', and there must be only one instance. For that reason, it doesn't makes sense to include it the stock mixers, since these can be disabled. It's best to have a separate mix (I currently just use a FreeMix with Active Condition =Always On). 

If you wanted to add a dedicated 'Flap Offset' mix, I think four fields would be sufficient:

- _Name_: "Flap Offset"
- _Offset_: integer value or linked to source
- _Channels count_
- _Outputs_

Or maybe make it completely general and call it simply 'Offset' mix.

I think this would work well with the butterfly mix. A complete crow implementation might be:

**Butterfly mix**
Input: Throttle stick
Curve: [100, 0] -- maps idle end of throttle stick to zero
Channels count: 2 ailerons + 2 flaps
Weights: as required, up for ailerons, down for flaps.

**Offset mix**
Offset: flap offset as required -- adjust with throttle stick in 'idle' position
Channel count: 2
Outputs: 2 x flap channel

**Comment by RC-SOAR** [comment]
On further thought, I agree with the idea of @strgaltdel  that offsets should be independently adjustable. So

- Name: "Offset"
- Channels count
- Weight [...]
- Outputs [...]

**Comment by strgaltdel** [comment]
Ich kehre zurück am 09.08.2021.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] missing offsets for ailerons / flaps (#138)" gesendet am
27.07.2021 15:54:43.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by strgaltdel** [comment]
Ich kehre zurück am 09.08.2021.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] missing offsets for ailerons / flaps (#138)" gesendet am
27.07.2021 15:43:34.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by Joetrin** [comment]
We originally asked for multiple offsets in mixes to allow for things like Butterfly or Crow, not just for gliders.  We use it in 3D aerobatics on high wing models as well.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/378

**Comment by strgaltdel** [comment]
Ich kehre zurück am 09.08.2021.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[FrSkyRC/ETHOS-Feedback-Community] missing offsets for ailerons / flaps (#138)" gesendet am
27.07.2021 16:40:58.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by mawzthefinn** [comment]
I believe this was addressed with the introduction of the Offset and Airbrake mixes.

**Comment by strgaltdel** [comment]
Yepp,
 "airbrake" mixer is a sufficient substitude

thanks &
regards
