### ISSUE TITLE
LUA: add ram used function

### ISSUE THREAD

**Issue by i3dm** [FrSkyRC/ETHOS-Feedback-Community#1380]
since ethos has limited RAM for widgets, please add a function that can prints RAM used to allow proper design and testing of widgets.

**Comment by bsongis-frsky** [comment]
please not that all systems that I know have limited RAM for widgets and bitmaps ;)

**Comment by i3dm** [comment]
> please note that all systems that I know have limited RAM for widgets and bitmaps ;)

naturally. but we have come to a point where can not run even 2 widgets with background.

**Comment by bsongis-frsky** [comment]
2 widgets with full screen bitmaps badly encoded won't run, but if you spend time on learning bitmaps encoding you will get better results

**Comment by bsongis-frsky** [comment]
`system.getMemoryUsage()` added

**Comment by i3dm** [comment]
> 2 widgets with full screen bitmaps badly encoded won't run simultaneously, but if you spend time on learning bitmaps encoding you will get better results

if anyone writing a lua needs a PhD in bitmap encoding i have a sense we are missing the point.

im loading the bitmap during first cycles of run time. not during init. it does NOT help.

**Comment by Hobby4life** [comment]
I fact a regular user must not have to need tools to import images.
Ethos shoud auto correct/convert it upon first load and ditch the old one.

This makes it more friendly for users in almost all cases.
Specially model files.

**Comment by i3dm** [comment]
totally right.
with all do respect i dont think my wuidgets are written poorly at all. the resources available by Ethos for bitmaps are very low.

**Comment by Hobby4life** [comment]
I can follow it reasonably well, but if my neighbor just wants to load a simple GPS map, all kinds of tools have to be used. this should and can never be the intention.

If ETHOS expects something, then it should be solved within ETHOS not on the user side.

**Comment by i3dm** [comment]
> `system.getMemoryUsage()` added

please write an example about how to print 4 sepeate values which are returned by 'system.getMemoryUsage()`

**Comment by bsongis-frsky** [comment]
@Hobby4life the radio has limited RAM, this is a fact, you cannot expect it to load all kind of bitmaps

**Comment by bsongis-frsky** [comment]
The App will be able to convert bitmaps for the average user, we are currently working on it

**Comment by bsongis-frsky** [comment]
@i3dm please use RCG for such questions, this is a repository for issues only

**Comment by i3dm** [comment]
> @i3dm please use RCG for such questions, this is a repository for issues only

sending us to RCG every time a new function is written is futile, since no one but the programmer (yourself) knows the answer. this is getting absurd.

**Comment by bsongis-frsky** [comment]
This is a screenshot that you sent me in the same time on Skype, you should search a little bit before annoying me on Github and Skype

![image](https://user-images.githubusercontent.com/50834778/151137897-9e813ed3-0e4c-4c4a-8457-cefc7c09c8e0.png)

**Comment by i3dm** [comment]
My comment was in general and not about this specific case (which i managed without your help)

**Comment by Hobby4life** [comment]
> @Hobby4life the radio has limited RAM, this is a fact, you cannot expect it to load all kind of bitmaps

@Adelaxie 

I understand it, but the majority of average user not.
I daily get calls and emails from clients with questions about this.

I now see there is an app in development that covers this, thats good news.

But it is how it is represented in the first place.
You think of the best way of an image format.. BMP565, thats ok.. nothing wrong with it.
But at the same time you must have known that this is not an standard format for anyone!
So directly at least an instruction had to been provided how to create such files.
There was none at the release date.

Besides this you can not expect that the majority of users are on the same level as you.
A simple bitmap for a gpsmap is a pita to create for an averag user.
Please do understand that every time things newly are developed, it must be super simple for users to use.
If something new is developed a bit out of the ordinary, then directly you should supply tools, or write something in ETHOS that covers this.
Now people are left in the dark, even with official releases there is no documentiation about this. documentation is far behind of with every release. (Lothar does a very amazing job to keep up with everything. big thumbs up for him)
But in 2022 manuals should be online, easy to find and search.

I really dissagree that RCG is the only place for this, thats is utterly wrong.
Frsky should have their own forum to discuss this.
If people need info of have questions they firstly go to the frsky website to search for answers. they dont think about RCG.
Many of my clients never heard of it anyways. so that is not the way.

The whole idea of this has to be drasticly changed from now.

If all of this can be improved from now on, it saves A LOT of questions for you daily, and me and others.

**Comment by i3dm** [comment]
> The whole idea of this has to be drasticly changed from now.
> 
> If all of this can be improved from now on, it saves A LOT of questions for you daily, and me and others.
> 
> And keep in mind that this is not an opensource product, people paid for this os.

couldn't agree more. this is getting absurd.
@Adelaxie

**Comment by i3dm** [comment]
I have a simple question.
how to clear image RAM from Ethos.
for that i have to go to the RCG group, ask there, wait for someone to answer (when 100% of my questions there so far have never been answered).
how is this supposed to work without actual support?

**Comment by Adelaxie** [comment]
answered.
