### ISSUE TITLE
Flight Mode Naming in Mixer

### ISSUE THREAD

**Issue by dunback** [FrSkyRC/ETHOS-Feedback-Community#1490]
When selecting Flight Mode as the category in the mixer, the pre-identified user Member is shown for selection. But, when that user member name is selected it is shown as "FM0", "FM1" etc. and NOT by the user member name. Would it not make more sense to show the user identified Flight Mode name?

**Comment by WismyYao** [comment]
![image](https://user-images.githubusercontent.com/16497598/155093535-38c9a934-9823-426f-892b-660ab936f6e9.png)
Do you mean the Flight Mode shown here?

**Comment by dunback** [comment]
I think so.

This is where I select the flight mode as the mix enable category which shows my member name (LOW_RATES) as the enabler.



But the Mixer screen then shows “FM0” as my selection. I think it would make more sense to show my member name “LOW_RATES” as selected.



Not a biggy but it would be nice in my opinion.

Cheers for now!

George Coupar

**Comment by BernhardFe** [comment]
Hi,
In logic switches there is a similar situation. The name of the flight mode is missing as well. The number is shown instead of the given name. It would be helpful to see the real name of the flight mode as well in the logic switch. Example Flight Mode 1 is "Start". Selecting it in the logic switch it will be available for selection with the given name. After selection the text changes in the switch to "FM1" instead of "Start".
The Listing and display in the mixer should also show the given name.
Best Regards
Bernhard

**Comment by mawzthefinn** [comment]
This was addressed in 1.4.0

**Comment by dunback** [comment]
Great! Thanks!  Appreciate all you do. 

Cheers for now!

George Coupar
