### ISSUE TITLE
Switching models

### ISSUE THREAD

**Issue by kramgrand** [FrSkyRC/ETHOS-Feedback-Community#1549]
I have just updated Ethos to 1.1.3.  and noticed that you can no longer switch to a different model by just holding down the models icon in model select menu.  
It has gone back to touching the icon to highlight it, then touch it again to bring up the dropdown menu and then touch it again to select "Set current model"
It has changed from a one touch model select to a three touch model select.

**Comment by phaedra-tm** [comment]
In the field, this way of selecting a different model leads to inadvertently selecting "clone model" instead of "set current model"
Before I was aware of the long press functionality to change model, I was constantly creating clones of my models. At the end of the flying day, I had to clean up the models list and rebind some models (because I kept the cloned version instead of the original).  
I'm still using 1.1.1, and I consider the long press method a big improvement over the 3-touch version.  The latter is a nightmare to use.
