### ISSUE TITLE
request VAR Mixer - Flight Modes 

### ISSUE THREAD

**Issue by Cipta-de** [FrSkyRC/ETHOS-Feedback-Community#1566]
Hello, 😀
I would be interested if there is a specific reason why the function to select FlightModes adn Active Condition in VAR-Mixer is not available. 
In my opinion it would be very beneficial in some situations if it were possible to activate the variables in different states. 
For example I could have with the same Switch different Variables in different Flightmodes.
Greetings

**Comment by BernhardFe** [comment]
This would be useful for Helis to have fixed Rotor speed depending on flight mode as well.
The same can be used then for the stabilisation to program fixed values depending on flight modes for Helis.
Antother use case are fixed positions of actors in function models. This would make it easy to programming and adjustment.
9 values (modes) would be great.

**Comment by Cipta-de** [comment]
Yes that's  true - it's possible to use a FM in weight - but that's really not the same what I would like to expect. For example 6Pos switch with 6 differnt weights in FM1 and for FM2 the same 6Pos switch with different weights. I don't know how to do this.

**Comment by mawzthefinn** [comment]
Actually, I think the best solution for that is to make the Function Switches behave more like a true 6-pos. Then you could do this with a Free Mix and 2 curves, with the FSW's as the Source.

What you want is easily done with the 6-pos on the Horus radios, but not on the X20's because of how the Function Switches are setup, they don't have a default weight unlike a real 6-pos.

**Comment by Cipta-de** [comment]
In the logic switches there is no Funktion Switch as source!! And if I would need six LS - back to my first question: 
Would it be possible to have FM and Active Conditions in the VAR Mixer or is there a specific reason to not have?

**Comment by mawzthefinn** [comment]
Function Switches are certainly usable as a Value for an AND logic switch.

But you are correct that you would need 6 of them to do what you wanted (actually 5, because you have a default value when the others aren't true)

FM and Active Condition for the VAR mixer to me invalidates the reason for the VAR mix, it's a place to store values and you can select between those values by switches. 

I'd rather see them fix the 6-pos implementation on the X20 so you can use it like the 6-pos on a Horus. You are really just using the VAR mix to work around the incomplete 6-pos implementation on the X20(S)

**Comment by Cipta-de** [comment]
IMO no need for fix of 6Pos switch because I can easily do with a VAR-mix. 
![VAR-EXPO auf CH20](https://user-images.githubusercontent.com/78207054/161282741-7fc0934d-57af-4828-8e57-c77912d47fe1.JPG)
FS auf CH20
![Expo-Aileron](https://user-images.githubusercontent.com/78207054/161282855-74f61cca-3212-49f7-99b1-3f099be84799.JPG)
CH20 as source and different curves for FM or switches or ... - my solution 
There are allways different ways to solve a task -  the solution with diffent curves in Mixers works fine - thanks for the hint

**Comment by mawzthefinn** [comment]
Except there is a reason to fix the 6-pos limitation, because as it stands you can't port a model using the 6-pos on the X10 or X12 to an X20 without reprogramming to work around the limits of the Function Switches (ETHOS currently addresses this by mapping teh X10/X12 6-pos as an extra Pot)

**Comment by mawzthefinn** [comment]
After a lot of thought, I've decided I like the current implementation better given the multiple FSW configurations that would each need a set of default analog values defined and withdraw my last comment.

**Comment by BernhardFe** [comment]
So why not closing this case. I think ist is solved... :-)

**Comment by mawzthefinn** [comment]
I’m giving @Cipta-de a chance to comment before closing due to the solution being really a workaround.

**Comment by Cipta-de** [comment]
Hello,
totally fine - You can close it.
👍
