### ISSUE TITLE
analog sticks center Tone option

### ISSUE THREAD

**Issue by Droptank** [FrSkyRC/ETHOS-Feedback-Community#1574]
would like to see a simple toggle switch perhaps in Hardware menu to enable or disable "beep" when chosen analog stick reaches center. Useful in Helicopter throttle/pitch stick.   I know this can be done with logic switch and special function play track but it should be a simple toggle.  A beep like the trim click would be perfect.

**Comment by BernhardFe** [comment]
And a haptic vibration as an alternative or both acoustic and haptic as well. I had it in the past with a V-Bar Control and it was/is useful for heli flying and for gliders if the upper and lower part of a stick has different functions. (gliders: e.G. upper motor speed, lower butterfly)

**Comment by mawzthefinn** [comment]
Custom stuff like this is exactly what Logic Switches and Special functions are for, rather than cluttering up the hardware menu with duplicate functions.

That said, it would be REALLY nice to be able to apply sets of LSW/SF's to a new model so you don't have to recreate them every time. We need some sort of library or templating function for that.

**Comment by BernhardFe** [comment]
I agree to the proposal, I'm just using the logical switches for creating a signal in the stick middle for every model. The "=" is not working reliable but there is "nearly" function that works. :-)

Regarding the second proposal to have predefined "Sets" it would be great to have them. Reusing all the programming the only option is to clone a model and then manually making adjustments. For me it is less work than recreation. But because of this I can not use the assistant for new models, what is an also not a good solution. 
Another use case would be if I have a new function in one model and wan to apply this to others to update them. This is also a very manual procedure.
This sets of function might be not only for the LSW, but also for Mixers, Special Functions, Curves, Flight Modes and Telemetry. Because they depending often from each other. 
Considering this, it might be also an option for a first option instead of macros to be able to mark several items (group of LSW) anywhere in one step and then copy them to another model. This general function might be more flexible. Nevertheless I appreciate also global function groups. But this might be more complicated to implement, I guess.
