### ISSUE TITLE
SxR script

### ISSUE THREAD

**Issue by drummaker** [FrSkyRC/ETHOS-Feedback-Community#1585]
When configuring an SxR  I have tried Access sr6 sr8 and sr10  nothing below Self Check is highlighted and cannot be changed  this includes Self Chec

So I cannot adjust sensitivity or really anything but channel reversals etc

this is on version 1.2.1

**Comment by Jetman1** [comment]
The same problem exist on RB30 SxR setup with X20s FW 1.1.4, TD RF FW 2.2.1 and an R8pro Archer RX with FW 2.1.10. No self test via lua possible and no gain values adjustable. Same problem with TD10 RX. 😬😬😬

**Comment by drummaker** [comment]
How ciuld this happen?   I can't  go back to 1.1 because the models I have created since upgrade don't show up.   I swear frsky should either quit making stabilized receivers, or make sure they are really supported

**Comment by EngelMT** [comment]
I tested it at the moment with X20 and X20S and ETHOS 1.2.1 and SR8 Pro with newest Firmware V2.1.1.0.

No problem to connect the receiver to the SXR script. Works well und adjustments are possible.

**Comment by Jetman1** [comment]
Hello Andreas, can you test it with 1.1.4 in combination with Access R8 Archer and TD 10 Receivers. It does not work in my own setup. Thanks, Danke.

**Comment by Jetman1** [comment]
Hello Drummaker, when downgrading from ethos 1.1.4 to 1.1.1 I also lost all models and radio geberal settings. I copied the models from PC to the SD card of the radio, but that does not help. After re-flashing the firmware. bin 1.1.1 to the flash drive of the radio the models appeared again. I do not know why, but that worked. General settings had to be made again by hand. Frsky should work on stability and not on new products every week.

**Comment by Jetman1** [comment]
It was my mistake, in the meantime I lost the orientation a little bit. I have got the problems with the mentioned RXs in combination with the RB30 with actual FW. No self test and no adjustable gain values on Ethos 1.1.4. I have not tested it on 1.2.1 because I need a FW version for real flight. And only for understanding I like frsky and bought one of the first X9D in germany at your shop and use opentx since 10 years (Turnigy 9x with homemade programming Interface). But in the last years it is possible to loose the overview at FW versions and updates. Manchmal ist weniger eben mehr!

**Comment by drummaker** [comment]
OK upgrading receivers made it work properly
latest version

I haven't yet tested 8SR or 6.... will let you know

**Comment by pgee63** [comment]
I cannot change the gain settings on my ACCST S6R  via the SXR tool on my X20(1.2.1RC1).
On the ACCESS SR6 everything works perfectly( all equipped with the latest firmware).

**Comment by EngelMT** [comment]
Seems to be a problem with S6R and S8R receivern. Not possible to make all settings. With SR8 for excample it works perfect.

**Comment by chenbevis** [comment]
> 這是我的錯誤，同時我有點迷失方向。上述 RX 與帶有實際固件的 RB30 結合使用時，我遇到了問題。Ethos 1.1.4 上沒有自檢和可調增益值。我沒有在 1.2.1 上測試它，因為我需要一個 FW 版本才能真正飛行。只是為了理解我喜歡 frsky 並在您的商店購買了德國第一台 X9D 並使用了 10 年以來的 opentx（Turnigy 9x 與自製編程接口）。但在過去幾年中，可能會在固件版本和更新中鬆散概述。Manchmal ist weniger eben mehr！

frsky frsky has to fix the firmware of rb30 and rb40, you can now use opentx and accst to set rb30, then change back to x20s and it will work

**Comment by Jetman1** [comment]
I have got it running (RB30) by using Ethos 1.1.1 and TD 2.2.1 and switching off the sensor alarms of the RB30 sensors. With that combination the gyro gain values are changeable and sensor lost occurs only from time to time. But I am not sure if it is stable and no other bugs are existing. It is not the best solution and I will observe the functionality especially when flying a jet.

**Comment by drummaker** [comment]
Frsky have never taken the stabilizer config scripts seriously.    I don't understand it, and the fact that no one has responded to this or the other thread about this is just more evidence of that

**Comment by EngelMT** [comment]
The "sensor lost" warnings seem to be triggered by the 868 MHz sensors. I have brought this issue directly to FrSky's attention once.

**Comment by Adelaxie** [comment]
> I tested it at the moment with X20 and X20S and ETHOS 1.2.1 and SR8 Pro with newest Firmware V2.1.1.0.
> 
> No problem to connect the receiver to the SXR script. Works well und adjustments are possible.
> 
> Tested only with single receiver and not with RB30.

thanks for the test! and RB firmware is updated to work with Lua or ETHOS. please check.

**Comment by jcerbilla** [comment]
hi, in my system, x10sexpress with ethos, all in the last firmware and software, rb30+2 archer r8pro, i'm unable to enter the selfcheck to calibrate the servo travel, in opentx have no problem, but in ethos is impossible.
I'm thinking to pass all my systems to ethos, but this issue is an stopper for me.

**Comment by EngelMT** [comment]
Hi ???,
 
in ETHOS you have to make the self test in the SXR Menu. There you will find a switch „Self Check“. Please test it. I never heard the the self test is not working in ETHOS.
 
 
Mit freundlichen Grüssen
With best regards
Andreas Engel
Engel Modellbau & Technik

Eberhäuser Weg 24
37139 Adelebsen - Güntersen

Tel.: ++49 / (0) 5502 - 3142
Fax: ++49 / (0) 5502 - 944712

web:www.engelmt.de
<blocked::http://www.engelmt.de/>
web:www.frsky-forum.de
<http://www.frsky-forum.de/>

***@***.***

USt.ID-NO: DE 167910105
WEEE Reg.-Nr. DE 66393653
BattV: GRS 108121212
VerpackV: D-59624-2008-0196
 
 
Von: jcerbilla ***@***.***>
Gesendet: Sonntag, 7. Mai 2023 11:29
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Andreas Engel ***@***.***>; Comment ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] SxR script (Issue #1585)
 
hi, in my system, x10sexpress with ethos, all in the last firmware and software, rb30+2 archer r8pro, i'm unable to enter the selfcheck to calibrate the servo travel, in opentx have no problem, but in ethos is impossible.
I'm thinking to pass all my systems to ethos, but this issue is an stopper for me.
—
Reply to this email directly,view it on GitHub
<https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1585#issuecomment-1537369134>, orunsubscribe

**Comment by EngelMT** [comment]
And trottle must be down.
 
 
Mit freundlichen Grüssen
With best regards
Andreas Engel
Engel Modellbau & Technik

Eberhäuser Weg 24
37139 Adelebsen - Güntersen

Tel.: ++49 / (0) 5502 - 3142
Fax: ++49 / (0) 5502 - 944712

web:www.engelmt.de
<blocked::http://www.engelmt.de/>
web:www.frsky-forum.de
<http://www.frsky-forum.de/>

***@***.***

USt.ID-NO: DE 167910105
WEEE Reg.-Nr. DE 66393653
BattV: GRS 108121212
VerpackV: D-59624-2008-0196
 
 
Von: jcerbilla ***@***.***>
Gesendet: Sonntag, 7. Mai 2023 11:29
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Andreas Engel ***@***.***>; Comment ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] SxR script (Issue #1585)
 
hi, in my system, x10sexpress with ethos, all in the last firmware and software, rb30+2 archer r8pro, i'm unable to enter the selfcheck to calibrate the servo travel, in opentx have no problem, but in ethos is impossible.
I'm thinking to pass all my systems to ethos, but this issue is an stopper for me.
—
Reply to this email directly,view it on GitHub
<https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1585#issuecomment-1537369134>, orunsubscribe

**Comment by jcerbilla** [comment]
thanks for the response, in the sxr menu, there is the self check option, on/off, y put in on with throttle down and does nothing, instead in opentx works on the two ways, from the menu and from the channel 12 switch

**Comment by EngelMT** [comment]
I tested it today in the morning and it works.
 
 
Mit freundlichen Grüssen
With best regards
Andreas Engel
Engel Modellbau & Technik

Eberhäuser Weg 24
37139 Adelebsen - Güntersen

Tel.: ++49 / (0) 5502 - 3142
Fax: ++49 / (0) 5502 - 944712

web:www.engelmt.de
<blocked::http://www.engelmt.de/>
web:www.frsky-forum.de
<http://www.frsky-forum.de/>

***@***.***

USt.ID-NO: DE 167910105
WEEE Reg.-Nr. DE 66393653
BattV: GRS 108121212
VerpackV: D-59624-2008-0196
 
 
Von: jcerbilla ***@***.***>
Gesendet: Montag, 8. Mai 2023 11:26
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Andreas Engel ***@***.***>; Comment ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] SxR script (Issue #1585)
 
thanks for the response, in the sxr menu, there is the self check option, on/off, y put in on with throttle down and does nothing, instead in opentx works on the two ways, from the menu and from the channel 12 switch
—
Reply to this email directly,view it on GitHub
<https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1585#issuecomment-1538049173>, orunsubscribe

**Comment by jcerbilla** [comment]
hi, finally works, using only one receiver access-24 unmapping channel 24, recalibrate gas stick, gas down, and works well.
Thanks.
