### ISSUE TITLE
Timer which would totalize the total duration of Tx working / emitting, not resetting itself whenever one changes the model

### ISSUE THREAD

**Issue by Billy60** [FrSkyRC/ETHOS-Feedback-Community#1595]
Good afternoon
Is there a way to have a timer which would totalize the total duration of Tx working /emitting, not resetting itself whenever one changes the model ? this to have an idea of the total time spent on one TX battery regardless of the models used.
2nd: is there a way to have the values in a curve appear in ms or microsecs, not only in % ? this would be on the curve definition screen. It would be useful to add a ms value to another one via a mixi. Not a % but some ms or micsec.

Thanks and keep on this excellent work !
My set is a X10Express and it runs the latest 1.2.1

**Comment by Mordee** [comment]
Demands ? Seems more like queries, no ?

**Comment by Billy60** [comment]
You are right
Sorry for my poor english,

What is your answer ?

**Comment by mawzthefinn** [comment]
You can't mix microseconds at the mixer level or via curves, because the mapping of percent to outputs doesn't occur until the Outputs level. 

Curve editing is currently separate from both mixers and outputs, as one curve can be mapped to either level. That is why there's no edit in microseconds option for curves or mixers.

**Comment by bsongis-frsky** [comment]
Please try not to mix 2 requests, it's difficult to follow. I will change the title of this one and keep only the first request (radio total time)
