### ISSUE TITLE
Suddenly black screen

### ISSUE THREAD

**Issue by wolverine202** [FrSkyRC/ETHOS-Feedback-Community#170]
The other day my Tandem x20 was no longer operable. A black screen came up and it hummed strangely. It could no longer be operated or switched off. Could only turn it off by removing the battery. Is that a bug? Would be grateful for information. It happened from now on and something was changed.

**Comment by rburrow87** [comment]
What were you doing when it happened?

I had this happen not too long ago while switching between models but I haven't been able to reproduce it. And then today, I was working on setting the name of a receiver as I was registering it with the TX and it just suddenly went into "emergency mode," but again I haven't been able to reproduce it.

Also what MicroSD card do you have? Wondering if that's related.

**Comment by wolverine202** [comment]
Didn't do anything at the time, the tandem was next to me. Had screwed on my model. SD card is the normal one that came with the delivery.

**Comment by andika207** [comment]
@wolverine202 if you upload a video it will be easier to understand your problem

**Comment by wolverine202** [comment]
Uploading X20-startet-nicht-mehr.mp4…

**Comment by wolverine202** [comment]
andika207 ***@***.***> schrieb am Mo., 3. Mai 2021, 19:33:

**Comment by Chandrayaan-git** [comment]
Looks like the problem I had ...

Could fix it with installing the bootloader.bin new.

- download Ethos 1.01 (bootloader.bin is part of the .zip)
- connect switched of X20 to Windows PC
- start OpenTX Companion on PC and select write firmware (deselect compatibility check since there is no X20 support in Companion)
- select bootloader.bin and write it to X20
- disconnect X20 and go to bootloader mode (enter + switch on)
- copy firmware.bin (in my case 1.02 worked) into root of sd-card
- write firmware to flash
- switch of and on again 
=> X20 works again

**Comment by bsongis-frsky** [comment]
@wolverine202 which release? we are missing some information!
