### ISSUE TITLE
Log files compatibility with Google Earth

### ISSUE THREAD

**Issue by keiner0815** [FrSkyRC/ETHOS-Feedback-Community#1708]
It would be great if you could implement a conversion script in Ethos Suite to convert the GPS log files into a format compatible to Google Earth.

So that the result looks something like this:
https://www.sm-modellbau.de/media/image/product/358/lg/gps-logger-3~3.jpg

Does anybody know which format is necessary to get such a result?

**Comment by OldGazer** [comment]
That is a good idea.  I get similar functionality from ArduPilot/ArduCopter and Mission Planner.  AP logs the data, MP converts the data, and GE plots and displays the data.

Sent from Yahoo Mail on Android 
 
  On Sun, May 29, 2022 at 9:51 AM, ***@***.***> wrote:   


It would be great if you could implement a conversion script in Ethos Suite to convert the GPS log files into a format compatible to Google Earth.

So that the result looks something like this:
https://www.sm-modellbau.de/media/image/product/358/lg/gps-logger-3~3.jpg

Does anybody know which format is necessary to get such a result?

**Comment by strgaltdel** [comment]
Guess you need kml format

Never looked into the Ethos logs, if you could get a "compatible" import format out of them,
but maybe this tool will help to create a kml file:
https://www.gpsvisualizer.com/map_input?form=googleearth

regards

**Comment by mawzthefinn** [comment]
I think OpenTX companion may also do the conversion.

Would be nice to have that in ETHOS Suite as well.

**Comment by KevinFairgrieve** [comment]
Please leave open. Another in the future that would be good to add.

**Comment by j-watkiss** [comment]
I thought this today too. Well, something similar. The ability to view log file .csv displayed in a chart (similar to OTX Companion) within ethos suite. Something where you can select your variables from the list within the .csv to plot a graph so the data is more easily interpreted. (here is an example - https://www.csvplot.com/ ).
The ability to manage log files, delete or download through suite would be nice too. 

It occurs to me that many people who might want to view logs may not be easily able to deal with the .csv format. A nice viewer option in the toolbar of ethos suite would be a great addition.

**Comment by agibson2** [comment]
FYI... I created a powershell script last year to convert an Ethos logfile with GPS data to .gpx format.  There is also a command line option '-UseVarioHeight' to use the vario altitude data which is has better precision for 3d graphing.  GPS height data is inherently worse than an altimeter/vario because of the geometry of the GPS calculation.

https://www.rcgroups.com/forums/showthread.php?4140519-Script-to-convert-FrSky-logs-to-gpx-GPS-file-format#post49247111

It would indeed be awesome if FrSky had that ability built in to export as .gpx.  The ability to use vario altitude data would be really useful also if it did get that feature.

**Comment by keiner0815** [comment]
That sounds great, thatnks for the information!

I tried it, but it does not work as I am using ETHOS with german language and it seems that the logfiles use the german words, too.
So there is no "Alt" collumn for the script to find

**Comment by agibson2** [comment]
To keep my script from polluting this discussion anymore... I created an issue on the github for the script that I created.  If you can help with translation of the column names to match what FrSky uses, I will see if I can get the script to parse the german log files.  If you can include a sample German logfile too, I can experiment on that.

https://github.com/agibson2/ToolsForFrskyDevices/issues/2

**Comment by KevinFairgrieve** [comment]
> Please leave open. Another in the future that would be good to add.

Again, I for one would still like this.

**Comment by keiner0815** [comment]
Could you please implement that feature?

**Comment by KevinFairgrieve** [comment]
Again.

Please leave open and have a look to see if this is possible.

**Comment by bsongis-frsky** [comment]
The next 1.5.10 nightlies will write logfiles with only one column for GPS. They can be imported in Google Maps.
I don't know if something else is needed for Google Earth.

**Comment by bsongis-frsky** [comment]
Implemented since some time!
