### ISSUE TITLE
SXR /X20S issues

### ISSUE THREAD

**Issue by hershg21** [FrSkyRC/ETHOS-Feedback-Community#1736]
After updating SX8 to latest firmware update and X20S to 1.2.10 cannot go into self check (no blue light).

**Comment by mawzthefinn** [comment]
If this is an SR8 on 2.1.10 firmware, you need to go to Models->Device Configuration->SxR and then scroll down to the self-check line of the config section. It will be the last option with an on/off switch.

**Comment by tysonfromcanada** [comment]
On S6R accst, in the device config menu, quite a few of advanced settings appear but are grey'ed out, both in quick mode and full mode.  Angle Gain for auto level and offset for pitch auto level are two setting examples that I cannot access.  Settings are available on my QX7s using opentx and the latest lua config script for SxR.  S6R otherwise functions normally.

**Comment by tysonfromcanada** [comment]
> 

I was able to trigger self check with ch12 in the traditional way, so that has not been an issue for me as well

**Comment by hershg21** [comment]
Glad to hear it!

**Comment by tysonfromcanada** [comment]
My issue is resolved in 1.2.11 👍
