### ISSUE TITLE
Please add ability to flash IRX4 Lite Multimodule as external module 

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#1861]
Ethos 1.3.0

I had great difficulty in upgrading the IRX4 Lite Multimodule firmware (please refer to post #19448 on rcg, link below), so please add the ability to flash IRX4 Lite multimodule as an external module from the radio.

[https://www.rcgroups.com/forums/showpost.php?p=49657133&postcount=19448](url)

**Comment by lthole** [comment]
Keep alive

**Comment by arshish1612** [comment]
I second this. It extremely difficult to update the module because the pins need to be soldered every time you need to update the firmware. Unfortunately, you cannot even leave the pins soldered in place because the module is so small, that you cannot even assemble it back with the headers in place.

**Comment by mawzthefinn** [comment]
Yes, this would be an excellent addition. I bought a X9 Lite S in part to ensure I could flash Lite modules not current supported for flashing in ETHOS.

**Comment by KevinFairgrieve** [comment]
Please keep open. Something that is needed.

**Comment by arshish1612** [comment]
Pls Keep Open

**Comment by lthole** [comment]
Keep alive, it’s definitely needed.

**Comment by arshish1612** [comment]
Keep Alive Please
