### ISSUE TITLE
No stick input to plane for 3 seconds 

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#1869]
I had an issue X12S on ETHOS 1.3.0 with S6R
yesterday  was first time I flown on 1.3.0

I was flying up and down the strip about 250 meters long doing Immelmann turns at the ends and inverted flight up and down the strip.

I was lucky I was 3 mistakes High in the middle of the strip 50 meters from me it start to roll I tried to correct it I had no input to the plane 
no Rssi warning just like the radio froze for 3 sec no call outs then it came good so I landed it
went to pick the plane up i expected to here the esc beeping as it does if RX out has stopped out putting to the esc in the flight till a power cycle it will not stop

so i tested it just to check i put the tx in range mode and walked away till it went in to fail safe the esc started to beep
i walked back as it should it kept beeping till i turn off the plane

so to me it looks like the TX module and the Rx where talking to each other but TX was not talking to the module

i don't know if this was just one freaky glitch at the field or issue waiting to happen

so packed up came home

**Comment by yak-54** [comment]
well went out for a fly this mirroring after yesterdays issue

Different X12S on ETHOS 1.3.0 and Plane XR8R pro
first flight fine second one fine
next one not so good it did the same thing just paused 3 to for sec no warning at all no call outs
i did set it to call out rssi every 3 sec it did stop call out as well
then started some seconds later
the only common thing with the 2 setups is they are ACCST Receivers and 1.3.0 been working fine on 1.2.10

**Comment by Nerenye** [comment]
@bsongis you gona Close this aswell because i´m criticizing your company? #1823 for reference

**Comment by bsongis-frsky** [comment]
No this issue is not closed, despite we cannot reproduce it. 
Please stop spamming here or I will have to report abuse to github

**Comment by bsongis-frsky** [comment]
@yak-54 It seems you are able to reproduce this issue easily, right? We cannot reproduce it (neither the test team, nor Mike and e). Would you please contact me by email so that I send you a special firmware with more logging, so that we can understand what is the root cause of this issue, either the radio or the module.

**Comment by yak-54** [comment]
I had 4 flights with 1.3.3 over 4 hours first flight fine no issues
 second flight took off going to turn right nothing happens with stick input for a bout 3 sec the planes rolling left on only about 100 meters away so of lately i using my foamy to do testing easy fix if goes wrong  ( hot glue gun ) lol  till i am happy with ethos  this plane did it  last times as well with an old S6R so i fitted new archer S6R hoping it was just the old S6R issue 
nop it is not the antennas are on the out side of the so there's no issues of getting blocked 

[file (1).csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9701413/file.1.csv)

**Comment by dehigama** [comment]
I’m new to ethos but for my understanding is this issue only reproduced on a x12? And after establishing a connection with the rx?  It occurred to my x20 when connected to the ethos suite in bootloader mode, after I clicked start radio in application (macOS). The tx just froze I couldn’t boot it up with all cables disconnected. The only way I could get it up and running is after disconnecting a reconnecting the lipo. Not sure if it’s something similar. Just wanted to share.

**Comment by bsongis-frsky** [comment]
@dehigama I think this issue has only be reproduced on Horus X12S and I have been warned about the same issue on OpenTX recently, it's not at all a problem with the bootloader, but rather the RF board, or communication between the radio and the RF board.

@yak-54 would you help me on this issue like you did for the other one on X12S? The key is ... try to reproduce!

Here are some random ideas I have in mind right now:
1) try to reproduce. perhaps add a special device which beeps when channels don't move? so that you are warned and you can do something else?
2) when the receiver seems frozen, look at the radios screens to see if the Model / Outputs move. If they move, the mixer runs correctly.
3) enable the SD Logs, to see if they are normal during a freeze

**Comment by yak-54** [comment]
sorry i have not been getting email alerts from github and having to deal with flooding so its been some time from last time i checked in
will get on it as i get to the field as i said its flooded :(
