### ISSUE TITLE
Sensor Conflict Remains in 1.3.0 for SM-Unisense

### ISSUE THREAD

**Issue by m0p3d** [FrSkyRC/ETHOS-Feedback-Community#1878]
See #1827 - not gone for unisense users 

Log data , explainations etc uploaded already in #1827

**Comment by bsongis-frsky** [comment]
Unisense should be able to change the AppID

**Comment by m0p3d** [comment]
Still no clear understanding what's the trigger for playing sensor conflict.wav and what needs to be changed. Please help out with some explainations

**Comment by bsongis-frsky** [comment]
The idea is simple: 2 different sensors should have a different AppID

**Comment by m0p3d** [comment]
@bsongis-frsky The NEW FRSKY_ESC_RPM_CONS_FIRST_ID = 0x0B60  contains two 16bit blocks. Separating ID's not possible in this case. And that's the problem- please check

**Comment by michelkorthout** [comment]
@m0p3d what combination (receiver) are you using? If you are using the GR8, than with any firmware version of unisens-e you will get the sensor conflict. 
This because there is a conflict between the altitude and vspeed. Basically appid 0100 and 0110 are conflicting. 

I did not tested the unisens-e firmware version 1.20 with another receiver that is not having a vario.
Ps. Are you the developer of the unisens-e firmware?

**Comment by michelkorthout** [comment]
Hello,
I now tested the following combination: UNISENS-E FW1.20 with an RX4R using the ACCESS protocol.
I then do NOT have any Sensor Conflict messages!! 
**Conclusion**: The issue only exists in the combination with GR8 and any UNISENS-E firmware version. Because UNISENS-E Vspeed and Altitude are conflicting with the same values coming from the receiver.
not an issue that can be solved by FRSKY, but issue should be solved by UNISENS-e (Sm-Modellbau)

**Comment by m0p3d** [comment]
@michelkorthout nop I m just another user - but all my setups include unisense (because it's very versatile and helpful combination for most important telemetry applications ) and most if them using gr8 ....

Have you already informed sm Modellbau about your findings ?

**Comment by michelkorthout** [comment]
@m0p3d i mailed them last monday, but I did not get any response from then (yet).

maybe you can also contact them?

this is what I send them last week:

Hello,

Currently i am facing some issues with the following combination:
Unisens-e (fw v1.20) with Frsky Archer GR8 receiver.

When i use this combination, i get an error from Ethos that there is a sensor conflict.
First i was under the impression that the issue was at Frsky, they have some known issues with sensor conflicts..

but then i decided to find out the cause of this combination, because other combinations of Unisens-e and other FRSKY receivers did not cause this alert.

I think there are 2 potential issues:

First: The Receiver (archer GR8) has a build in vario.
seams that the unisens-e is using the same APP ID as the receiver.
below the discovered addresses. The first 2 digits are the physical ID, the last 4 digits is the Application ID.
altitude (archer)    1A 0100 
vspeed (archer)      1A 0110
altitude (unisens-e) 03 0100
vspeed (unisens-e)   03 0110

as you can see, it uses the same application ID.

Below a part out of the FRSKY Ethos manual:
Each sensor may have multiple Application IDs, one for each sensor value being sent. The Physical ID and the Application ID are independent and unrelated. For example the Variometer sensor has just one Physical ID (default 00), but two Application IDs: one for Altitude (0100) and the other for Vertical Speed (0110). Another example is the FLVSS Lipo Voltage sensor, which has a Physical ID (default 01), and an Application ID for Voltage (0300). 
If you want to use two FLVSS sensors to monitor two 6S Lipo packs, you will need to use Device Config to change the Physical ID of the second FLVSS to an empty slot (say 0F hex), and also to change the Application ID from 00 to say 01, which will make the complete Application ID (0301). Because the Physical ID and the Application ID are independent and unrelated, both must be changed. The Physical ID must be changed for exclusive communication with the host receiver, and the Application ID must be changed so the receiver can distinguish between the data from Lipo 1 and 2.
Please note that the Application ID parameter in Device Config only changes the 4th hex digit i.e. (x) above; the default is 0, but may be changed in a range of 0 to F hex (0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F) to ensure that all Application IDs are unique.

Secondly when i use firmware version v1.20 with Ethos i get an empty value:
vspeed   03 0110 
altitude    03 0100
                 03 0B60
fuel          03 0600
esc consumption 03 0B60
current    03 0200
vFAS        03 0210

Seams that the application ID 0B60 is there twices. 

Can you check those 2 issues for me?
Maybe a new parameter is required to also be able to change the applicationID.
from 0 to F (where only the last digit is changed.
like vspeed 0111 (instead of the default (0110)

When this is possible, also more then 1 unisens-e can be used on a single receiver. which is nice for planes that have 2 electic motors.

Hope this mail makes sense, and you are able to follow this up.

If i need to test something for you, let me know.

**Comment by m0p3d** [comment]
@michelkorthout Wrote him ...
But agree to your mail - makes absolutely sense.

I didn't get deep understanding because I was not able to find up-to-date telemetry protocol manual.

**Comment by m0p3d** [comment]
Fix for unisense could solve the problem - not ethos related. -> Closed wait for unisense FW release

**Comment by michelkorthout** [comment]
I guess it will not take long before a new version will be released, I already received a test version. In this test version the appid can be changed, after changing the sensorconflict messages are gone

**Comment by michelkorthout** [comment]
@bsongis-frsky I just tested the new firmware for Unisens-e on my system. I tested this using X20S with the latest Ethos version and i tested to same on a X-LITE pro.

The sensor conflicts messages are gone, but still an empty slot.
![image](https://user-images.githubusercontent.com/52248764/188494478-4ca60c16-f12e-4107-ae8b-bc7169e087a4.png)

But when i pair the receiver to my XLITE PRO, i do not get an empty slot!
here i get ERPM as the name.

When i look at the details of this empty slot, i see it shows as RPM related stuff.
![1](https://user-images.githubusercontent.com/52248764/188495206-de1095fb-d46f-4bff-8b74-7c15f53bc882.jpg)
![2](https://user-images.githubusercontent.com/52248764/188495215-4aa0e680-79e1-465d-a164-26567bc09893.jpg)
