### ISSUE TITLE
Ail trim does not respect differential set in Ail => Flaps mix

### ISSUE THREAD

**Issue by stefanfluck** [FrSkyRC/ETHOS-Feedback-Community#1918]
Ethos 1.3.0

When setting up a glider with 2 Ail and 2 Flaps, I have the flaps move with ailerons when giving Aileron input by using the Ail => Flaps mix. In the Ail => Flaps mix, one can give Differential, which is essential as the flap servo horns are offset to allow for more down travel than up. When applying full Aileron input, the behavior is as expected (that is, flap moves a fraction of ailerons).

Issue: When applying full aileron trim with trim switch T1 now, the flap travels way more down than the other flap up.
Potential cause: It seems that the differential as specified in the Ail => Flaps mix is not respected during trim.

Idea: Furthermore, it'd be worth a thought to give the user the option to select if flaps should move too under aileron trim if a Ail => Flaps mix is set.

**Comment by mawzthefinn** [comment]
After testing, the issue is not with the ail->flaps mix.

The trim system is not respecting differential settings in the mixer.

As a test, I applied 50% differential first to the aileron->flaps mix and added 1uS of trim. The full trim value was applied in the correct direction to each flap channel as well as to the aileron channels

I then applied 50% differential to the ailerons mixer and observed identical behaviour as before the differential was applied. The trim is not respecting differential on the aileron mixer either.

**Comment by stefanfluck** [comment]
Thanks for the reply!
Correct me if I'm wrong, but differentials represent factors on an input, so I do not see how these would at some point become unpredictable. Also, as it currently is (see my description above), it might be consistent and predictable, but it's just wrong and impractical. 
As a consequence, a function is needed so Ail trim only goes to the aileron output channels, but not the flaps. I'd rather have the flaps stay where they are while trimming with the Ails compared to have them move disproportionate amout of travel down.

**Comment by mawzthefinn** [comment]
Differential can be live adjusted, as can rates, by using a VAR mix or other Source as an input.. If Trim respected them your trim could change in flight due to you adjusting other items. That's potentially dangerous. As it is, trims do not change unless you adjust the Outputs page or the trim itself.

I agree that the Ail->Flap mix needs an 'Ignore trims' option. In fact all the mixes should have that option.

**Comment by mawzthefinn** [comment]
This behaviour will be left as-is for now. It is the most common behaviour on other OS's as well.

Documentation will be added to the manual to clarify the behaviour.
