### ISSUE TITLE
Feature Request- Separate weights and expo for left and right of control surface. 

### ISSUE THREAD

**Issue by bubbagumprc** [FrSkyRC/ETHOS-Feedback-Community#1931]
Like to have separate left and right, or up and down weights and expos in the mixer page with out doing a special mix or messing with the differential  function which just takes away throw from one side and adds more to the other side.  Very useful for competition flying including F3A flying and is in all the high end radios and even on the spektrum radios.

**Comment by mawzthefinn** [comment]
You can easily do this today. 

Multiple Weights and Expo's are available today, with the addition of a simple Logical Switch to select which one is active at a given time (use an A > X logic switch with the A value as your Analog and an X value of 0). That logic switch is active on one side and the default is active on the other side. 

It's also wildly more powerful than the Spektrum setup as you are not limited to '0' as the transition point.

**Comment by bubbagumprc** [comment]
I already do this to have true aileron differential to adjust both left and right rolls, but this is a work around for something simple that should be in the mixer page built in.  When you have 6 different weights and expos in the mixer page do to having 2 snap conditions which is on logic switching, spin condition. Also having 3 different rudder rates that is independent of those three conditions and normal condition. Having 20 something logic switches for this task is not fun and over complicated.

**Comment by mawzthefinn** [comment]
I'd be interested in seeing the model file in question. 

When you're getting that complex, Flight Modes and VAR mixes become much easier ways to manage this stuff, especially compared to old-fashioned OS's like Spektrum. 

6 different rates is pretty standard stuff for F3J programming where I run 6 flight modes, each with different rates, expo, and differential and use of one or more VAR mixes makes that much easier to manage, without overcomplicating the base mixer setup.

Note the basic paradigm for the mixers in ETHOS are 'do one thing, well' and to chain mixers and logic switches when complex solutions are needed, rather than the 'everything in one mixer screen' approach that other OS's use.
