### ISSUE TITLE
X20 logic based volume control 

### ISSUE THREAD

**Issue by dehigama** [FrSkyRC/ETHOS-Feedback-Community#1938]
Would like to know if there is a way to start the radio with a low volume and increase it via a logic switch. I’m only able to set it to mute and max via a logic switch. The reason behind is to only set a high volume during a flight. Was able to accomplish this on openTX. Thanks 

1.3.3 EU

**Comment by mawzthefinn** [comment]
You certainly can do so, but it's a little different from OTX.

You can Use a Source to control volume. Thus you can use anything that can control a channel to control volume, but you do it with a Mixer instead of a Logic Switch (you can have the Logic Switch controlling the mixer). 

I would suggest picking a consistent channel for this, because the volume control is a system-level setting. I'd use a mid-channel for this (like Ch33), because I do all my fancy mixing on high channels (working down from 64).

**Comment by dehigama** [comment]
Thanks @mawzthefinn works a treat!

For anyone interested in @mawzthefinn's solution, here it is.

1. Create a logic switch: **Function A>X**  where the **Source(A)** is **Throttle** and **X** is **-50** (Or any trigger value you prefer)
2. Create a new mix: **Input** should be the logic switch name created above. create a new curve setting the min and max volume you prefer to have. **Output** set to Channel 64 (an unused channel).
3. Navigate to **System->General->Audio** and long press on volume, select **Use a source** select option **Channels** and assign the channel you created on step 2 which in my case was 64.
Done!

**Comment by mawzthefinn** [comment]
I’d actually do it a touch differently for step 2, although your solution works well.

For #2 I’d use a VAR mix instead of a Free Mix, with the default value as the desired min volume and add a second weight triggered by the LSW with a value of the desired max volume.

By using a VAR mix, you can actually add an additional weight that’s ‘Use a Source’ and can be set to an analog volume control, getting the best of both worlds, analog control when you want it and the two values when you don’t (plus this use of an Analog can be used to tweak settings, adjust in flight to the desired value, go back to the VAR mix, long press the value window with the Analog and choose ‘Convert to  Value’

**Comment by dehigama** [comment]
@mawzthefinn thanks for sharing, that's a much better way with more options. brilliant!
