### ISSUE TITLE
Possibility to have openTX style page option for logic switches

### ISSUE THREAD

**Issue by dehigama** [FrSkyRC/ETHOS-Feedback-Community#1940]
Moving from openTX would be great if we can choose between the ethos way and the openTX way of program logic switches. Would be super nice. 

1.3.3 EU

**Comment by bsongis-frsky** [comment]
Please explain what you need!

**Comment by dehigama** [comment]
I was thinking of the openTx pilots moving to ETHOS and who are making use of fancy logic switches on OTX, some method to import, or to have an optional openTx style logic switches page. would be super nice and helpful to transition into ETHOS while ramping up knowledge on the new way of programming.

**Comment by Nerenye** [comment]
What do you mean by opentx style? Can you mark out what changes you want or how it should look like? 

PC companion would be really helpful I think. Programming lots of logic switches is kind of a nightmare. The ability to copy them on pc from model to model would be nice. (duplicating them on the remote itself takes way too Long because model switching takes ages)

**Comment by dehigama** [comment]
Indeed, a companion would be helpful, I was an opentx user till I got my hands on an x20 running on ethos, so I wished I had a way to copy all my logic I had configured in otx line by line into ethos.  I don't have a tx running on otx anymore so unfortunately cannot share what it looked like. 

I was thinking under the same logic switch page on ethos if we can have an option to render it as in otx, call it like "advanced mode" or "legacy mode" :).

 but must say that working with ethos the past days helped me get past some startup obstacles. This is just for someone new to ethos coming from an otx background enabling them to reconstruct their existing logic at a fast pace and go flying.

**Comment by mawzthefinn** [comment]
I'm kind of mystified as to the desired change, the layout of the options on the LSW edit page is pretty close to what was there in OpenTX, but it follows regular ETHOS navigation rather than the poorly designed UI in OpenTX (at least on colour screen radios, the UI made sense for the limited screen real estate of the B&W radios).

You can pretty much copy any displayed OpenTX Logic Switch directly to an ETHOS one.

**Comment by mawzthefinn** [comment]
The best is probably the X20 thread in the Radios section on RCGroups. Mr D Falling With Style has some great videos as well and Mike's ETHOS Hanger on RC-Soar.com is another great resource.
