### ISSUE TITLE
New to Ethos

### ISSUE THREAD

**Issue by davidholland315** [FrSkyRC/ETHOS-Feedback-Community#1944]
I have just treated myself to an X20 after using a Horus X10 on FrOs.  I am trying to set up an autogyro and need to mix aileron and elevator functions. The head uses two servos which need to operate simultaneously to articulate the head but I cannot get a mix working. Any ideas, thanks.

**Comment by mawzthefinn** [comment]
You should be able to achieve this with the Heli setup and CCPM mixing, just with your pitch permanent fixed (since you have no pitch channel anyways). You would need to know the angle between the two servos to pick the CCPM setup. 

Alternatively set  the aileron and elevator mix outputs to target higher channels (say ch64 for Aileron and Ch63 for Elevator) instead of ch1 and 2, and then add 4 free mixers setup the following way (assuming AETR at the receiver)

Mixer 1: Name: Ele1, Source Ch63, Output Ch1
Mixer 2: Name: Ele2, Source Ch63, Output Ch2
Mixer 3: Name: Ail1, Source Ch64, Output Ch1
Mixer4: Name: Ail2, Source Ch64, Output Ch2

Then you can adjust the weights of each of  these channels to get the mixing you want.

**Comment by davidholland315** [comment]
I'm really struggling with this X20, I'm trying to update to the latest version of Ethos which I have downloaded but I cannot get either my iMac, Window10 PC or Windows11 laptop to recognise the Tx when connected by USB. I am in Bootloader mode and the Tx screen says "USB Plugged". Help, what am I doing wrong!!!!

**Comment by mawzthefinn** [comment]
First try a different cable, I've had poor luck with the included cables and use a high-quality USB-A to USB-C data cable (that I got with an older high-end phone).

If you are struggling with USB connectivity, remember you can always update using the MicroSD card directly using a MicroSD reader, copying the firmware files to the root of the SD card, then booting into the Bootloader.
