### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Fpilih** [FrSkyRC/ETHOS-Feedback-Community#1948]
I have not updated my X20S from 1.2.10 because I have little faith in the last few updates.  How is a person to know if there are "new" "bugs" introduced in the latest release? The last rev level caused the transmitter to announce "sensor conflict" when there was none. This alarm was persistent enough for me to roll back to the previous release.

**Comment by mgsanna** [comment]
It is an Issue? this repo is made for issue, not complain.... about new release....
Find in rc world a company that has this kind of support and fast solving issue, I say issue not bug ....because Bug are so few.. even after 1500 and more "issue/bug/enhancement" solved in time and so near to user community....

**Comment by MIKE-DAILEY** [comment]
> I have not updated my X20S from 1.2.10 because I have little faith in the last few updates. How is a person to know if there are "new" "bugs" introduced in the latest release? The last rev level caused the transmitter to announce "sensor conflict" when there was none. This alarm was persistent enough for me to roll back to the previous release.

I don't know of any bugs that impact aircraft flight, but you might consider checking in to forums like RC Groups that discuss ETHOS.  Here is the link to a thread https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-X20S-X20HD-Tandem-24-Channels-with-ETHOS
