### ISSUE TITLE
Product and protocols

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#1984]
In the RF configuration the product "TwinLite Pro" can be selected and the protocol "ELRS". But there is no protocol "ELRS" but ELRS is a product and uses the protocol CRSF.

Similar confusion is in the main.lua for ELRS module. system.registerElrsProtocol() is illogical because it is not a protocol. system.registerElrsModule() would be a better name.

crossfire.pushFrame() is also such an example. Here a protocol is addressed, but Crossfire is a product and not a protocol. The protocol is CRSF. Ergo crsf.pushFrame() would be correct.

Probably some modules will be added in the course of time and it would be better to correct that now instead of having problems later.

**Comment by bsongis-frsky** [comment]
1) TwinLite Pro doesn't use the CRSF protocol

2) agreed, I will change to `system.registerElrsModule()` in 1.4.1

3) agreed, I will change the lib name to "crsf" in 1.4.1

**Comment by Target0815** [comment]
Thank you!

I didn't have the right idea for the TwinLite Pro either, but the "ELRS" protocol isn't right either. How about an additional product entry "TwinLite Pro ELRS" with the protocol "CRSF"?

**Comment by bsongis-frsky** [comment]
This "ELRS" means that you set the TwinLite Pro in a configuration which is compatible with any ELRS receiver

**Comment by mawzthefinn** [comment]
There are two paths to using an ELRS 2.4G receiver with ETHOS.

1. Use an ELRS 2.4G Module

2. Use a TWIN compatible radio or module (TWIN X-Lite or TWIN Lite Pro right now) running with the ELRS protocol selected instead of one of the other 3 protocols supported by TWIN radios and modules (ACCST D16, ACCESS 2.4G and TW are also supported)

So having ELRS is correct in the TWIN Lite Pro protocol menu, but ELRS is another module option as well.
