### ISSUE TITLE
Calculated Sensors: Option missing to calculate with constant values.

### ISSUE THREAD

**Issue by BernhardFe** [FrSkyRC/ETHOS-Feedback-Community#2063]
When I want to show the calculated voltage cell (Voltages mul. x%) I need to adjust the ESC Voltage. This is working.
Calculating now the power consumption with a new calculated sensor shows not the over all power in W. It is also divided by factor in the ESC sensor.
The solution would be to leave the ESC Voltage source as is and create a calculated sensor (ESC Volt mul. x%) and have then a second separated calculated sensor for the power.
But I found no option in the calculated sensor to put a fixed value in the calculation.
If not, Is ist possible to add fixed values to the programming of the calculated sensor (+-*/)? This fixed values might be values in %.
A work around with defining a VAR mixer and an output to reuse the value in the calculated sensor is not working either.
Is there any option to make this happen?

**Comment by BernhardFe** [comment]
We should not forget this and not close it. 😊

**Comment by ealdaz-seesai** [comment]
This seems a very useful and basic capability, surprised it's not added.
I wanted to scale a telemetry reading to create a calculated sensor and I can't divide by a constant value..

**Comment by bsongis-frsky** [comment]
I am not sure I fully understand what you need, but you can do any calculation with sensors:
![image](https://user-images.githubusercontent.com/50834778/227351492-874e334b-1989-4eb6-b4be-dd49a6b3ed35.png)

**Comment by mawzthefinn** [comment]
Yes, looks good to close as you can do arbitrary math with the Custom formula

**Comment by ealdaz-seesai** [comment]
Hi guys, thanks for taking a look.
The issue is not so much on wether the Custom formula has math operators or not, addition, subtraction, division, multiplication are all there, no issues with that.
You can even use all sort of data types as source, Telemetry, Channels, Timers... however the one that is missing (or I haven't been able to find) is a constant value source.

For example if I wanted to subtract a number (say 10) from a telemetry channel there is no way to do that that I can see.

I'm using version 1.4.6 in case that helps.

**Comment by mawzthefinn** [comment]
Take a closer look at Bertrands's screen shot. 

You can set constant values for all lines in the Source selection by long-pressing the value selector box and choosing 'Convert to Value.

**Comment by ealdaz-seesai** [comment]
Very helpful, I would have never thought about doing a long press, I was convinced it would have appeared as another type of source.
Thanks!
