### ISSUE TITLE
Run own LUA Scripts

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#2072]
Hello everyone, there is no error message now.  But how can I add and run LUA scripts under Ethos?  They do not appear in the selection list under Scripts.
Horus X10s with ISRM; Ethos 1.4.3

**Comment by strgaltdel** [comment]
your description isn't very precise !


a) System scripts appears in the 2nd page of  the system section
b) widget scripts are listed in the config page of a widget screen
c) source scripts are configured / listed in the model section/model config

every script should have its own subfolder in the /scripts folder

**Comment by Skippydi** [comment]
Hi strgaltdel, thanks for quick answer. But were i find the 2nd Page of system section, or the config Page of widget screen and so on?
My own script is in subfolder /scripts/...
This picture shows the filestructure of Horus X10s
![bild](https://user-images.githubusercontent.com/68751162/201375376-cb653da6-e961-4703-9e1f-9198a5b2645f.jpg)

**Comment by strgaltdel** [comment]
But were i find the 2nd Page of system section,..

These are Basics, (press sys button to enter System options, press page to enter 2nd Page)
I'm pretty sure this  contribution will be closed soon because  it s no Ethos Bug.

Either the script has bugs and doesn't start
(did you crosscheck in debug Mode of sim) 
Or you dont know how to Register the script...

Would propose  to discuss it in EngelMT forum,
I see your TX is ger localized 

Regards

**Comment by Skippydi** [comment]
Ok, it works. Thanks
