### ISSUE TITLE
ELRS on Twin Lite Pro: Bind not working

### ISSUE THREAD

**Issue by notonamap** [FrSkyRC/ETHOS-Feedback-Community#2082]
Hey there,

I'm having issues trying to bind the Twin Lite Pro to a Skystars ELRS receiver. Receiver is clearly in bind mode but whenever I hit Bind on the TX the "Waiting for receiver" popup just disappears after a few seconds with no link established. Any way to get to the bottom of this?

Running a X20
Ethos 1.4.2
Twin Lite Pro 1.0.1 EU-LBT

This is how I flashed the receiver:
![rx-elrs](https://user-images.githubusercontent.com/8919922/201677224-40fe3682-0978-4918-bd46-95ce33e9162c.png)

**Comment by mawzthefinn** [comment]
Yes, the TWIN ELRS compatibility currently targets ELRS 2.3 according to the information I've received.

**Comment by notonamap** [comment]
Thanks a lot! Frankly I'm a bit lost to what extend Ethos already supports ELRS, specifically 3.0. If I had a TX module that supports ELRS 3.0 would I be able to hook up to it via the ELRS Lua script?

**Comment by mawzthefinn** [comment]
Yes, you would be able to do so.

I have tested the HappyModel ES24TX Slim Pro personally on my X18 and X20, with firmware 3.0.0  with success.

Do be aware that right now the Betaflight SPI installation wants a v2.x firmware compatibility target, so if you are using a Whoop that can be an issue If you have an ELRS module on 3.0.0

Also note that while I am a Contributor here, I do not work for FrSky (I’m a beta tester who helps with community engagement) so my comment above for the HappyModel ELRS module is personal experience, not an official FrSky recommendation. I understand the Vantac modules also work well but have not tested that myself. Avoid the Jumper modules, they are known to have fit issues on the X20 due to out of spec case designs.

**Comment by notonamap** [comment]
Just tested a BetaFPV 2.4 TX with ELRS 3 flashed and it worked out of the box. Thanks again for your help! I was already afraid that I had to get a new radio 😅
