### ISSUE TITLE
no offset in ele,ail,rud mixes

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2088]
no offset in ele,ail,rud mixes.  if one uses the center/subtrim in the output function one doesn't get symmetrical movement in the channel. only way i could do it was to use a free-mix combined with a trim, or ele.ail,rud mix combined with offset mix. both seem overly complicated. the center/subtrim does something kind of odd.

**Comment by mawzthefinn** [comment]
PPM center will shift endpoints as well as center, subtrim trims the center only but does not affect endpoints. The reason for both is that subtrim should be used once endpoints are set to limit physical travel while PPM Center sets the initial ranges.

The Offset mix is the intended solution, and it is done this way because in complex mixing scenarios you want 1 offset per channel, not 1 offset per mix, otherwise multiple mixers fight (such as in a delta situation where the Aileron and Elevator mixers are targeting the same 2 channels)

**Comment by williajgr** [comment]
So for every channel I want an offsets I have to have 2 mixes?  Generally after I get a plane trimmed out I set offsets so I can center the trims.  So I have to have 2 mixes for every flying channel, that is a lot of work.  Make the center/sub trim do what it should do and you would have just one offset per channel and not an infinite number of mixes.Sent from my iPhoneOn Nov 17, 2022, at 9:12 PM, mawzthefinn ***@***.***> wrote:﻿
PPM center will shift endpoints as well as center, subtrim trims the center only but does not affect endpoints. The reason for both is that subtrim should be used once endpoints are set to limit physical travel while PPM Center sets the initial ranges.
The Offset mix is the intended solution, and it is done this way because in complex mixing scenarios you want 1 offset per channel, not 1 offset per mix, otherwise multiple mixers fight (such as in a delta situation where the Aileron and Elevator mixers are targeting the same 2 channels)

**Comment by mawzthefinn** [comment]
Subtrim already works correctly. Use that for centering trims. 

If you are shifting the whole channel range (ie you want the endpoints to be adjusted so you have consistent throw ranges in each direction) use PPM center to do  that.

The logic here is to use PPM center when you want the whole range shifted and to use Subtrim when you want to shift the trim center without affecting your endpoints (because you use min/max endpoint settings to prevent driving a servo past its physical limits).

You should never be setting the trim center in a mixer, in ETHOS or OpenTX.

**Comment by williajgr** [comment]
The trouble with ppm is that you have no idea where you are.  So if I have to trim 8% I have no idea where to set the ppm.  I am using it now to copy models over from open-tx.Sent from my iPhoneOn Nov 18, 2022, at 8:15 AM, mawzthefinn ***@***.***> wrote:﻿
Subtrim already works correctly. Use that for centering trims.
If you are shifting the whole channel range (ie you want the endpoints to be adjusted so you have consistent throw ranges in each direction) use PPM center to do  that.
The logic here is to use PPM center when you want the whole range shifted and to use Subtrim when you want to shift the trim center without affecting your endpoints (because you use min/max endpoint settings to prevent driving a servo past its physical limits).
You should never be setting the trim center in a mixer, in ETHOS or OpenTX.

**Comment by williajgr** [comment]
Actually from my experience center/subtrim does change the endpoints.   Weight x subtrim value Sent from my iPhoneOn Nov 18, 2022, at 9:15 AM, George Williams ***@***.***> wrote:﻿The trouble with ppm is that you have no idea where you are.  So if I have to trim 8% I have no idea where to set the ppm.  I am using it now to copy models over from open-tx.Sent from my iPhoneOn Nov 18, 2022, at 8:15 AM, mawzthefinn ***@***.***> wrote:﻿
Subtrim already works correctly. Use that for centering trims.
If you are shifting the whole channel range (ie you want the endpoints to be adjusted so you have consistent throw ranges in each direction) use PPM center to do  that.
The logic here is to use PPM center when you want the whole range shifted and to use Subtrim when you want to shift the trim center without affecting your endpoints (because you use min/max endpoint settings to prevent driving a servo past its physical limits).
You should never be setting the trim center in a mixer, in ETHOS or OpenTX.

**Comment by williajgr** [comment]
You better check your facts as the endpoints do change with subtrim.  At least on my radio.Sent from my iPhoneOn Nov 18, 2022, at 10:01 AM, mawzthefinn ***@***.***> wrote:﻿
Center/Subtrim does not change endpoints on ETHOS, this is a deliberate choice for the reason I explained above. OpenTX and ETHOS do not necessarily treat things the same way.
If copying from OpenTX, in OpenTX your outputs display should be showing uS value as well as percentage. On the B&W radios that is shown at the top of the screen for the currently selected channel and can simply be copied to the PPM Center value if the channel is entered when you read the value.

**Comment by mawzthefinn** [comment]
I just tested on my X20, running ETHOS 1.4.3 FCC. Endpoints at -100.0% minimum and 100.0% maximum

Elevator channel, 992 minimum, 1500 center, 2009 max with 0 subtrim, ppm center at 1500uS (default). I see +/-1uS of drift on the end points with my stick calibration (the radio needs a calibration)

dial in 10% subtrim, the center moves to 1551uS, 993 minimum, 2008 maximum. The very slight endpoint difference I see are the drift due to my stick calibration being a little off

If I set PPM center to 1551 (to match 10% subtrim setting), my endpoints become 1044uS minimum, 2059uS maximum, as expected.

**Comment by williajgr** [comment]
Ok I setup ail mix weight of 50.  Go to output for that channel put in 10%subtrim.  Now output goes from +55 to -45. I don’t understand that logic.Sent from my iPhoneOn Nov 18, 2022, at 1:45 PM, mawzthefinn ***@***.***> wrote:﻿
I just tested on my X20, running ETHOS 1.4.3 FCC. Endpoints at -100.0% minimum and 100.0% maximum
Elevator channel, 992 minimum, 1500 center, 2009 max with 0 subtrim, ppm center at 1500uS (default). I see +/-1uS of drift on the end points with my stick calibration (the radio needs a calibration)
dial in 10% subtrim, the center moves to 1551uS, 993 minimum, 2008 maximum. The very slight endpoint difference I see are the drift due to my stick calibration being a little off
If I set PPM center to 1551 (to match 10% subtrim setting), my endpoints become 1044uS minimum, 2059uS maximum, as expected.

**Comment by mawzthefinn** [comment]
OK, you're not coming close to hitting the endpoints of the output channel, which is why you are not seeing what I'm describing. 

The absolute endpoint of the channel is not shifting, the scaling between that and centre is as you shift the centre. This occurs because those endpoints are defined as -100%/100% value from the combined mixer outputs for the channel and the subtrim position is 0 from the mixer position.

Subtrim doesn't shift the channel endpoint. It moves the centre point and the mixer->channel output is then scaled over the range from channel '0' to channel '-100' or '100', which gives the results you describe.

**Comment by williajgr** [comment]
I knew what it was doing just couldn’t figure out what good that function is.  What good is scaling the output by the subtrim. Makes no sense to me. Just let subtrim be subtrim.Sent from my iPhoneOn Nov 18, 2022, at 2:20 PM, mawzthefinn ***@***.***> wrote:﻿
OK, you're not coming close to hitting the endpoints of the output channel, which is why you are not seeing what I'm describing.
The absolute endpoint of the channel is not shifting, the scaling between that and centre is as you shift the centre. This occurs because those endpoints are defined as -100%/100% value from the combined mixer outputs for the channel and the subtrim position is 0 from the mixer position.
Subtrim doesn't shift the channel endpoint. It moves the centre point and the mixer->channel output is then scaled over the range from channel '0' to channel '-100' or '100', which gives the results you describe.

**Comment by mawzthefinn** [comment]
The scaling is necessary, because the endpoints are used to limit servo throw to prevent exceeding physical limitations. Endpoints set the 100%/-100% positions, subtrim sets the 0 point, the values range in according to the scaling, so you do not need to tweak mixers to limit max throws, only lower rates. 50% mixer output is always 50% of the way between 0 and 100%.

If it behaved as you describe, you could potentially drive servos past the physical limits of the surface. Using endpoints in Outputs to prevent exceeding physical limits is standard procedure when setting up sailplanes and many other cases (gear doors for example) where you need a hard limit for the servo range.

The need to shift the whole range around center as you are trying to do is why PPM Center also exists. It's in PPM because the usual issue that drives its use is adjusting for old standard (1520uS) or non-standard PPM centers for FC's, FBL's or old servo installs .

**Comment by williajgr** [comment]
Well thanks for explaining your logic.  Never used endpoints to keep servos from binding up, only to set the desired throws to a channel. In the old days that is all one had.  I use offset to recenter the trims after the plane is trimmed out.  Endpoints is just another way of setting the throws, or a way to set up differential actually easier than using differential.  You just have a different religion than I do, and most of the open-Rc people.  You are just too hung up on the endpoints, and can only see things your way.  Open your horizons every one using open-tx isn’t stupid.  I happened to make large sums of money developing main frame computers for IBM.Sent from my iPhoneOn Nov 18, 2022, at 3:37 PM, mawzthefinn ***@***.***> wrote:﻿
The scaling is necessary, because the endpoints are used to limit servo throw to prevent exceeding physical limitations. Endpoints set the 100%/-100% positions, subtrim sets the 0 point, the values range in according to the scaling, so you do not need to tweak mixers to limit max throws, only lower rates. 50% mixer output is always 50% of the way between 0 and 100%.
If it behaved as you describe, you could potentially drive servos past the physical limits of the surface. Using endpoints in Outputs to prevent exceeding physical limits is standard procedure when setting up sailplanes and many other cases (gear doors for example) where you need a hard limit for the servo range.
The need to shift the whole range around center as you are trying to do is why PPM Center also exists. It's in PPM because the usual issue that drives its use is adjusting for old standard (1520uS) or non-standard PPM centers for FC's, FBL's or old servo installs .

**Comment by mawzthefinn** [comment]
The procedures I'm recommending actually come from the OpenTX community, especially the sailplane community running OpenTX. I am certainly not dismissing the OpenTX community, but rather noting that ETHOS is not OpenTX and some functionality in ETHOS is different from OpenTX by deliberate design. I am personally an OpenTX user as well as an ETHOS user. 

The implementation of Offset in a separate mix is one such case and was developed in part based on the inputs from OpenTX users, including one of the noted experts on advanced mixing in OpenTX, Mike Shellim of RC-Soar.com fame. The discussion is covered in part in #138 

Not every setup will have to worry about mechanical limits, if the servos can't overdrive the surface any discussion of the need to set endpoints academic for that application. The design of Subtrim and Maximum/Minimum in the Outputs page behaves as it does because of the need for some setups to prevent overdriving of surfaces, PPM Center exists because not every user has that need. Both subtrim behaviours available in OpenTX exist in ETHOS, but are not implemented identically to OpenTX.

PPM Center in ETHOS is the equivalent to Symmetrical subtrim in OpenTX. Center/Subtrim is equivalent to Center Only Subtrim in OpenTX. 

The same goes with the recommendation to use subtrim to recenter the trims after trimming rather than offset. OpenTX actually has a function specifically for that, allowing trims or stick positions to be saved directly to subtrim in the Outputs page (which I would like to see come to ETHOS in the future)

**Comment by williajgr** [comment]
Just like the open-tx mix so much better than ethos.  Offset, trim, delay.  One stop shopping.Sent from my iPhoneOn Nov 18, 2022, at 8:08 PM, mawzthefinn ***@***.***> wrote:﻿
The procedures I'm recommending actually come from the OpenTX community, especially the sailplane community running OpenTX. I am certainly not dismissing the OpenTX community, but rather noting that ETHOS is not OpenTX and some functionality in ETHOS is different from OpenTX by deliberate design. I am personally an OpenTX user as well as an ETHOS user.
The implementation of Offset in a separate mix is one such case and was developed in part based on the inputs from OpenTX users, including one of the noted experts on advanced mixing in OpenTX, Mike Shellim of RC-Soar.com fame. The discussion is covered in part in #138
Not every setup will have to worry about mechanical limits, if the servos can't overdrive the surface any discussion of the need to set endpoints academic for that application. The design of Subtrim and Maximum/Minimum in the Outputs page behaves as it does because of the need for some setups to prevent overdriving of surfaces, PPM Center exists because not every user has that need. Both subtrim behaviours available in OpenTX exist in ETHOS, but are not implemented identically to OpenTX.
PPM Center in ETHOS is the equivalent to Symmetrical subtrim in OpenTX. Center/Subtrim is equivalent to Center Only Subtrim in OpenTX.
The same goes with the recommendation to use subtrim to recenter the trims after trimming rather than offset. OpenTX actually has a function specifically for that, allowing trims or stick positions to be saved directly to subtrim in the Outputs page (which I would like to see come to ETHOS in the future)
