### ISSUE TITLE
SxR device configuration utility not working correctly with 2 ACCST S8R 

### ISSUE THREAD

**Issue by jlk69** [FrSkyRC/ETHOS-Feedback-Community#2090]
Ethos  version 1.4.2.0. Tx is X-18. Internal module HW: 1.01 FW: 2.2.2 (FCC) Rx is S8R ACCST 2.1.2 (FCC)https://youtu.be/LKtJUgLTd6E[](url)  

I even tried re-calibrating the Rx, but no change. This is happening with two different S8R Rx's.

**Comment by jlk69** [comment]
Both of these S8R worked correctly with a Taranis 2019 SE

FW: opentx-x9d+2019

VERS: 2.3.14

**Comment by drummaker** [comment]
This broke when thew added the ability to initialize the access stabilized receivers within the script.   This was access only, and I suspect firmware upgrades for the accst sxr receivers came to an end.  I suspect this could be fixed by having 2 different scripts.  That said, frsky has never been too quick to work on stabilizing receiver issues.  I currently config my sxr stuff from an opentx radio

**Comment by jlk69** [comment]
If I configure my SxR Rx's on an Opentx radio is it safe to use my X-18 to bind and fly my SxR Rx's? 
Does Self-Check work with Ethos?
