### ISSUE TITLE
Emergency message using nano tx crsf module

### ISSUE THREAD

**Issue by Holypug** [FrSkyRC/ETHOS-Feedback-Community#2190]
Hi everyone. I am new in fpv  and i own a new x18s . Everything is updated to latest and is ok. I try to copy the lua script to the sd card but is not working. Only if i copy on the internal memory of the radio it display the external module option. I bind a quad, and few seconds later the radio went to emergency mode and no shut down pressing the power button. What i am doing wrong? Thanks for help

**Comment by Holypug** [comment]
It work only if scripts folder is in Nand drive. Sd card won't work even if selected as lrimary source for folders.

**Comment by Target0815** [comment]
You should leave the scripts folder on the NAND drive. This is provided for the X18S.

Then create a folder "crossfire" below "scripts" and copy the main.lua into it. Then restart the transmitter so that the script is loaded.

I also use the Crossfire Nano TX with the X18S mit Ethos 1.4.4. Which Ethos version do you have installed?

P.S. there is no "crsf module", but a Crossfire module which uses the CRSF protocol.

**Comment by Holypug** [comment]
Thanks. In fact it work only on the NAND drive. Look like the sd card is a " problem " on my radio. It is also slow to show on pc. Something strange about sd functionality. Even if i select ghe sd card as primary golder on the segting option won't work.

**Comment by Holypug** [comment]
Ethos 1.4.4 latest version. Everything is updated
