### ISSUE TITLE
Support for NMEA Dataset thru Bluetooth

### ISSUE THREAD

**Issue by krokusvej** [FrSkyRC/ETHOS-Feedback-Community#2191]
Sorry just have seen your message regarding #713, I havn´t got it working with ether Skynavigator or Albatross are there any one else there have got this working? 
Do anyone know if there are any LUA scripts supporting translation of the telemetri data sets? I have been told that Skynavigator supports NMEA protocal as standard I have also resieved this document explaining the data set could we get this as a lua script?
[SkyNavigator Protokol.pdf](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10200731/SkyNavigator.Protokol.pdf)
[https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/713])

**Comment by mawzthefinn** [comment]
No, a Lua script won’t give you that, because the radio will still be sending S.Port formatted data, A Lua script at most would embed NMEA inside S.port.

SkyNavigator or Albatross’s developers should contact FrSky to get access to the S.Port documentation. Other applications in this space have done so and support the data, like iMSB.

**Comment by krokusvej** [comment]
Hi I have talked to Albatros and they would like to know haw to get in contact thru the right channel could you share this info with me I have given them the link to this forum. Is there a nother way to make this contact?

**Comment by mawzthefinn** [comment]
https://www.frsky-rc.com/register-for-firmware/ is where developers can sign up for access to documentation including S.Port docs

**Comment by Dsrenger** [comment]
That would be the best news of the year if rc electronics would support Frsky. *Dream*
