### ISSUE TITLE
[REQUEST] Fade in/out for switch and logic switch

### ISSUE THREAD

**Issue by mikeschuster** [FrSkyRC/ETHOS-Feedback-Community#2246]
Fade in/out is available for flight modes, which is helpful for mixer 'Active condition' when activation or deactivation could cause a relative large surface deflection.

However, if mixer Active condition is a switch or a logic switch, I see no option to set fade in/out.

A competitor radio I own supports this option, it would be nice to have in Ethos.

**Comment by mawzthefinn** [comment]
Switch and logic switch positions are true/not true, so inherently cannot be faded 

That said, a mixer should potentially be fadeable like a flight mode (which doesn't fade the state, merely the transition of flight-mode specific values)

You can simulate this today however by using a mixer and curve so that the mixer is '0' when the non-active condition is true and whatever value you want when the active condition is true, then using slow to achieve the fade. A Var mix may be necessary to condition the input to be a source instead of an active condition.

**Comment by mikeschuster** [comment]
Thank you for your suggestion. FYI: a free mix with switch input, slow and curve so output changes between 0% and 100% slowly. Multiplying this result with my original mix gives what I want.
