### ISSUE TITLE
Ethos suite (latest) breaking x20 usb connection

### ISSUE THREAD

**Issue by Highlanderjc** [FrSkyRC/ETHOS-Feedback-Community#2262]
I can plug the radio into computer in bootloader mode and sd card appears in explorer. If I open ethos suite it breaks the usb connection and ethos suite not pick up the radio. This in in win 11. If I use win 10 (laptop) all works fine. Anyone else got this problem, and has anyone got an idea on a fix many thanks.

**Comment by mawzthefinn** [comment]
Windows update broke USB drivers most likely. It's a common issue on later Windows 10 builds and Windows 11. 

I'd suggest uninstalling Suite and reinstalling it. Otherwise you may need to do some forcible driver updating in Windows Device Manager.

**Comment by BladeScraper-Designs** [comment]
I have noticed something similar with 1.4.5.  Can't remember if 1.4.4 did it as I only used that once or twice.

My issue is that Suite only seems to connect to the radio the first time after starting the program.  For example, I have two radios - an X18SE and a X20S.  If I want to connect both of them to Suite for, say, backing up my models, I have to launch the program, connect one radio, do the thing, close the program and disconnect the radio, then relaunch the program and connect the other radio and do the thing.  If I try connecting one radio, doing the thing in Suite, then connect the other radio, it will not connect to Suite without a relaunch.  In addition this happens if I connect the radio, disconnect it, then reconnect it.  Suite does not reconnect until relaunch.  

This even happens when updating the firmware.  I updated my X18SE to 1.4.5 today, and after completing the update and rebooting into firmware, Suite did not recognize that it had booted and said "your bootloader may not support auto switching", so I had to close and relaunch it.  Once I did that, it connected to the radio normally.

**Comment by Highlanderjc** [comment]
> 

I have been unable to find the drivers.

**Comment by NorbertHeli** [comment]
"I can plug the radio into computer in bootloader mode and sd card appears in explorer. If I open ethos suite it breaks the usb connection and ethos suite not pick up the radio. This was in Win10 and also in win 11. 
If I use win 10 (laptop) all works fine."

Same here with 2 x X20 and 1 x Twin X-Lite. I tried everything ( De/Install Suite, delete USB Driver, booting new, Update to win11 with the support of the German FrSky Forum over more than 20 stage. Tried all USB plugs on the computer, tried to plug out all other usb devices and a external powered USB Hub. Nothing helps.

a short video, what happens when suite is started:  https://youtu.be/peNyiel4ej8

Any idea what is the problem?

**Comment by NorbertHeli** [comment]
my Diskussion at german forum about the problem and what I tried:

https://www.frsky-forum.de/forum/index.php?thread/7704-probleme-mit-der-pc-verbindung-tandem-x20/&pageNo=9  #171

There where some other with the same problem.

**Comment by Highlanderjc** [comment]
I eventually discovered this was a windows problem along with what you have installed on windows itself. I did a clean install of windows 11, ran ethos suite and hey presto, it works. I also check it every time I install other fpv, drone and rdupilot stuff.
