### ISSUE TITLE
X20S V1.4.5 Battery undervoltage detection does not work properly.

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#2322]
X20S V1.4.5
Battery undervoltage detection does not work properly.

If the battery voltage is already below the warning threshold when the transmitter is switched on, the warning Battery voltage too low appears once in the checklist.
But then in normal transmitter operation there is no undervoltage warning at all, 
It is no longer recognized and does not trigger a warning message any more. 
This is a serious error!

In normal operation, the warning comes every minute when the battery warning threshold is undershot. 

Tests are at Engel Forum

There are two different situations here.

1. transmitter is on and the voltage drops below the warning threshold during operation. For some the warning message comes and repeats regularly, for others it does not. This would be a bug that should definitely be reported.

2. transmitter is off and battery is almost empty. Transmitter is switched on. Warning message comes and is pushed away. Transmitter remains on anyway. A new warning message does not appear.

**Comment by bsongis-frsky** [comment]
Anyone confirms / infirms there is an issue there? 
I cannot reproduce it
The delay between 2 checks is one full minute after the MessageBox is closed, including the Checklist Warnings Popup.

**Comment by Peterbilt84** [comment]
I have also just tested the whole thing.

Firmware 1.4.5.



Transmitter on. Voltage drops below the warning threshold. Message appears and repeats every minute.

Transmitter off. Battery voltage is below the warning threshold. Transmitter on. Message appears but does not repeat.

**Comment by hrenz** [comment]
another effect
Transmitter on, voltage is 7.8V, threshold set to 7.7V. When the threshold is reached, a warning comes. This warning is repeated every minute - unless the display goes to sleep mode. When this mode is set to 30s, I do not hear another warning. I also find this unusual.

**Comment by HolgerJr** [comment]
I just didn't have a warning either!
What is even worse, suddenly emergency mode, short beep and transmitter off.
Transmitter XEs, Ethos 1.4.5, transmitter active in TD mode, no further LUA activated for the model memory.
Battery voltage warning set to 7.2V. Battery voltage after starting the transmitter with switched on HF 7.4V.
What I also noticed is that the inactivity warning also does what it wants. Sometimes it responds as set, but very often it doesn't.

**Comment by bsongis-frsky** [comment]
Bug found and fixed last week. This is why nobody could reproduce it in 1.4.6 which is about to be released

**Comment by bsongis-frsky** [comment]
The inactivity warning is something else. I guess it's the sticks value which change a little bit (analogs) and the radio is considered as alive. Would you please try to disable the sticks / gyro in this menu?

![image](https://user-images.githubusercontent.com/50834778/212273958-ec03042a-64b9-404f-b4ef-e035f9459826.png)

**Comment by bsongis-frsky** [comment]
Also please tell us on which radio you see a problem with Inactivity Warning

**Comment by bsongis-frsky** [comment]
It could also be the gyro. Please try to tell us which one is involved on your radio!

**Comment by HolgerJr** [comment]
The Radio is the XEs.
In the Wake for the inactivity warning no option no is selected.

**Comment by bsongis-frsky** [comment]
Is your gyro calibrated correctly?

**Comment by HolgerJr** [comment]
I have not changed the factory settings.
How should the correct calibration be done?
How far does the transmitter have to be turned or tilted for calibration?
I have now performed a new calibration. I can't say whether it's correct, because the description for the calibration is very ambiguous.
I will observe the behavior with new calibration.

**Comment by HolgerJr** [comment]
I'll add some translated messages to Engel's Frsky forum and hope the translator does a good job and it remains understandable.

Quote from Andreas Engel (support team)
Did you install the soft springs? Could it be that there are somewhat larger fluctuations when the transmitter is on the table? Say, when you bump into the table, for example, or write on the PC keyboard, for example?

Hi Andreas,
the springs are the ones that were installed. I don't know if those are the stronger ones.

The table should not wobble or vibrate, it should be completely stable with an extremely high dead weight and completely torsion-resistant, since it was self-made. The whole house would have to shake. And if I'm not near or at the table, the inactivity alert still doesn't work correctly. Sometimes it works sporadically and other times it doesn't. I can't really understand at the moment what's wrong. The filter range for the analog encoders may not really be sufficient. But that's just a guess.

Greeting Holger


Hi Andreas,

To be honest, the inactivity warning issue doesn't really bother me that much, as I don't consider this feature to be essential. During my long-term tests with the LUA, I only noticed that the function does not work reliably and very sporadically and actually only mentioned it because I believe that an implemented function should also work safely and reliably. If it doesn't, there may be an unwanted interaction or an error in the programming, but it doesn't have to be. Possibly the limits are too narrow for certain donors. Possibly even the gyros of the transmitter are evaluated, although they are not ticked in the wake up, as Bertrand had asked. Again, he then asked again about the calibration of the gyros. At the moment I'm showing the values ​​of the transmitter's gyro axes in the upper window of the XEs and they don't move on the table, but there is still the green-yellow flickering of the lower half of the upper display. And now the flickering only came when there were changes in the displayed encoder values. Since the display of the gyros only shows whole percentage values ​​without a comma, one or both axes may have a value that lies between the resolution of the gyros and internally there are always fluctuations between two output values ​​in the umpteenth decimal range and maybe the filter does not work or is too narrow, since gyros should otherwise react to the slightest change. If the gyros are now in the evaluation for inactivity despite the absence of a check mark in the wake up, then they may be the cause.

Greeting Holger


Hi Andreas,

one last comment on the inactivity warning. Curiously, after a few adjustments of the time and the silent mode between off and on, I had a function that worked perfectly for a short time when the transmitter was on the table, with the warning switched on after a set time and the announcement being repeated regularly after each additional approx . 30 seconds. And the same thing repeated after activations on the transmitter and new phases of rest. However, the normal function only lasted until the transmitter was switched off. The next time you turn it on, everything only worked sporadically again, both time and repetition of the announcement, everything only sporadically and as it wants.

When it worked as it should for a short time, I noticed that the transmitter's gyros are included in the cancellation of the inactivity warning. In the wake up, the gyros and everything else are not ticked for me. I carefully lifted the transmitter so that the sticks didn't vibrate, the inactivity warning that was active at the time was immediately canceled and the announcement was no longer repeated. After putting down the system and not working on the transmitter any further, the inactivity warning came back after the set time and also with a repeat. However, all this only worked until the transmitter was switched off. And the next time you turn it on everything as usual, totally sporadic.

To be honest, I don't find it beneficial to include the gyros in the evaluation for the inactivity process. Any vibration that I would rule out with my desk inevitably leads to the suppression of the inactivity warning. Or if you absolutely want to include the gyros, then the filter should be very wide so that the gyros do not lead to the suppression of the inactivity function with every slightest movement. At the moment it is probably even the case that it is sufficient if the transmitter is in an unfavorable position and the gyros jump back and forth independently between two resolution values ​​or for whatever reason (temperature compensation or reference voltage fluctuation), the addressing of the Inactivity warning is suppressed.

If you now live near a busy road, the railway near a tram and there is vibration all over the house, then the whole thing is not going to work properly at all at the moment anyway!
