### ISSUE TITLE
CRITICAL: "Flight Mode 0" not forceabel any more!

### ISSUE THREAD

**Issue by LuHaGH** [FrSkyRC/ETHOS-Feedback-Community#2328]
According to [https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2228](url) there was a change in the Flight Mode handling.
Now it is not possible to force the default Flight Mode any more by a Switch.

But this FM must be the "maximum save" FM "Autorotation" for helis eg.
In case of a misconfiguration the default FM is set, where it is sure that the engine is off.
And of course you want to force this FM in case of an emergency via switch.

So the solution of the Issues 2228 is not to remove the switch from FM0, but to implement a "force switch" AND set FM0 to active when no other flight mode is selected.

**Comment by mawzthefinn** [comment]
FM1 is supposed to be the forceable FM (with the highest priority) as per the documentation, and matching standard behaviours on other OS’s, FM0 is the fallback, active only when all other FM’s are not true. 

Being able to force FM0 breaks expectations in a lot of setups in the case of a user mistakenly adding a switch to FM0.

**Comment by Dsrenger** [comment]
That means, if I have a dedicated landing flightmode with crow on a glider. I have to create fm1 for landing and recreate the same FM as fm0?

I always created the crow FM as fm0 and assigned a switch to it.

So when something went wrong with the switch assignments it goes into fm0 and I can land. It is the safest setup.

I assigned a switch to it the force it. (So it does not matter where my 3-switch is for thermal, normal and speed)

Now I have to create fm1 with crow...fm2-4 for thermal, speed and normal and additionally fm0 that is basically the same than landing?

Not saying that's bad(well... ;)) But just to understand what's the "planned" way of doing it is.

**Comment by LuHaGH** [comment]
> Being able to force FM0 breaks expectations in a lot of setups in the case of a user mistakenly adding a switch to FM0.

There is no problem when you add a "force switch" to FM0 which must be the most important and safe FM in every model setup. When you forget to set an other FM, no problem, you are in the safest one automatically. When you want to force it, hit the switch. If you want a FM with lower priority, unset the force switch.
When you setup FM1 as your most important Flight Mode, than you did it wrong, cause FM0 has the higher priority and must be the most important FM.

**Comment by mawzthefinn** [comment]
I disagree very strongly on that. FM0 is the failback FM, the one that becomes active if no switch is active (ie lowest priority). It must be a safe/flyable mode (cruise for sailplanes, as that's the mode that is flyable in the most conditions)

The override/highest priority FM is separate, that locks out all lower priority modes so long as the switch is active. This must be launch on a sailplane, as that MUST lock out landing mode (popping landing on the winch would be disastrous and a massive safety issue, similar for DLG, although likely less spectacular)

Note the current behaviour matches OpenTX exactly. FM0 is the lowest priority mode, not the highest. What you are asking is for the switch to go back to breaking the priority chain, which I very strongly disagree with. The failback mode and the highest priority mode are supposed to be separate functions.

**Comment by mawzthefinn** [comment]
@Dsrenger Base FM priority I use (shamelessly copied from @rc-soar because he got it right IMHO)

FM0 - Cruise
FM1 - Launch
FM2 - Zoom
FM3 - Landing
FM4 - Thermal
FM5 - Speed

All but FM0 have a switch assigned. failback is to cruise as that's most flyable (although the landing will suck without crow). Crow is only active in Landing so that Launch/Zoom can lock it out.

**Comment by Dsrenger** [comment]
If that's the way it's planned....

Thanks for explaining.

Guess I need to update some of my models ;)

I always avoided to create more FM that I really plan to fly and choosed the safest one as FM0.

Learned something today :)

**Comment by mawzthefinn** [comment]
I should note I design my setups so that switch failure in flight are accounted for. There's always 1 condition that is active for any critical item if the switch up and disappears (which I have seen happen on old X9D's due to hardware failure. Rare but real)

That's why I design with failback and highest priority to be separate. If you need them the same, a duplicate achieves that (you have 20 FM's to play with)

**Comment by LuHaGH** [comment]
There are thousands of helis with the following config out there:

FM0 : Autorotation
FM1: RPM1
FM2: RPM2
FM3: RPM3

All this people cannot switch off their engines any more. This is dangerous as hell.
You must not change this behavior in an existing config in a minor FW Update without a big red notice.
There isn't even a hint in the release notes.

**Comment by mawzthefinn** [comment]
I very much doubt there are more than a handful of users using that setup, since the only way to make it work is to exploit an undocumented UI bug (the ability to re-order FM’s to give you FM0 with a switch, since you can’t set one normally in FM0, only by setting a lower-priority FM to have the switch then re-ordering).

The fix makes things safer for most users, since now users cannot accidentally put FM0 on a switch, which is the reason why the bug was found and fixed in the first place. It also matches the logic that thousands are used to in OpenTX.

**Comment by STC148** [comment]
I don't know anyone who has engine off on FP0. Nothing has changed in the logic, the highest priority has always been FP1. I can not see any problem here.

**Comment by mawzthefinn** [comment]
I would actually recommend the following map for heli’s

FM0 - Spool Up/Normal (minimum flyable mode)
FM1 - Autorotate
FM2 -  Idle Up 1
FM3 - Idle Up 2

Then a failure of a the Idle up switch won’t force an autorotate, but Auto-rotate will still override all other FM’s.

**Comment by LuHaGH** [comment]
No, FM0 must be a mode with engine off in case of a switch failure.

**Comment by hrenz** [comment]
there is nothing to change in FMx 
FM0 = D = Default, Fall back
FM1........FM9  are the priorities

**Comment by Dsrenger** [comment]
Yeah, today I learned I have to do the following in the future(even if I hatte to maintain a FM that will hopefully never be used. Would prefer a setup where FM0 is a FM that I fly in during a usual flight as well.

FM0 - duplicate of FM 1 just there as fall back FM
FM1 - landing
FM2 - thermal
FM3 - cruise
FM4 - Speed

I cannot accept the workaround (it's just that for me)

FM0 - cruise
FM1 - landing
FM2 - thermal
FM3 - speed

As trying to land without crow in my spots results in a lost airplane ;) often you have to land in your hand ;)

@mawzthefinn 
As you are the expert, can you confirm the first setup  is the "correct" way to set it up if you want FM0 to have crow and thermal/speed/cruise on a 3 position switch, but being able to switch into landing phase no matter where the 3position switch is?

Just want to avoid to rework my model in the future again, as all of my models are corrupted due to the change at the moment ;) used the UI "bug" (for me it was more of a feature ;)

**Comment by mawzthefinn** [comment]
@Dsrenger - Yes, that makes sense, with your use case. 

@LuHaGH - Please check Page 241 in the English manual, the default FM is NOT the same as the priority FM in ETHOS.
Also your throttle hold/cut should be tied to the functionality in the Throttle mixer, not FM’s directly. Autorotation mode and throttle hold/cut are two different functions.

**Comment by Dsrenger** [comment]
Thanks for your patience...

A little bit more work, but I see the concept. even as I would do it different if it would be my OS. But that's fine :) I see the concept.

Really appreciate your help... I really mean it without irony :)

**Comment by mawzthefinn** [comment]
@Dsrenger - Actually just thinking this through and you can do an easier table by using the FM1 activation to instead disallow the 3 flight modes using logical switches. That way you don’t need 2 Landing modes.

**Comment by Dsrenger** [comment]
@mawzthefinn 
Hmmmmm,

I need to think it through what to do with logical switches.

FM0 - landing
FM1 - thermal
FM2 - cruise 
FM3 - speed

FM1 activated by a logic switch thats activated by "SA up AND SC down"
FM2 activated by a logic switch thats activated by "SA mid AND SC down"
FM3 activated by a logic switch thats activated by "SA down AND SC down"

If I flip SC up all 3 FM gets deactivated regardless of SA and therefore FM0 gets active.

Is it that, what you meant? Ethos is so cool....

That would work. Thanks for hearing me into the right direction. If that's what you meant :)

**Comment by mawzthefinn** [comment]
That’s exactly what I meant.

I should note my usual landing trigger is Thr<95%, so I trigger it just by deploying  butterfly.

**Comment by strgaltdel** [comment]
.. its my understanding, that in case you want an enforcable fm0, you could do it by using LSWs

define an "deactivate fm0" condition wich is false in case you want to enforce fm0

let fm1 .. fmx activate by a lsw that combines your favourite switch condition AND the "deactivate  fm0" condition

so in case your switch sets the deactivation condition to "false" you'll automatically get fm0


another way would be to introduce an optional "overwrite active fm" condition in fm0 for those who really need this

**Comment by Dsrenger** [comment]
Thanks a lot.
It's even more elegant to define a second lsw that replaces SC in the table above. This logical switch will be triggered by SC. With that you can reassign from SC to SD in one logical switch instead of 3.

Thanks again folks. Topic is done for me. Appreciate your help :)

**Comment by mawzthefinn** [comment]
After confirmation from @bsongis-frsky, confirmed that the direction provided is correct and the current behaviour is the designed and intended behaviour with FM1 as the highest priority and FM0 lowest.

**Comment by LuHaGH** [comment]
Maybe it was the intended behavior with FM1 as the highest priority and FM0 lowest. But Up to now (I tested it with 1.4.3 today) FM0 have had the highest priority. An if you change such an important thing you have to inform the users about that.

**Comment by mawzthefinn** [comment]
The current behaviour matches what is in the manual and what would normally be seen by users.

 There was a UI bug that allowed FM0 to have a switch if you re-ordered a lower-priority FM into the FM0 slot. That was fixed in 1.4.5 and is in the changelog for 1.4.5
