### ISSUE TITLE
Tandem X20s 1.4.6EU Firmware -no full lenght music playback, Channel assignment of Aileron only 4 possible

### ISSUE THREAD

**Issue by Xtreme-RC** [FrSkyRC/ETHOS-Feedback-Community#2377]
Tandem X20s 1.4.6EU Firmware:

Ethos suite converted music track wav file is not played back in full lenght when assigning with a switch- its cut after some seconds.
This is a must have to play back the full track to train freestyle routines with music. It makes no sense to cut a track off in lenght when the function is already there.
It should also be possible to pause, stop and restart from current timline value.

Channel assignment Aileron for Example: in basic can be choosen only 4 output channels, but 3meter Aerobatic planes have 3-4 Servos per Wing, makes a total of up to 8.  Ok its possible to create mixer, but this should be available to choose with maximum possible value directly for Aileron, Elevator and Rudder.

**Comment by mawzthefinn** [comment]
The first request is a functional duplicate of #773, or at least depends on the introduction of background playback and audio mixing. Without background playback, full-length playback is not possible because it would block all other audio callouts. 

The second is working as designed, for UI simplicity but could potentially be changed in the future. I would simply create a second Aileron mixer for the other set of servos. Trim will be common between all Aileron mixers. The one issue here is  that the Aileron outputs alternate right now (left/right/left/right) so the same setup must be followed rather than having a Left wing mixer and a right wing mixer. You could also replace the canned Aileron mix with 2 Free mixers, one from the Aileron source and one from the Aileron trim. Free mixes allow arbitrary numbers of outputs and are often the best way to do more demanding applications. You lose Differential this way though and would have to program for it manually.

**Comment by pstasek** [comment]
Thanks for the heads up. If this is not going to be implemented (and I fully understand the reasons), I think a nested mix is the best option of all then.

Creating a regular 2-channel aileron mix with all the features like differentials, trims, expos and rates as an input, and setting the output to two channels out of receiver range, for example, 25 and 26. Then create a free mix for each side and use a source Channel 25 for the left-wing mix and Channel 26 for the right-wing mix with as many channel outputs as needed just to send the same signal to all of them, while being able to synchronize them in Output screen.

![image](https://user-images.githubusercontent.com/4296578/226671890-78e9b407-cdec-4c57-b878-52b75e4a77d0.png)
