### ISSUE TITLE
Supplement Hold position in mixer 

### ISSUE THREAD

**Issue by Peterbilt84** [FrSkyRC/ETHOS-Feedback-Community#2379]
For self-centring sticks, curve returns to initial value as soon as stick is released.

A hold position option would be very nice. When the stick is moved halfway and released, the curve should stop at the halfway value. Only when the stick is moved down, the curve goes back to the initial value.

An alternative would be to create a new mixer for this behaviour.

**Comment by mawzthefinn** [comment]
The curve does not return to  the initial value, the stick does. The curve reflects the current stick position in the exact same manner for all analogs (current position).

I know this behaviour is useful for some robotics and surface uses for emulating hydraulics, but it also seriously breaks the base concept of proportional analog inputs. 

It’s best addressed for now by custom Lua sources or for basic applications by the combination of stick detection logic switches and a Trim mixer (which can do a fixed speed emulation of hydraulics, at least until the repeat speed issue on trim mixers are addressed).

**Comment by Peterbilt84** [comment]
The word curve was the not quite clear. It is about the position of the stick on the curve.

It works like the accelerator pedal of a car with cruise control. At the point where the pedal is released, the speed remains constant and does not increase any further.

**Comment by Peterbilt84** [comment]
The basic concept of proportional analogue inputs remains unchanged.
The mixer and its behaviour remain the same. Nothing changes at the output either, regardless of whether I hold the stick in one position all the time or whether the software does it for me.

**Comment by mawzthefinn** [comment]
I understand completely what you are trying to achieve, I’m pointing out that the mixer curve position/output always reflects the current input. There are a couple ways to do this, but they are roundabout because a mixer reflects its inputs always. What you need to do is change the inputs, not break the mixer.

The two solutions I suggest will work. In fact I just tested out a new variation that works even better using 1 Free Mix, one VAR mix and 5 Logic switches.

Create a Free Mix, Source of a high channel (say ch64), Output the desired channel, set servo slow up &  down to reflect how fast you want it to charge when jumping far.
Create a Logic switch, Type A < X, Source - The stick you want to use, Value -2

Create a second logic switch of Type A < X, Source - The stick you want to use, Value - Use a source ->Channel, Channel your free mix outputs to, active condition of the first logic switch.

Now duplicate those two logic switches using A > X and a value of 2 for the first one. Active condition of the fourth LS is the third LS

Make a fifth LS, Type OR, Value 1 is the second LS, Value 2 is the fourth LS

Now make a VAR mix. Default weight is ‘Use a Source->Channel output of free mix’, Add a weight, switch is the fifth LS, weight is ‘Use a Source->stick desired’, output is the high channel you selected as the source of the free mix.

This will change the input of the free mix between its current position and the current stick position, based on the stick position relative to the current output. Servo slow controls how fast the output can change, tune as necessary to get the speed desired.

**Comment by uj-berlin** [comment]
This is easy to realize with a recursive mixer as described in #2357. This mixer must then be stoppable at 100%. This behaviour ist essentiell for that kind of application. It would be a great addition to allow a clipping of the mixers.
An other interesting way would be a new variation of the mixer for this purpose.

**Comment by mawzthefinn** [comment]
Proxying the mixer through the VAR mix solves the >200% issue you see with a regular recursive mixer, without breaking the functionality from stacked mixers on one channel that is the reason why you can exceed 200% now on individual mixers.

**Comment by hrenz** [comment]
This is much easier
With a recursion mixer / integral mixer 
A range monitoring by 2 log switches
2 mixers for up and down movement and recursion
2 Example for V1.4.6  with 1 or 2 Hydraulik Zylinders

[AUTO.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/10527659/AUTO.zip)

**Comment by mawzthefinn** [comment]
@hrenz that solution does work, but since it uses 3 mixers, 2 logical switches and 3 curves I'd suggest it is actually more complex than the 2 mix/5 LS solution I proposed. 

Your solution is superior however in one major regard, it is more responsive to the stick position in terms of speed sensitivity.

**Comment by uj-berlin** [comment]
With clipping to 100% you only need two mixers to realize a hydraulic simulation or similar. No logical switch or other workarounds. This is a very simple way and was possible before 1.2.11. It would be very useful to make clipping possible. To avoid conflicts, this mixer type can get another name. So fliers will not be confused.

**Comment by hrenz** [comment]
Hy, 
the 2 log switches and the 2 motion mixers are only necessary since the mixers run internally up to 200%.

With a special mixer, a so-called integral or recursion mixer, where you can enter the range limits directly and limit the clipping, you can save the 2 log switches and a free mixer.
It would be enough to be able to enter a range in an extended free mixer, like the trim mixer has.

This would make a lot of things easier for the many function modelers with hydraulic and cylinder movements.

Please think about it and extend ETHOS with a special recursion mixer.

**Comment by Peterbilt84** [comment]
An extra mixer for recursion would be the best solution.
Creating 2 mixers and 5 logical switches to realize a function contradicts the concept of Ethos.

Ethos should have a simple and clear menu. Through the many unnecessary mixers, the clarity is lost.
An extra mixer, would then even be a unique selling point of Ethos.

**Comment by mawzthefinn** [comment]
Unstale, the surface folks still want this.
