### ISSUE TITLE
GPS Altitude incorrect

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2390]
gps altitude being reported incorrectly in ethos.  I am getting -98 ft for my house when it should be about 400ft.  i get 400 ft when i use my horus x10  se on the same model. i get the right variation just off 500 ft.

**Comment by williajgr** [comment]
I am using release 1.4.6

**Comment by strgaltdel** [comment]
determination of the vertical position is always the most unreliable value with GPS due to physical conditions (VDOP) and is subject to greater fluctuations.
Only with a higher number of received sats does the value become reasonably stable.

The problem is not likely to be on Ethos side,
but on the then actual reception situation.

Was the almanac already up to date when the worse value was displayed? 
How many sats were received in situation A, how many in situation B?
what was the PDOP / HDOP or even better VDOP value?
(if available: oXs GPS can output several parameters on SPort).
Without such information, no comparison can be made.
Such differences can occur with one and the same GPS within minutes, especially at the beginning, when its almanac must be updated which can last about 15..30 Minutes

Was the module left in the same place for about 15..20 minutes (or longer) in good reception conditions and then briefly and repeatedly changed back and forth to receive again for 20 minutes each time?
This is the only way to roughly determine whether the error moves with the operating system or whether it is (very likely) a typical GPS "dilution of precision" problem.

Alternatively, you can read out U Blox GPS modules directly via FTDI adapter directly by means of software on the PC and get exact values for comparisons.

**Comment by williajgr** [comment]
sorry all of that is true but, i hook up the model to my open tx transmitter then hook it up to my ethos transmitter (same place and time) and get different answers and always 500 ft difference. -98 and 400. and i happen to know 400 is the right height for my house..

**Comment by strgaltdel** [comment]
I made a crosscheck:
X18 (1.4.6) bound to an X8r  with oXs GPS,
waited app. 30..40 Minutes after first fix so that the GPS was "up to date" with stable coordinates and Altitude

than i switched off the X18, switched on my X12 running otx, set the X12 into bind mode and performed a very short power cycle of the Rx in order to get him into bind mode,
so the GPS had no "real chance" to loose his volantile data (which are buffered for a short time)

I had definitely the same Altitude between oTx & Ethos by using an openXsensor GPS

**Comment by williajgr** [comment]
i am using the FrSky GPS ADV Sensor.

**Comment by Satcomix** [comment]
Hello everyone,
I also work a lot with openXsensor_on_328P or oXs_on_RP2040. The GPS altitude information varies from protocol to protocol. With my FrSky X20S I see the relative altitude under GPS_Alt and when I change the protocol to HOTT I see the absolute altitude above sea level from the GPS.
I only noticed the relative altitude with Ethos 1.4.6, until then I thought it was the absolute GPS MSL altitude.
Perhaps in the future there is an option in the Telemetry GPS Sensor menu to switch between the relative and/or absolute altitude, or to display both.
Thank you for the work so far.
br,
Torsten

**Comment by strgaltdel** [comment]
i was testing near msl, that would explain a lot.
differences between ethos / otx less then 20m

so, yes, user options to choose between relative/absolute values would be fine

**Comment by williajgr** [comment]
that seams about right. if ethos is reading relative alt and open tx is reading absolute alt. Both have merit. would be nice to be able to pick which one to have..

**Comment by Satcomix** [comment]
Hello everyone,
The way I see it, it's not an error in the Ethos system, but a matter of presentation in the Ethos interface.
So it should be a feature request to show the GPS Altitude value as either a relative and/or absolute value.
You could do it with free IDs from the DIY sensor area.
The developers could express themselves on this topic.
Best regards,
Torsten

**Comment by williajgr** [comment]
I would like to see the option.   Not sure which one i would pick if i had the option.  But the gps module does get a different answer than it did in any other  os.

**Comment by williajgr** [comment]
any comments from the developers?

**Comment by williajgr** [comment]
did this issue die no comment from the developers????

**Comment by williajgr** [comment]
what do you have to do to get the devs to comment?
