### ISSUE TITLE
Confusion in  stick names and function assigned

### ISSUE THREAD

**Issue by 3frcg** [FrSkyRC/ETHOS-Feedback-Community#2426]
The first thing I did with my Ethos transmitter was to rename the four main inputs to the initial letter J. This way I don't confuse the name of the stick with the name of the function. 

 I normally assign a switch for the motor function on gliders. In the mixer I also distinguish between the function, (motor not throttle) and the actuator, the switch. I suggest renaming the four stick actuators so there is no confusion. In Futaba it was traditionally J1,J2,J3,J4. I suggest JRH, JRV, JLV,JLH or any other similar.

**Comment by 4qr1hu9n7** [comment]
This isn't Futaba.

**Comment by 3frcg** [comment]
> This isn't Futaba.
Very positive contribution. Thank you very much indeed !

**Comment by 4qr1hu9n7** [comment]
Glad to help.

**Comment by Wolepo** [comment]
Completely superfluous

**Comment by mawzthefinn** [comment]
The transmitter mode sets the stick functional assignments (eg Analogs->Throttle). They are named because you are mapping analog functions not raw sticks.

If you set Mode 1 the ‘Throttle’ analog function is mapped to a different stick than it is if you set the radio to Mode 2.

The reason for this is to enable trading of model files between radios running in different modes without requiring any program changes.

The very old school Futaba solution is not  well suited to trading model files between radios and would be a significant step backwards in functionality.

**Comment by mawzthefinn** [comment]
Closing off as per my previous comment.

**Comment by 3frcg** [comment]
I will try to explain my previous question with an example:

Let´s suppose  a glider with electric motor channel assigned to a switch.  
Butterfly is controlled by the "throttle" stick.

In Trims page, T3 is assigned by default to Throttle. What is Throttle ? the throttle stick, no; the function throttle, no, the butterfly function, no.

How assign trim T3 to the motor channel without resorting to a mixer taking as input the trim? 

By the way the trims are named and engraved as T1,T2,T3,T4.  

Thank you for your patience.

**Comment by mawzthefinn** [comment]
The Radio mode setting determines which stick is 'Throttle'. In mode 2 that's the left vertical axis, next to T3

Trim Throttle is assigned to the Throttle mixer (just as Trim Aileron is to the Aileron mixer)

The Throttle mixer will take trim input from T3 by default when the radio is set to Mode 2. Assigning an alternate trim to the Trim Throttle function is done in Model->Trims->Cross Trim. Use the Throttle Mixer to control the motor (it does allow for arbitrary Inputs to be assigned)
