### ISSUE TITLE
1.5 nightly - cannot dynamically update (via VARs) multiple curve points concurrently

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#2483]
I'm attempting to implement my [crow-aware trim Lua script](https://rc-soar.com/opentx/lua/adaptivetrim/index.htm) using the new VAR function. However, I'm not able to dynamically update more than one curve point at a time, as I can with the script..

Steps to reproduce in Ethos 1.5 nightly:

1. Create two logical switches:

```
LS1 'Zone1' Throttle in range [-100%:-67%]
LS2 'Zone2' Throttle in range [-83%:-25%]
```

The ranges overlap, so LS1 and LS2 are both active when throttle in range -83% to -67%

2. Create two VARs:

```
VAR:Pt1 if Zone1 repurpose elevator trim
VAR:Pt2 if Zone2 repurpose elevator trim
```

3. Bind these VARs to points 1 and point 2 of a curve. This works as expected, when either LS1 or LS2 is active. 

When both LS1 and LS2 are active, I would like both points to be updated simultaneously, however only one point on the curve is updated.  Is this a limitation or a bug?

The rationale for this is as follows: if the pilot has the crow stick is midway between two curve points, the elevator trim should move both of the _adjacent points_. Without this facility, it'll be a lot more difficult to achieve an optimal curve compared with the OpenTX/Lua solution.

**Comment by strgaltdel** [comment]
by the way,
when i tested 1.5n 2 week ago on my X18, i could reproduce following behavior of the repurpose action:

throttle trim was deactivated / activated as wished
Var mixer value (vars not implemented by this time) stayed active every time.
i would have expected that repurpose would "alter" between two modes, but so i had a situation that i was trimming throttle channel and var mixer simultanous, or vars alone.

can' test now because i'm on a foreign trip.

**Comment by RC-SOAR** [comment]
I can see why it makes sense to prohibit multiple Repurpose's _within_ a Var.  
However I don't understand why the same trim cannot be repurposed in multiple distinct Vars - the trim is just bumping the VAR value. When the trim is not being repurposed in any VAR, it could revert to default behaviour.
Or maybe I've missed something? Either way, it would very handy if this limitation could be relaxed.

**Comment by mawzthefinn** [comment]
Consider that the affected VAR's may not be controlling the same thing at all.

Picture this - X20, Gas/glow, Stab & flaps (ie my Valiant 10cc)

Throttle trim is set for low position trim normally (idle adjust). When throttle goes over 25%, the master gain VAR repurpose engages so that trimmer now becomes live as the gain adjustment. this is the normal state of the flying configuration. When flaps are deployed, a second repurpose engages to adjust the flap->ele weight.

Your proposal would have the gain and flap->ele weight being adjusted at the same time unless deliberately locked out via a more complex logic switch setup controlling the gain adjustment.

**Comment by RC-SOAR** [comment]
Surely this kind of conflict is already possible without VARs? It's always been the user's responsibility to avoid such conflicts, by sensible programming (for example by using FM's to restrict scope, if possible).

It may seem like a nit-picking detail, but being able to bind two curve points to the same trim makes a big difference in terms of usability for this application. It still feels like an arbitrary and unnecessary restriction.

**Comment by RC-SOAR** [comment]
This vid shows simultaneous updating for two curve points via OpenTX / Lua script.  It should be fairly clear why it's so useful/essential.

https://youtu.be/bzznn_io5J8?t=41

**Comment by lthole** [comment]
I agree with Mike. As with most programming, I would use flight modes to avoid a conflict in overloading.

**Comment by bsongis-frsky** [comment]
The same kind of Lua script would do the same in Ethos ;)
But I think I do like the idea of having multiple actions on the same trim!

**Comment by RC-SOAR** [comment]
@bsongis-frsky it's already a 1/2 killer feature [binding VARs to curve points]. Multiple actions would make it totally killer IMO. Users of other brands would sell their grandmothers to do this kind of curve manipulation directly from the operating system :-)

**Comment by RC-SOAR** [comment]
Ah, I missed that this had been self-assigned - many thanks :-)

**Comment by bsongis-frsky** [comment]
Ready for next nighties

**Comment by lthole** [comment]
Hi MikeOnce you have a working adaptive trim setup, would you mind sharing the model file so that I can play with it?Thanks,LotharOn 8 Mar 2023, at 8:54 pm, Mike Shellim ***@***.***> wrote:﻿
Ah, I missed that this had been self-assigned - many thanks :-)

**Comment by RC-SOAR** [comment]
@lthole Hi Lother, yep no problem!
