### ISSUE TITLE
Crossfire lua not working x18 1.4.7

### ISSUE THREAD

**Issue by rwijnhov** [FrSkyRC/ETHOS-Feedback-Community#2492]
On my x18 1.4.7 the crossfire lua is not working right. Most of the time it doesn't come up. If it does it is realy slow and bind button not working.

**Comment by rwijnhov** [comment]
No i use this
https://github.com/FrSkyRC/ETHOS-Feedback-Community/tree/main/lua/crossfire

If i press configure most of the time i don't even get the config settings but a blank screen.

**Comment by Target0815** [comment]
Do you have the current script installed? I have uploaded the current version on 2022-12-28.

What also happens sometimes: the script is not downloaded in RAW format and/or opened with a wrong editor. The .lua is a plain text file. 

With my X18S and Ethos 1.4.7 it works otherwise without problems, I just tested several times.

**Comment by rwijnhov** [comment]
I found the issue. I had an other lua script running in my widget screen. Removing that makes the crossfire lua run fine.
