### ISSUE TITLE
Cant get Suite to work 1.4.7

### ISSUE THREAD

**Issue by NiclasHaraldsson** [FrSkyRC/ETHOS-Feedback-Community#2499]
When I connect the X20s to suite it switch between connected and not connected all the time.And windows tells me there is a problem with the USB.Have used this computer and the same radio before with earlier versions of suite.And it has always worked,
So maybe something is wrong with sute 1.4.7

**Comment by NiclasHaraldsson** [comment]
im on the latest fw 1.4.7 and 2.2.2 on the radio...i used the old sdcard uodate process :)

**Comment by strgaltdel** [comment]
Pretty shure 1.4.7 is not the root cause, 
if so there should be a lot more users with this problem.

for example i'm using the suite on 4 different pc's & notebooks.
win 10/11
one usb port of a lenovo notepad gives a "high current"  alert and disables the port by connecting the x18,
all other ports are working well.
keep in mind that there can be different specs of usb ports (even on the same notebook / pc)
so a new software revision can exceed the specs of an "old fashioned" port
(wont say this is your problem)

nevertheless,
first actions to try are imho:

- use another "quality" usb cable, lot of usb problems disappeared then

- update bootloader if outdated

- try another port ( or machine for a crosscheck)

- evaluate some details of the issue by check device manager & win error logs

btw
germany's premium dealer reported some defective usb ports on tandems after users charged with "cheap" usb power supplies that raised voltages above specs..
does your charger support qc or pd ?

**Comment by Marisha62** [comment]
I have the same issue. Connecting X20S to PC as Ethos Suite works fine. No issues. No issues using X20S as joystick. However, Windows disconnects X20S when I start the Ethos Suite. Issue affects version 1.4.4 (I think) through 1.4.7. Everything was OK before that as far as I remember.
Since there is no problem using bootloader or just Windows to transfer files to/from the SD card I have just written this off as an issue on my PC.

**Comment by NiclasHaraldsson** [comment]
its a qc charger

**Comment by mawzthefinn** [comment]
Some cheap QC and PD chargers have burned out the USB interface on the radios.

This is because the charger is out of spec and is delivering >5V without QC or PD modes being requested by the radio. That is against the QC and PD specs specifically to prevent this issue.

**Comment by NiclasHaraldsson** [comment]
I have ordered a new mainboard.Hopefully it wont be to much fuzz to change it(have been modding Tv-concoles for 15 years)
I come back with the results

**Comment by bsongis-frsky** [comment]
No, it's not difficult to change. Please reopen the issue if needed.
