### ISSUE TITLE
Get output value from Channel in lua script

### ISSUE THREAD

**Issue by Storchy1** [FrSkyRC/ETHOS-Feedback-Community#2505]
i need the value from a channel in my script.
i use the function:
local source = system.getSource({category=CATEGORY_CHANNEL, member=ch})
local value = source:value()
I think this is the Mix-value (yellow) of the channel if the min / max and subtrim is not changed
How can i get the real (blue) value if these values are changed see pic
perhaps you can add an options parameter option_output to get the blue value
![Ethos Simulator](https://user-images.githubusercontent.com/26022422/225568658-6d1ac8c1-cc82-48e0-9eb0-702b5b52a7e8.png)

**Comment by strgaltdel** [comment]
this is a very early stage of an UI to let users easily manage the new (1.5.0) GVAR implementation
Goal would be to provide "one pane of glass" in order to configure mixer weights / deflection rates etc..
Requirement would be a template where all these "bells & whistles" are summarized in the xvar section.

in theory, a user wouldn't have to elaborate/understand the mixer logic of  templates made available by the community to finetune his model.
the widget would be an "on top" tool to make configuration a little bit more simpler then browsing between the "xvars pages"

**my point is,**
in case there would be such a tool AND you would be able to display the "real" output value it would be **much** easier to migrate models from other vendors remote systems, because users could tune the deflection/mixer rates until it reaches the same output value than on it's former "3rd party" configuration without switching between several pages.

![image](https://user-images.githubusercontent.com/20392683/225599543-1dd773ac-7b92-4971-8e33-89482c91aaec.png)
  
(of course at this moment there is now way to read&write Xvars by lua, but maybe in the future ?)

**Comment by mawzthefinn** [comment]
It should be noted that ‘Channels’ when referenced in mixer logic (and it should be the same in Lua) are always the output of  the mixer stack, which is  the input to  the Outputs stage  and not the output to  the RF stage.

**Comment by Storchy1** [comment]
That is right. It would be helpful to get the value to the rf output. For instance if the option parameter is not wanted, perhaps a new category something like CATEGORY_RF_OUTPUT is a better solution.

**Comment by strgaltdel** [comment]
... keep alive post

**Comment by strgaltdel** [comment]
... keep alive post

**Comment by bsongis-frsky** [comment]
```lua
source = system.getSource({category=CATEGORY_CHANNEL, member=0})
print(source:value(OPTION_CHANNEL_OUTPUT))
```

**Comment by strgaltdel** [comment]
for sure the option works as intended ?
just tested (source: member = 0 so channel 1):

```
		widget.GV.ChVal = math.floor(widget.GV.activeSRC:value(OPTION_CHANNEL_OUTPUT)/10.24 +0.5)
		print("719 chVal:",widget.GV.ChVal)
```

results in value 86%, which is the mixer output value.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/94456cff-e527-4796-bc17-5282b066937e)

but Channel output is 65%

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/308d9b3a-911a-49f3-aeaf-60565ba0ffa5)

maybe the value is read from the channel output processing before weighting was applied ?

tested with todays Sim 1.5.8  / 17.may

.. and much thanks for this 1.5.8 "within time"  (-;
