### ISSUE TITLE
Mlvss sensor conflict when use more that one Mlvss 1.4.7 on X12s

### ISSUE THREAD

**Issue by yak-54** [FrSkyRC/ETHOS-Feedback-Community#2517]
X12s on ETHOS 1.4.7 with 2 x R8 pro and FrSky RB –20 with 2 Mlvss plug into sport RB20

2 x R8 pros with telemetry enabled on both plug into the rb-20 i keep getting sensor conflict
is this 1.4.7 issue never did it on 1.4.6 and nothing has changed on the plane ?

looks like its only when more than one Mlvss Mini Lipo Voltage Sensor is used

they do have different ID 14 and 15 i changed with Frsky ID changer i can plug either one in by its self it work just not 2 at a time
i get sensor conflict. i did try to change the Ap id from 300 on one and it changes both or them to the same ap id 
but when i check telemetry sensor list there are no conflict sensors ( marked in Red )

i did  update access firmware from Archer-X_2.1.10 to  Archer-X_2.1.12 still the same sensor conflict s well

**Comment by 4qr1hu9n7** [comment]
Change Physical I.D. and Application I.D.

**Comment by yak-54** [comment]
I did and have changed Physical I.D. and Application I.D

**Comment by yak-54** [comment]
its working but she is always nagging   sensor conflict

![screenshot-2023-03-18-33741](https://user-images.githubusercontent.com/9161926/226064342-e5d66ab6-d043-473a-a471-8c3ed48874fb.jpg)
![screenshot-2023-03-18-33756](https://user-images.githubusercontent.com/9161926/226064347-8be774a1-21b2-4fe4-b6f9-c33170ea79c2.jpg)
![screenshot-2023-03-18-33769](https://user-images.githubusercontent.com/9161926/226064348-7427a72f-6271-4b65-8e6c-57a7de5ac555.jpg)
![screenshot-2023-03-18-33785](https://user-images.githubusercontent.com/9161926/226064350-4e0abc5b-1e46-4091-b059-fa50421658f1.jpg)

**Comment by bsongis-frsky** [comment]
Do you mean that the new AppID is not taken into account?

**Comment by yak-54** [comment]
got it working now  just keep getting sensor conflict warring  till I unplug one of Mlvss sensor
and these are the only thing plug into the sport 
 I did  test the with 2 and 3 FLVSS its fine 
 with 2 Mlvss i get sensor conflict warring

**Comment by bsongis-frsky** [comment]
MLVSS / FLVSS are exactly the same at Ethos level

**Comment by yak-54** [comment]
RF ?

**Comment by yak-54** [comment]
> MLVSS / FLVSS are exactly the same at Ethos level

yep i just rechecked it it does with 3 FLVSS new model just receiver nothing else plug in

**Comment by yak-54** [comment]
my bad may off had the volume turn off to stop hearing her telling me sensor conflict

**Comment by yak-54** [comment]
just tested it under Accst in D16 mode on RX8R pro new model still get 
sensor conflict

**Comment by Eagleowl1** [comment]
I had a very similar issue but it solved "magicaly" by itself
(X20S v1.3 at that time)
See  #1836

**Comment by builda1** [comment]
> its working but she is always nagging   sensor conflict
> 
> 
> 
> ![screenshot-2023-03-18-33741](https://user-images.githubusercontent.com/9161926/226064342-e5d66ab6-d043-473a-a471-8c3ed48874fb.jpg)
> 
> ![screenshot-2023-03-18-33756](https://user-images.githubusercontent.com/9161926/226064347-8be774a1-21b2-4fe4-b6f9-c33170ea79c2.jpg)
> 
> ![screenshot-2023-03-18-33769](https://user-images.githubusercontent.com/9161926/226064348-7427a72f-6271-4b65-8e6c-57a7de5ac555.jpg)
> 
> ![screenshot-2023-03-18-33785](https://user-images.githubusercontent.com/9161926/226064350-4e0abc5b-1e46-4091-b059-fa50421658f1.jpg)
> 
> 

I had the very same problem recently with my Flightline liberator, I literally had to individually detect the MLVSS sensors connected one at a time to the receiver, then change the channel ID for one of them. Took me a bit to get it to sort it self out, but it works now. The one thing I did find that I couldn't fix Though was that when I was configuring the screen, it would only let me select 1 Lipo sensor (it wouldn't let me select a second one for a different field in the same screen..... or so I thought! I found on certain screen layout it would work and others it wouldn't.

**Comment by craigywsm** [comment]
has anyone tried this with the latest updates?

**Comment by builda1** [comment]
You cant use two MLVSS sensors together on the same telemetry loop, because for a long time now we have not been able to change the channel ID of them. With the FLVSS you can, but not with MLVSS. 

I've had exactly the same problem with 2 of my 8s planes where i wanted to run 2 of the MLVSS (because I've got heaps of the mini sensors and not many of the FLVSS) and I ended up having to use one of each or two of the FLVSS. Have a look at the Manuel right at the bottom of the last page and it tells you very clearly you cannot use two of them together 

https://www.frsky-rc.com/wp-content/uploads/Downloads/Manual/Mlvss/MLVSS%20-Manual.pdf

Just trying to save you some pain because I know it worked at one time but it doesn't any more. I don't know what they did to change it but I've had issues since last year with the very same issue and ended up replacing all my sensors.

Hope this helps 👍

**Comment by craigywsm** [comment]
This is still an issue with 1.4.11

**Comment by yak-54** [comment]
don't know will have get the plane down

**Comment by yak-54** [comment]
OK just got down the plane yes it is 1.4.11

**Comment by yak-54** [comment]
> You cant use two MLVSS sensors together on the same telemetry loop, because for a long time now we have not been able to change the channel ID of them. With the FLVSS you can, but not with MLVSS.
> 
> I've had exactly the same problem with 2 of my 8s planes (and a pair of 4s ones running 2x 4s lipo) where i wanted to run 2 of the MLVSS (because I had heaps of the mini sensors and not many of the FLVSS) and I ended up having to use one of each or two of the FLVSS. Have a look at the Manual right at the bottom of the last page and it tells you very clearly you cannot use two of them together
> 
> https://www.frsky-rc.com/wp-content/uploads/Downloads/Manual/Mlvss/MLVSS%20-Manual.pdf
> 
> Just trying to save you some pain because I know it worked at one time but it doesn't any more. I don't know what they did to change it but I've had issues since last year with the very same issue and ended up replacing all my sensors.
> 
> Hope this helps 👍

i use 2 x 2S

**Comment by yak-54** [comment]
still the same on 1.4.12 if i use more that one MLVSS

**Comment by builda1** [comment]
> still the same on 1.4.12 if i use  MLVSS

Dude, I told you last time you Cannot use 2x MLVSS together because they changed the firmware in 2017. I believe it was, you can use 2x FLVSS, or 1xMLVSS and 1xFLVSS but you CAN NOT use 2xMLVSS (the Mini one) together. 

Originally you could years ago But Frsky changed the firmware on the sensors years ago now and if you try to use two of them, you will get a sensor conflict, changing the sensor ID number etc won't make any difference. You will consistently get a conflict because it is a firmware issue. If you don't believe me send an email direct to the following Tech support at Frsky in China: 

longxiang.xu@frsky-rc.com

His other Email is: 
sales4tech@gmail.com

This is the head technical guy at  Frsky in China ok, he will tell you exactly the same thing. I've just told you! I had to find out myself because I've got a number of 8S planes with 2x 4500 4s lipos in plus a bunch of Flightline ones with 2x 4S batteries in and I had exactly the same problem I spent probably the best part of a week trying to figure out why it wouldn't work in the end I emailed one of my good friends at Frsky in china and they told me to ask the tech service guy whose email I gave you above. 

He told me very clearly that I would never get two of them to work together, unless I could find a pair that had the old firmware on (pre-2017) because they changed the firmware at that time and the change removed the ability to use two of them together. I did not ask, but I am guessing it is probably about the time they brought out the FLVSS hence they wanted people to use them instead. 

I've tried to help you twice now and save you a lot of pain , just get one of each and you will be fine (FLVSS and MLVSS) or 2x FLVSS, but you absolutely cannot use 2xMLVSS you will go crazy trying to get it to work I can assure you I spent almost a week and I gave up after hours of frustration only to find out it wouldn't work anyway! 

Like I said, if you don't believe me send an email to the above email address and you will get the answer you seek. It is not a receiver firmware issue It is a SENSOR firmware issue.👍

**Comment by builda1** [comment]
You can even read it in the manual that you CAN NOT use more than one MLVSS in a telemetry loop! 

https://www.frsky-rc.com/wp-content/uploads/Downloads/Manual/Mlvss/MLVSS%20-Manual.pdf

**Comment by builda1** [comment]
> You can even read it in the manual that you CAN NOT use more than one MLVSS in a telemetry loop! 
> 
> https://www.frsky-rc.com/wp-content/uploads/Downloads/Manual/Mlvss/MLVSS%20-Manual.pdf
> 
> The very last thing it says in the manual is: 
> 
> "Notice: FrSky Smart Port Mini Lipo Voltage Sensor can meansure from 2S to 6S. Combine two FrSky Smart Port Mini Lipo Voltage Sensors to measure more than 6S is not supported." 
> 
> 

See, "IS NOT SUPPORTED" 👍

**Comment by yak-54** [comment]
they work fine its just bitching all the time 
i use 1xMLVSS and 1xFLVSS same issue even if i just use one MLVSS i cant use MLVSS or more  with out it bitchin 
and using 1 x 4s and 1 x 2s  battery 
AND IT WORKS FINE UNDER EDGETX

**Comment by builda1** [comment]
> > its working but she is always nagging   sensor conflict
> > 
> > 
> > 
> > ![screenshot-2023-03-18-33741](https://user-images.githubusercontent.com/9161926/226064342-e5d66ab6-d043-473a-a471-8c3ed48874fb.jpg)
> > 
> > ![screenshot-2023-03-18-33756](https://user-images.githubusercontent.com/9161926/226064347-8be774a1-21b2-4fe4-b6f9-c33170ea79c2.jpg)
> > 
> > ![screenshot-2023-03-18-33769](https://user-images.githubusercontent.com/9161926/226064348-7427a72f-6271-4b65-8e6c-57a7de5ac555.jpg)
> > 
> > ![screenshot-2023-03-18-33785](https://user-images.githubusercontent.com/9161926/226064350-4e0abc5b-1e46-4091-b059-fa50421658f1.jpg)
> > 
> > 
> 
> I had the very same problem recently with my Flightline liberator, I literally had to individually detect the MLVSS sensors connected one at a time to the receiver, then change the channel ID for one of them. Took me a bit to get it to sort it self out, but it works now. The one thing I did find that I couldn't fix Though was that when I was configuring the screen, it would only let me select 1 Lipo sensor (it wouldn't let me select a second one for a different field in the same screen..... or so I thought! I found on certain screen layout it would work and others it wouldn't. 



As I said and showed earlier, this is how I got to work in ethos. You can only change the ID for the FLVSS and have it accept the change from memory-it was quite awhile ago when I set it up, but it still works to this day. Send an email to the email address I gave you before and you will get a response from China if you use the "Sales4Tech@gmail.com" one he answers a lot quicker. 👍

**Comment by bsongis-frsky** [comment]
EdgeTX / OpenTX don't check the sensor conflicts. Do you succeed to change the AppID / PhysId of your sensors? If they are different everything should work fine!

**Comment by craigywsm** [comment]
> EdgeTX / OpenTX don't check the sensor conflicts. Do you succeed to change the AppID / PhysId of your sensors? If they are different everything should work fine!

Hi @bsongis-frsky I have and RB20 with two R8RPRO's 
I also have a telemetry sensor from [Lior Zahavi](https://www.linkedin.com/in/lior-zahavi-48b18983/overlay/about-this-profile/)
I have checked all of the AppID/ Physical ID of all telemetry items and they are all different,
I get sensor conflict when I first switch on the model. I only get it once but I do get it every time.
If I then unplug the Sport connector to the Zavionics sensor then I do not get sensor conflict. (even though I did not remove the sensors from the telemetry screen)
It does seem to me like there is an issue with additional S port devices causing a conflict.
Please let me know if you need any further information
Kind Regards
Craig

**Comment by yak-54** [comment]
> EdgeTX / OpenTX don't check the sensor conflicts. Do you succeed to change the AppID / PhysId of your sensors? If they are different everything should work fine!

I have change the ID with an servo ID changer  and if I trie to change app I’d the radio freezes on device screen have to power radio off and restart it

**Comment by bsongis-frsky** [comment]
On which radio? Horus? Or X20S? Just to know if the radio freezes, or if only the focus is lost and you cannot do anything. Are you able to power the radio off with the button, or you have to remove the battery (really a freeze!)

**Comment by yak-54** [comment]
the horrible horus X12S :) 
yes i can power it off
 i can't exit out of device config menu after i try to change the Physical ID    that menu no buttons work 
what ever it is doing when i do get it to change app id something is changing the app ID back to 0300 app ID

**Comment by yak-54** [comment]
Mlvss 1  
![screenshot-2023-10-17-38523](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/e4766584-f85e-4661-8ff4-6418a87a6812)
![screenshot-2023-10-17-38538](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/19128020-0ede-4b1c-9fbb-af53f99c53ab)

**Comment by yak-54** [comment]
Mlvss 2 is on 4S battery
telemetry sensor edit page as you can see the app ID has been changed back to 0300
![screenshot-2023-10-17-39787](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9161926/fed5ea76-a9a3-49d7-b346-cd693175ea6d)

**Comment by craigywsm** [comment]
Still an issue

**Comment by dWoolridge** [comment]
Sounds nearly identical to my issue #3614 in 1.5.1 (and later) that has been stuck in "Information Needed" land.

**Comment by yak-54** [comment]
yep and i still have this issue

**Comment by dWoolridge** [comment]
Have you (yak-54) flown any aircraft with this issue?  I'm guessing that telemetry reading problems at the Transmitter wouldn't be very likely to cause control problems, but anything is possible.

So... I'm wondering how much flight testing has been done with this Sensor Conflict issue active.  I'm under the impression that FrSky is relying on it's customers to do the final system testing for them.

**Comment by dWoolridge** [comment]
See my latest findings for FrSky in my Issue #3614.  Hopefully this issue will start to get back on FrSky's radar.
