### ISSUE TITLE
My X18SE is not recognized by my PC under Windows 7.0

### ISSUE THREAD

**Issue by Lleston2** [FrSkyRC/ETHOS-Feedback-Community#2535]
Hi Guys,

 I upgraded to ETHOS 1.4.7 and now the radio is not recognized by Realflight 9.5S. The USB driver is not executed when I plug the radio in

I am using windows 7. It was working just before I upgraded from 1.4.6 to 1.4.7.

Please let me know if you need something else.

**Comment by strgaltdel** [comment]
I was finally able to find an old Win7 PC at the company before it was to be scrapped.

I installed Suite 1.4.6 and was able to connect to an X18se.
Then I upgraded to 1.4.7 and everything worked fine.

![grafik](https://user-images.githubusercontent.com/20392683/227184277-f5c5e7e0-2901-4d1b-ac2b-118fc9959a33.png)


So I am pretty sure that the problem is not caused by a systematic Suite problem, but that the root cause has something to do with your Win7 environment.

I would therefore suggest that in such a case you apply the typical procedure as investigations of

- device manager stati
- event logs
- reinstall some USB drivers etc..


was your X18 fully upgraded?
If not i would try a manual approach & try if Suite can reconnect.
