### ISSUE TITLE
Editing existing models is uncomfortable

### ISSUE THREAD

**Issue by NorbertHeli** [FrSkyRC/ETHOS-Feedback-Community#2539]
I love ETHOS, but one thing bothers me every time I want to create a new model from existing models:

1) There is no PC Editor like Compagnion for ETHOS
2) When I do the programming in the transmitter, I can only clone one line - change the model and paste it there - and change the model again and so on

Since I fly complex glider models, I have many flight phases, curves and compensations

For OLC competitions I use the SM GPS logger, in addition to the telemetry values known to ETHOS, 8 DIY values have to be adjusted and some telemetry values converted in a new line

20 logic switches and 25 special function for OLC navigation that need to be adjusted

Therefore I ask you to make the programming editable on the PC (it is best to copy entire blocks of 2 to n lines)
Or to clone whole blocks (2 - n lines) in the transmitter.

That would make the time-consuming programming much easier

**Comment by NorbertHeli** [comment]
Thats not only concerns suite - also ETHOS on my transmitter
The most importend point is to select more than one line, not line for line. Maybe a full category - like log switches or kurves and so on.

So I can fast assemble from existing modells a new one and than adapt it.

**Comment by Target0815** [comment]
The problem would be none if the model configuration was not stored in a binary file but as with EdgeTX in a readable text file.

@mawzthefinn please remove suite label, mainly it concerns the transmitter themselves ...

**Comment by NorbertHeli** [comment]
I mine both

An editor in suite with the possibility to select 1 or more lines or the complete block to move/copy/clone/delete

and at the Transmitter also the possibility to select 1 or more lines or the complete block to move/copy/clone/delete

**Comment by strgaltdel** [comment]
more or less, in case the functionality to edit a model within the suite app would be available, 
"the issue" on tx side would have gone.

i, like others, would like to see a win based App as soon as possible, but i dont expect it within weeks (or a few months).
too much other open issues and i guess some hw adoptions "in the queue"

nevertheless, even there is no eta,
would be nice to see something like a rough roadmap when it will happen if planned.

**Comment by mawzthefinn** [comment]
> The problem would be none if the model configuration was not stored in a binary file but as with EdgeTX in a readable text file.
> 
> @mawzthefinn please remove suite label, mainly it concerns the transmitter themselves ...

The request is for either Suite editing or multi-line copy/paste in ETHOS. The former will arrive first as far as I'm aware, which is why this is labelled Suite.

**Comment by NorbertHeli** [comment]
Not really, a essential part is, that its possible to select more than 1 line, at suite and at ETHOS.
Selection only 1 line was also at compagnion a disadvantage.
Of course I where happy, when easy editing is anywhere  possible.

**Comment by mawzthefinn** [comment]
> Adding model editing to the Ethos suite is really key to acceptance and uptake for the OS.
> I love what Ihave seen so far but it needs to be far more easily used bby a non technical user.and ETA on this enhancement to the softwwre at all please?

As a note - my experience from OpenTX is that non-technical users won't even notice whether or not model editing is available in suite. They will do just about everything in the radio regardless of what radio they use, and they don't want to muck about on a computer.

More technical users are the ones who want editing in suite, to make more complex programming easier to do thanks to cut & paste and a better keyboard.

I demo ETHOS regularly to all sorts of users, the only ones who ask about PC editing are advanced users. 

Regardless, editing in Suite will be a major enhancement for ETHOS.

**Comment by Luznatural** [comment]
Please, maintain this issue open or will never happens.

**Comment by afdofdez** [comment]
It seems essential to me to have a model editor for Ethos on the PC.

**Comment by rcgecko** [comment]
A model editor is a definite plus for Open TX. Yes editing on Ethos is a lot easier then Open TX BUT it is even easier to work with models on a PC, especially for us 'older gents' :)
Please consider it to be a very very needed update to the Ethos brand.

**Comment by zvikaf** [comment]
wonder, there is "edit" lable on the companion, not workable :-(

**Comment by Nerenye** [comment]
Can we please open this again or is there another ticket regarding this?

**Comment by Nerenye** [comment]
@bsongis is a feature like this still planed?

**Comment by bsongis-frsky** [comment]
Yes of course this is planned for this year, but it's a lot of work. It will come little after little.
Our priority goes to 1.5.0 right now, to make it as stable as 1.4.X, as soon as possible.
Then we will work more seriously on big Ethos Suite improvements.

**Comment by bsongis-frsky** [comment]
No need to reopen the issue, we have it in mind, it's impossible to forget :)

**Comment by Nerenye** [comment]
Thank you

**Comment by MRPCBD** [comment]
Has any progress been made on the ETHOS PC Based model editor?  Why is the model edit function disabled in ETHOS Suit?
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6187041/7f485e2d-1b53-42c7-b4b2-b9b26d27e3b4)

**Comment by Nerenye** [comment]
@bsongis-frsky Year is almost over. Any news on this? you said it was planed for this year. a companion like editor is still badly missed

**Comment by afdofdez** [comment]
Ehos development has reached a point where it is unjustifiable, in my
opinion, that there is no model editor on the PC.

Greetings.

**Comment by NorbertHeli** [comment]
Can´t agree, maybe at simple modells, yes. But on sailplanes not, they are very complex. My helis and motorplane easy, 1 hour.

BUT: To compare models, transfer function from one model to another  or find errors on the Tx, a very boring task.
I own ~ 40 modells and fly about 10, because I don´t like to transfer the programming from OTx to ETHOS.
Some gays at my local club move to ETHOS ( newer Tx ), as long as no companion ( modeleditor ) is available.

It not possible to show or print the whole model with progamming, spezial funktion, virtual and real switches and so on.

**Comment by Nerenye** [comment]
> Can´t agree, maybe at simple modells, yes. But on sailplanes not, they are very complex. My helis and motorplane easy, 1 hour.
> 
> BUT: To compare models, transfer function from one model to another or find errors on the Tx, a very boring task. I own ~ 40 modells and fly about 10, because I don´t like to transfer the programming from OTx to ETHOS. Some gays at my local club move to ETHOS ( newer Tx ), as long as no companion ( modeleditor ) is available.
> 
> It not possible to show or print the whole model with progamming, spezial funktion, virtual and real switches and so on.

With what you can`t agree? afdofdez is saying a Editor is needed?

**Comment by NorbertHeli** [comment]
Sorry, did misinterpret it - yes it´s nessersary

**Comment by fredz2005** [comment]
I'm a member of a large flying club in SF Bay area..  Approx 85% of the members use Spektrum.   70% of the Spektrum users have no interest (or skills) to do any customization.  The model setup macros in Ethos attracts some of those users who enjoy modeling but can't/won't customize a model file.    Of course it's madding for the rest of FrSky's customers that FrSkyEthos prioritize development for the first group.   They waste time on little used features like BT model file transfer but can't provide a simple export utility so you can print out a program and MANUALLY copy complex LSw or SF between models.   As of 5/12/25 the copy/paste function doesn't work on SF and vars.   "Do it in the simulator."   Where is the user manual for the simulator?   Is there a set-up article for the simulator?   We need an editor.

**Comment by bsongis** [comment]
Spektrum has such an editor?

**Comment by fredz2005** [comment]
I don't use Spektrum.  I don't know if they have a PC based program editor.   My consistent experience flying with Spektrum users is many are not interested (or unable) to customize model programs, less interest in customizing the transmitter system (telemetry dashboard as example).    They bought Spektrum because its reliable and least complicated choice.   Many are expert RC pilots but don't use features that could prevent crashes, like monitoring RSSI or the receiver battery voltage.

The tension at FrSkyEthos is they have two incompatible objectives:  on the one hand, create an even simpler system to configure:  model setup wizard, automate FW updates, file BU, large library of templates.   Convert some Spektrum users to FrSky.    On the other hand, continue to introduce even more complicated products: TW, dual, stabilized receivers, all interesting, useful technology.

Simplification is good, but some tasks can't be simplified, each model is different, you need to edit the model program, it changes over time.   And you can't automate set-up of complex systemVar, LSw and SF.   Most of my model programs have a dozen SFs.   There is currently no way to move these scripts between models.   We need an editor of some kind.   The need for an editor wasn't clear to me until I had five models in Ethos and needed to make updates to each.   Cloning isn't a solution, its editing once the model program is created.

**Comment by NorbertHeli** [comment]
My view on this topic:
Helicopters and powered aircraft are easy to program with the transmitter because they're not particularly complex.
In contrast, my gliders, which I fly in OLC (offline competition), have approximately 25 special functions and just as many local switches to evaluate, announce, and display direction, altitude, and distance.
When regulations change, all of them have to be changed and adapted. This is time-consuming and error-prone.
Therefore, it would be useful to be able to copy entire packages of lines, not just individual lines.
As well as a simple overview of the program lines for comparison.
We have several pilots in the club who won't switch from OTx to ETHOS until an editor is available. They're even buying old Taranis to have spares.

**Comment by Nerenye** [comment]
Whats that discussion even about. A Editor was promissed for last year.  
I like Ethos but if that is not a feature for this year i'm moving on to edgeTx.
Its a real hadache to programm gliders and not be able to easily edit the planes on a Opentx like editor.

**Comment by bsongis** [comment]
This editor inside Ethos Suit is in our roadmap.
I still don't understand what is the relation with Spektrum users, they don't have such an editor for now
I think only OpenTX / EdgeTX have it.

**Comment by strgaltdel** [comment]
I was a long-time OpenTX user and know the benefits of a Companion program all too well.
I also had serious concerns about Ethos usability as a "heavy-duty" user.

However, after several years of using Ethos, most of those concerns have largely disappeared.
Yes, an editor/companion can also make life easier under Ethos.
But to claim that Ethos is hard to use for beginners because of its range of functions is simply not true.
That view ignores the advantages Ethos offers over competing systems.

In my opinion, it's not a new insight that the majority of RC pilots don’t want to deal much with transmitter configuration — they just want to get flying, quickly!
These are typically also the users who make only minimal fine-tuning or trimming adjustments to their models and, due to lack of experience, frequently ask where and how things can be configured.

Such users always face difficulties when switching from a familiar System A to a new System B — no matter the brand.
That’s not meant as criticism — these users often have other strengths, but PC knowledge or transmitter programming is generally not one of them.

My recommendation for such users is to make use of certain "trump cards" that Ethos offers:

- Ethos provides excellent setup wizards for quickly and easily creating standard models — use them!

- Think about which parameters (e.g., rates, expo, differential) are commonly adjusted, and set those up as variables (vars).

- Define personal standards that apply across all models (e.g., which switch controls what, consistent naming of vars, etc.).

- Avoid trying to build a perfect template immediately — instead, take time to understand the logic and structure of the user interface.

- Create a reference list of which mixers perform which functions and what parameters they expose — this helps later when choosing the best option for each use case.

- And most importantly: Don’t try to do everything at once.


The result:
Models of the same type don’t need to be created from scratch — copying an existing model and making adjustments is much faster.

Thanks to the almost unlimited number of vars, most configuration can be handled through them.
The classic question "Where do I adjust this in the mixer?" becomes obsolete.

From my experience, planning ahead, using standards, and relying on vars can significantly reduce the "need" for a Companion.
Ironically, the users who are not PC-savvy often didn’t use the Companion much in OpenTX either.
Ethos actually makes things easier for them in many ways.



**That said, yes, a PC editor is a great thing, especially for IT-savvy frequent users.
From a competitiveness and messaging/branding perspective, to be seen as a leader in software development, it’s a must-have.
But in my personal opinion, bringing average users on board with Ethos can be achieved more effectively by other means.**

**Comment by fredz2005** [comment]
"I still don't understand what is the relation with Spektrum users, they don't have such an editor for now"

Looking at the shape and content of Ethos/EthosSuite, Spektrum users appear to be your target market.   I think it's a misguided strategy.   Spektrum will probably never release a PC based editor because the average Spektrum user isn't interested.  Spektrum users are not FrSky's target market.   Yet FrSkyEthos is spending development resources to simplify the UI and maintenance tasks.   Why do this?   Its NOT to attract FrSky ETX or OTX users, technically savvy users.  You are trying to take market share from Spektrum and in the process creating a barrier to adoption within existing FrSky users (OTX/ETX).

I belong to a RC club with 250 members, maybe 10 FrSky users, 15 RadioMaster.   The rest are Spektrum.   Please understand, they never moving to FrSky because they don't understand (not interested) in programing their Spektrum transmitters and they have $2K-$4K already invested in Spektrum.

FrSky has a history of abandoning customers.   The current missteps/omissions on Ethos are disappointing.   Concurrently FrSky has dropped the ball entirely on OTX support of SRx receivers, the LUA config scrips don't work.   If some of us sound annoyed, there are good reasons.

I bought the X20R.   Please release an editor so I can efficiently develop and manage my model pgms and I'll take another look at Ethos.

**Comment by kochpet** [comment]
I don't understand Frsky's strategy. A model editor was promised with the initial launch of the Tandem X20 series, but years later, it still doesn't exist. To configure very complex models and utilize all the capabilities of the new transmitters, a model editor as clear as the EdgeTX Companion would be very helpful, and I believe Frsky would benefit from this approach for many advanced users.

**Comment by kochpet** [comment]
@bsongis 
> This editor inside Ethos Suit is in our roadmap.

Hello, it's nice to hear that the editor is still on the agenda, but does the roadmap also have a timeline? When can we expect to see the first version of a model editor?
