### ISSUE TITLE
Remove or disable default value of a VAR (global variable)

### ISSUE THREAD

**Issue by fhpage** [FrSkyRC/ETHOS-Feedback-Community#2541]
If one could remove or disable the default value of a VAR, then the action source (like a trim switch) could be repurposed in a normal mix.
Am also assuming that at some point the order of the VARs will establish a precedent for the actions. As of 3/23 nightly if the actions are the same (i.e. same trim switch) in several vars, all the values for same var criteria change.

**Comment by mawzthefinn** [comment]
Default value will be changed by the action, use the VAR itself as the value in the normal mix and you can adjust. 


No precedent is intended. The ability to adjust multiple VAR's via identical actions is intentional as per #2483

**Comment by fhpage** [comment]
I see now that one can use a "source" as a value as well as using "actions". So can force a non changeable default value. Can understand wanting to change two vars at the same time in a script, but this causes limitations. Use mixes to do that. If there is no plan to have precedence in the VARs order(as OpenTX in special functions), why can one change their order? The only way to multipurpose a switch as an action in Vars would be to have complicated logical switches. Also the use of a switch in a VAR, when active, does not preempt it's use in a Mix (OpenTX again). One is constrained by the number of (trim) switches.  As it stands, Vars bring no added value over using Trims.

**Comment by mawzthefinn** [comment]
VAR Actions override the default assignment of trimmers, the trimmer is either doing its default assignment or the action, not both at the same time. 

Precedence was originally planned for VAR actions (notably last activated, not highest in the stack), but the discussion in #2483 led to that being removed. 

As of right now you can override trimmer assignments using VAR's, but if two VAR actions are active at the same time and use the same overloaded trimmer, both will adjust, to allow for the use case described in #2483 

You can still have one trim doing multiple independent items in VAR's, so long as you program the active conditions so that only one can be active at a time in the VAR's.

You are not constrained in any way by the number of trim switches when using VAR overloading. VAR's also allow multiple trimmer-adjusted persistent values that are not selected by FM (trimmers only allow per-FM value independence when used directly).

**Comment by fhpage** [comment]
I created a Var using elevator trim switch, T2, for the action. Used T2 in a Trims Mix. Both were active at the same time.
Same case when using the "Airplane" category similar Var configuration. 
Was done with X18SE and today's nightly. Is it yet to be done or am I mis-understanding.

**Comment by mawzthefinn** [comment]
Interesting, that's a definite bug. I'm seeing a few trim clicks before it switches from trim to var adjusting.

**Comment by fhpage** [comment]
My original goal was to be able to repurpose a trim switch both within Mixes and Vars. Simply having Vars adjustment prioritized by order of the Var listing, as they are currently defined, would not have worked. If the "Actions" in a Var had a "Switch" (OpenTX special functions terminology) then (I believe) trim switches could be repurposed (or multipurposed) within Var definitions.

**Comment by mawzthefinn** [comment]
Active condition is the equivalent to the switch in OpenTX (except somewhat more flexible). You can repurpose the trimmer as many times as you want, so long as you accept that if multiple VAR's have actions that are true for that trimmer, it will adjust more than one var. Switch worked the same way anyways. 

What you are describing is already possible with the VAR's, so long as you wait 3S before adjusting the trimmer (the 3S delay is a repeat-related bug which has been identified due to this conversation, it's not fixed as if this morning).
