### ISSUE TITLE
Funtion Switches as Input on Mixer Page

### ISSUE THREAD

**Issue by Amahoser** [FrSkyRC/ETHOS-Feedback-Community#2544]
Looks like Function Switches cannot be used as an input when setting up a mix. I changed the function switches to be 2x 3 Pos Switches and I would like to use them the same as a regular switch as an input source.

**Comment by mawzthefinn** [comment]
Function Switches work more like logic switches due to their varying different setups, so they don't have an analog value, just true/false for each one.

The answer to using them as an input is to create a VAR mixer and using the function switches to select values, with the VAR mixer outputting to an unused high channel (I start with Ch64 and count down) then use the channel the VAR mixer outputs on as the source for your regular mix.

With 1.5.0 this will eb even easier, as the new VAR system allows you to directly assign the Var as a source rather than using up a channel.

**Comment by mawzthefinn** [comment]
Closing off as solution provided
