### ISSUE TITLE
Ethos Image Tool - Destination Path Does Not Exist

### ISSUE THREAD

**Issue by RSmith13141** [FrSkyRC/ETHOS-Feedback-Community#2576]
I am using Ethos Suite 1.4.8 and Bootloader 1.4.3.   I am in the image tool to load some model images (.png files).   I can add the png files to the image tool no problem.  When I select the output path to the X20S SD card and press Convert, I get a error that reads "Destination Path Does Not Exist!".   So then I tried to convert them to any folder on my desktop and got the same error.  It seems I cannot successfully specify and output path.  I am using Ethos Suite on a MacBook Air.
<img width="1369" alt="Screenshot 2023-04-11 at 7 28 32 AM" src="https://user-images.githubusercontent.com/130477983/231195342-ea5388f1-92aa-492e-9c54-1c5ca41c10e0.png">

**Comment by M0j0Risin** [comment]
I've noticed the same thing in the audio tool.  I know it worked fine in the previous version. My guess is that something changed surrounding the way it references these paths in the GUI.  Not a huge deal since I can just convert audio files and images in other apps, but it's definitely something that used to work that doesn't now.

**Comment by Nicholas-Luoyi** [comment]
It is an issue. It has been fixed and reuploaded now.

**Comment by M0j0Risin** [comment]
> It is an issue. It has been fixed and reuploaded now.

Thank you very much for the quick response.

**Comment by RSmith13141** [comment]
Thanks so much!  That was a really fast response.
