### ISSUE TITLE
RB 25 Failsafe setting suggestion.

### ISSUE THREAD

**Issue by DanPesonen** [FrSkyRC/ETHOS-Feedback-Community#2605]
The failsafe defaults all channels 988us. So surfaces were pegged all over the place. Would have made for a spectaular crash. Should default 1500us really, I think. Setting failsafe in TX had zero affect on the RB25 failsafe as well.   I have a Horus, so no manual typing values.  Took a lot of scrolling.   

One thing that would be handy in the LUA, is setting the Failsafe uS via output channels present outputs. I set my centers by PPM center for every channel, Subtrim stays 0. A one button "copy/paste" function in the script to take all outputs PPM uS at time of pressing, and copy to RB25 failsafe would save a ton of time.
ie, Set plane up, Match all servos etc etc. Then hold sticks in position you want for failsafe, (I like Aile centered, just a touch UP elev) Then hit the "copy sticks position" button 
Thanks for considering

**Comment by petermumford** [comment]
Wowzers - had no idea the RB-25 would do this. Sat failsafe as usual, turned the TX off followed by many cracks and linkages breaking. Please can this be done better asap. If possible include a warning when using an RB25/35 as I’m sure this will catch a lot of people out.

**Comment by DanPesonen** [comment]
Has this been addressed?  Fail safe should default 1500 I think

**Comment by juans-stripe** [comment]
Big +1 on this. The flight-safe system devices are usually meant for bigger/more expensive planes, but the failsafe defaults and configuration options are lagging way behind what FrSky (or any other brand) receivers offer (lack of hold, manually copy pasting pwm values...)

**Comment by mgsanna** [comment]
should be solved via new Lua script... and also the choice between "ignore" "hold" "no impulse" and "normal 890 to 2110 ms
it's really important to solve this for the real use of the RB25/RB25S RB35/RB35S

with "old" RB30 and RB30+ failsafe work permitting to user to decide how to setup

**Comment by RMM83** [comment]
Adding my use case, I don't use ETHOS, I have a Radiomaster TX16s running EdgeTX, and since there was no warning about this issue in the documentation I assumed that the RB-25 default would be "ignore" or default values at 1500.

I have a RB-40 that I can set up with no issues with the EdgeTX/OpenTX LUA scripts and that also provided me confidence to buy a RB-25.
I understand that ETHOS LUA scripts have now more priority, but before releasing the EdgeTX/OpenTX LUA scripts (if ever) a good workaround will be to implement "ignore" by default in the next firmware version or at least the default values at 1500.

The impact for me is a hangar 9 Ultra Stick 30cc waiting for maiden already for 6 months!
