### ISSUE TITLE
No confirmation when deleting telemetry sensors

### ISSUE THREAD

**Issue by lightbulbjim** [FrSkyRC/ETHOS-Feedback-Community#2626]
There is no confirmation when deleting telemetry sensors. It's easy to press delete by accident.

This includes DIY and calculated sensors, which can't be automatically rediscovered.

**Comment by azaz44** [comment]
+1

I would add to that --> I think this function should only delete RX sensors, but keep calculated and DIY sensors. Because this is what you need mostly.

I mean, we don't have functions to "delete all mixers" or "delete all logic switches", so I think we don't need one for "calculated sensors" either.

Deleting RX telemetry counters is however needed sometimes, and I think this was a reason for this function to be there.

**Comment by azaz44** [comment]
Still needed

**Comment by azaz44** [comment]
Still needed

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/2c56c933-1ba6-4ecb-8cd1-5bb2a914d7ed)
