### ISSUE TITLE
Thr->ele mix using inverted throttle stick

### ISSUE THREAD

**Issue by michelkorthout** [FrSkyRC/ETHOS-Feedback-Community#2676]
Version 1.4.8 on an X20S

I have configured the Throttle mix as inverted (-Throttle)

when I add the mix THR->ELE it is not using the inverted throttle input, but the default.

so, when now my throttle is 0% ( stick forwards) the Thr->ele is at max instead of the wanted 0%.

**Comment by lightbulbjim** [comment]
Yes, because the THR -> ELE mix uses the raw throttle stick value as the source, not the throttle channel output. Two ways to achieve what you want:

1. Invert the weight in the THR -> ELE mix.
2. Create your own inputs layer. Make a free mix of the throttle stick to a high channel. Invert this input so the mix output is high when the stick is low. Then use free mixes for your throttle channel and THR -> ELE mix, with the high channel being the input for both.

Option 1 is obviously simpler, but option 2 arguably makes things a bit clearer and more maintainable (to me, anyway 😵‍💫). This is one of the slightly awkward things about Ethos - to do complex things you sometimes have to create your own system.

**Comment by michelkorthout** [comment]
Thanks for the reply, unknown I can solve things using the freemix, but the whole idea about Ethos is to make things easier. Otherwise there was no need to make all kind of default mixes like ail to rudder etc.

in OpenTX I can set an inverted throttle in the general settings, with this the raw value is already inverted.

In my opinion either this option is missing, or the throttle related mixes like thr to ele are missing the option to invert the raw input (

**Comment by 00steven** [comment]
I have said it manny times. Only  futaba has done the throtle reverse thing right. 
Throtle reverse is a global  radio setting and should be with the stickmode settings. Once you have set it it schould be something you never have to think about. No work aroud, no strange reverced negative and positive value's,.... No morre revercing for every model. 

I think this can be done way beter than it is now
