### ISSUE TITLE
Aggregated RSSI and VFR sensors for dual-band receivers

### ISSUE THREAD

**Issue by lightbulbjim** [FrSkyRC/ETHOS-Feedback-Community#2693]
I was performing a range test on a TD R6 today, and I noticed that the VFR warning is announced when either VFR sensor drops below the warning threshold. In this case the 2.4GHz link had a VFR of <50%, but the 900MHz link was still at 100%.

This is a pretty common scenario for TD and TW systems, since there is a large range difference between the FSK and LoRa links. It's not very useful to hear "VFR low" while flying but actually have tons of range left.

For now I've disabled the default VFR warnings and created a calculated VFR sensor which reports the maximum VFR of both links. An alert sounds when this aggregated VFR value drops too low. Would it make sense to configure warnings like this out of the box?

Note that I wouldn't want to lose the two individual VFR sensors. They're very useful when examining logs. But an aggregated sensor is more useful while flying.

All of the above applies to RSSI as well.

Thoughts?

**Comment by Dsrenger** [comment]
+1

**Comment by bsongis-frsky** [comment]
RSSI is already aggregated since a couple of releases. It is working correctly in 1.4.8

VFR is aggregated in 1.4.9, I have worked on it at the end of last week. 1.4.9 is pre-released since yesterday, so I will mark this issue as fixed, unless you did your test on 1.4.9 and there is a mistake somewhere?
