### ISSUE TITLE
X18 fonts still small

### ISSUE THREAD

**Issue by Szonu** [FrSkyRC/ETHOS-Feedback-Community#2718]
Updated ethos and fonts still very small 
Every one I showed it to said there going to keep there tx’s if fonts this small 
Need to be doubled

**Comment by strgaltdel** [comment]
iam still on 1.48

the buddies who were interested in my x18 or ethos in the last few months (old opentx fighters) found the usability very good, criticized rather the lack of a companion app, the character size was desired in some places a little larger, but never was an important criteria.

"snowman" guys were even very impressed

as mentioned on rcg,
most users prefer x18 ergonomics over screen or font size

if there is a possibility of improvement without compromizining ressources for other issues, fine,
but my experience was that this is not the "hottest" issue on ethos /x18

**Comment by lightbulbjim** [comment]
> Need to be doubled

I don't see how it's possible to double the font size without a major UI redesign.

**Comment by bsongis-frsky** [comment]
Any proposal is welcome, I cannot see how we can add more information and in the same time write with a bigger font. We have to do some choice and it won't please all users!

**Comment by Szonu** [comment]
I think there’s already to much info on the screen for the size.  

Could the fonts be increased with less info but scroll or add pages.

**Comment by strgaltdel** [comment]
currently working on a redesign of some of my widgets,
and so grew an idea:

(1)
regarding UI / font sizing in menues:
My experience is, that users , after a few days working on a new UI, tend to know what buttom / field / area triggers what functionality or requires what kind of parameter without the need of reading the explaining text.
so i wouldn't bother to redesign this area. 

(2)
regarding display of informational data, i guess there could be an relatively "easy" way to get more usable space on a x18 display
looking on the standard layout, you see about 20..25% percent is used 
  - (I) for the "page indication" line (points indicate the number of available screens) and the 
  - (I) touch area at the bottom offering icons to jump into the menu tree
  

The indication line could be replaced by info in the topbar  (a text like 1/(3) ;indicates screen  #1 out of three available)

maybe it's my personal muscle memory, but i never used the bottom icons to jump into the menues, the hardkeys are my favorite "navigation tools" 
But i've to admit, this is a very personal decision and i can't judge about the majority of the users


so this is the proposal:

add an entry in models config, so that the user can decide if he want this "touch screen" supporting elements or not.

if user decides "no" in order to get more "free" area, you can add 2..3 widget frame sets which use this freed area (in case widget frame size is not dynamically calculated in existing sets)

So widgets can use more area for bigger fonts or not so compressed info areas


as an example i'll attach a screenshot of a prototype on a x18 sim-screen.
the left widget is the same, 
using identical font & icon size,
but spread linear over a bigger area which supports better readability (yellow frame). 


even without larger fonts it seems to be better readable,
the "classic" widget suffers a bit from the dense display 

![x18 screensize](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/03e8fca4-2a10-47d7-94bf-3c5945be08e5)


BUT
if it can't be done with little effort
I would give priority to other issues
(just my 2 cents)

**Comment by Szonu** [comment]
Sure in the uk there’s not many sales of the x18 as it is. 
 
sure it would appeal to more if something could be done with the fonts. 

Could some of the info be moved so you scroll down to see more info or moved to another page. so less info is on the screen. to make the fonts larger. 
And can the small screens like where switches are selected be increased

**Comment by Target0815** [comment]
Simple solution: mount a Fresnel lens in credit card size with some distance in front of the display.

https://www.amazon.com/-/de/dp/B09FXPMK6T

**Comment by strgaltdel** [comment]
be aware, these are lua widhets developed  by myself,
but yes this widget will support several "pages" within its frame

you can see it on 4:26 in the video
https://youtu.be/vIm0cenvDsw


not finished yet, but i hope i can publish  it in some weeks

**Comment by lightbulbjim** [comment]
> Could some of the info be moved so you scroll down to see more info or moved to another page. so less info is on the screen. to make the fonts larger. And can the small screens like where switches are selected be increased

Can you post some mockups of what you have in mind? Concrete proposals are useful if you want to see change.

**Comment by Szonu** [comment]
Not done any mock-ups yet 

The small pop up screens could be enlarged 
Model select screen could show less models across so could be enlarged and scroll down to see more models 
The first mixer has space to make txt in lines larger 
on the mixer edit screen the x could be removed so txt on same line could be stretched and enlarged 
Then scroll down to see more   

The value in curve screen is small. 

Show less channels on output screen so could be  enlarged and scroll to see more. 

Think the layout is very good just to much info on screen at once. 
And some txt just small even if there’s room.

**Comment by lightbulbjim** [comment]
I think some mockups would be useful.

Just my opinion: I'm happy to increase font sizes but not at the expense of lower information density or more scrolling. Already with the font bump mixer fields etc are sometimes truncated on the X18. I certainly wouldn't want fewer models per model select page or fewer channels per output page.

**Comment by Szonu** [comment]
Didn’t want a lot less models on select screen just 4 wide instead of 5.  

On first mixer page the graph could be removed freeing up space.  

Then  edit mixer screen graph could be removed and text under it is so small.  

 Then could have option to  pull up a screen like this with slightly smaller graph for weights and expo like the curve edit screen. 
 
The pop up screens like where you conform model and screen where select edit add mix move could easily be made bigger.  
thanks for looking into this 

How do I do mock ups. You  must 
![BBF28B29-3894-431B-BACE-A7159CF78E9D](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/132134599/aa06a2c0-ff1f-4579-ae2f-752e8cd62e77)
![F592C1BD-200E-4263-BAB6-855499720F1A](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/132134599/33567cfa-3d07-4452-8b0e-559c529e1e03)
have much more knowledge how to improve your software. than me. 
 
Sure some are happy as is but what about the people who want to buy and put of by fonts. 
fairly sure sales have stalled in uk.

**Comment by lightbulbjim** [comment]
I have no affiliation with FrSky by the way, I'm just another user like you.

**Comment by Szonu** [comment]
Ok
With the last update is that as large as fonts can be without redoing the ui.

**Comment by Szonu** [comment]
Maybe frsky are not interested in sales  
There’s hundreds of members at my clubs and I am the only one with an x18. 
there’s no interest with the ui as it is. 

they seem to be more interested in releasing lots of new untested products.

**Comment by andika207** [comment]
@Szonu I know you wished something like this with large buttons and fonts

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/NGkmdQtD/aaaaaaa.jpg' border='0' alt='aaaaaaa'/></a><br /><a href='https://postimages.org/'></a><br />

**Comment by andika207** [comment]
>  There’s hundreds of members at my clubs and I am the only one with an x18. there’s no interest with the ui as it is.


@Szonu don't hold your breath because the UI won't be enhanced, as they want it to be hybrid (not 100% touch) because of the old crap that should have been discontinued long since
I suggested some visual theme ideas to make it look simpler and more intuitive but was ignored

**Comment by Szonu** [comment]
Fonts don’t need to be as large as that just a bit more. 
I see no one is assigned to this  
If frsky fully tested products before release  
Would have more time to finish things. 
looks like ethos always trying to catch up.

**Comment by dsolaray** [comment]
> they seem to be more interested in releasing lots of new untested products.

Take a close-up look at the newly released X18RS fonts which look smaller than the fonts displayed on the old X18 
This is getting worse LOL

![screen](https://github.com/user-attachments/assets/013efcab-db20-4ee6-9c30-2abc614a784c)

**Comment by mrdhhall** [comment]
> > they seem to be more interested in releasing lots of new untested products.
> 
> Take a close-up look at the newly released X18RS fonts which look smaller than the fonts displayed on the old X18 This is getting worse LOL
> 
> ![screen](https://github.com/user-attachments/assets/013efcab-db20-4ee6-9c30-2abc614a784c)

**Comment by mrdhhall** [comment]
Absolutely agree with this I'm going back to my X18SE and selling my newer X18RS I hate the fact you can't read the screen as easy 😞

**Comment by bsongis** [comment]
Fonts have been enlarged in 1.7.0
Look at the nightlies, or the online simulator!

**Comment by mrdhhall** [comment]
Oh wow thank you so much for letting me know really appreciate the
information...when will the official 1.7.0 be released?
Dave

**Comment by bsongis** [comment]
That I still don't know but for sure when the VX10 is out as it really needs Ethos 1.7.0
VX10 has the same LCD than X18R(S)

**Comment by mrdhhall** [comment]
Ahh brilliant great to know it's being addressed 👍
It feels like a step back when I look at both screens especially with
having to wear glasses with the newer X18RS

**Comment by andika207** [comment]
> VX10 has the same LCD than X18R(S)

What is VX10 ?

**Comment by dsolaray** [comment]
> I'm going back to my X18SE and selling my newer X18RS

The S series has been discontinued in order to inflate the price of the RS series.
it's better to snag an external Twin module than using the internal crap with limited power output
