### ISSUE TITLE
Checklist 'Load all ... positions' is inconsistent 

### ISSUE THREAD

**Issue by Jedsters** [FrSkyRC/ETHOS-Feedback-Community#2759]
In the checklist 

For switches, 'Load all switches positions' (I believe that should be 'Load all **switch** positions') over-rides all existing settings with the switch positions. Even No check is over-ridden.

For Funtion switches, 'Load all function switches spositions' (I believe that should be 'Load all function **switch** positions') over-rides all existing settings with the function switch positions. Even No check is over-ridden.

For Pots / Sliders, 'Load all pots positions' (I believe that should be 'Load all **pot** positions') over-rides existing settings with the pot and slider positions except when No check is specified.

The above is inconsistent. No check should either be ignored in all cases or honoured in all cases. 
(I think I'm in favour of honouring No check otherwise it could be very tedious keep having to reset them to No check if you want to change a some switches but ignore some.)

1.5.0 Nightly Jul 15 2023
Thanks

**Comment by bsongis-frsky** [comment]
"No check" will be honoured in all cases

**Comment by bsongis-frsky** [comment]
Waiting for Lothar confirmation for the labels

**Comment by lthole** [comment]
As far as the grammar goes, the labels should read:
Load all switch positions
Load all function switch positions
Load all pot positions
The reason is that the nouns ‘switch’, ‘function switch’ and ‘pot’ are being used as adjectives and therefore are not made plural.

I agree that “No Check” should be honoured. If you realise that one or more switches should have a different position at startup, you will want to re-run the “Load all switch positions” without affecting the ones already marked as “No check”.

In this case we are not necessarily loading ‘all’ positions, therefore the final labels become:
Load switch positions
Load function switch positions
Load pot positions

**Comment by bsongis-frsky** [comment]
All confirmation dialogs modified too with the new grammar.

**Comment by Jedsters** [comment]
> The reason is that the nouns ‘switch’, ‘function switch’ and ‘pot’ are being used as adjectives and therefore are not made plural.

I knew it was wrong, but I couldn't have told you why! Thanks!! One of those things you know, but you don't know why.
