### ISSUE TITLE
note "RF" SR6 Failsave Bug

### ISSUE THREAD

**Issue by ingo-RCE** [FrSkyRC/ETHOS-Feedback-Community#2774]
SR6 HW 1.2.0 FW 2.1.12 (settings with X18 FW 1.4.9)
On active Gyro and RX setting "no Impuls", at failsave event all Gyro outputs are active with 1000us Impuls value.
The outher ouputs are deactivated.

I think, an additional setting of an failsave impuls deactivation timeout of user settings are helpful.

The other little mistake are, that on invert an Gyro direction, the RX channel are inverted too.

Thanks

**Comment by mawzthefinn** [comment]
Both are intentional behaviours.

best practice for failsafe on a self-level capable gyro is self-level on, throttle cut and some yaw to generate a wings level circle down behaviour. The gyro can and will continue to function in a failsafe condition to generate this behaviour. 

All FrSky 'S' series receivers have the gyro invert affects channel behaviour. This is why you have to set self-level direction before stick direction when setting up.

**Comment by ingo-RCE** [comment]
I know all settings and use self-level on failsave.
First i check all possible settings of the SR6 and found this bug.

**Comment by mawzthefinn** [comment]
So what aspect of that behaviour is a bug?

ON failsafe, if the gyro is active, it MUST be giving valid PWM output, or it cannot function. 1000ms sounds to me like a configuration issue (no valid failsafe position for ch10/12 because you set No Pulses in the receiver, which has led to the trigger of kinfe-edge or hover mode)

The non-gyro outputs are de-activated because you set no pulses.

Aside from the specific observed output value, what you describe is exactly what I would expect from a correctly functioning SR6 in failsafe.

**Comment by strgaltdel** [comment]
From a users view:

situation (a): 
in case of failsafe, user wants to enable gyro / maintain level flight:
so you can config your Rx to activate gyro (ch10/12), etc..., no Problem:

situation (b)
user prioritizise "no puls", example:
you mainly do "slope flying" and want to avoid heavy current on servos in case of far away out-landings, when grasses or other obstacles causes forces on the flaps after landing.
You switch off tx and servos don't get damaged
i'm pretty sure that's what a user expect when setting "no pulses"

>> using stabi receivers, this is not available by now.

**Comment by mawzthefinn** [comment]
For situation B, a gyro of any sort is unsuitable. If you want your servos to go slack on failsafe, you need to use a setup where that is a valid option. situation A is the functionality you get with a stabilizer in the mix. 

The fundamental issue is that you are expecting the receiver unit to override the gyro unit, but the gyro unit is downstream of the receiver in the control flow. The Gyro receives 'no pulses', but it remains in control of the system. 

The behaviour of the SR6 is as intended in this situation. The behaviour you are experiencing is not a bug, but intended behaviour. I would recommend replacing the SR6 with an R6 if you are in situation B.

**Comment by mawzthefinn** [comment]
The channel decoder is downstream of the receiver unit

Flow is receiver->gyro->decoder

Functionally, the decoder unit is just an SBus->PWM or FBus->PWM decoder attached to the serial receiver section. If a Gyro is present, it sits between the two sections.

Failsafe is set at the receiver, not the decoder.
