### ISSUE TITLE
Return to home function RTH

### ISSUE THREAD

**Issue by Eagleowl1** [FrSkyRC/ETHOS-Feedback-Community#2863]
I was just wondering if it would be possible to integrate an RTH function in ETHOS (GPS and "S" Rx required), a simplified version of the one found in Inav 6.1 FC.

In this idea, the Tx CPU would head the plane back home. (could current CPU handle this?)

This use case is not for FPV but for large gliders flying around 1km away and high altitude and "lost" in a cloud or in the sun.

Given the initial altitude, a lot of time is available for the recovery. High precision RTH is not required, when the ship becomes visible again, RTH is disabled.

The RTH descent angle can be set by a user-defined, GPS-driven constant speed setting (the plane is high in the sky) while the gyros keep the wings level.
A barometer would probably not be necessary as the altitude set by the GPS might be sufficient in this particular case.
The trickiest part could probably be making the initial turn to steer the ship to home heading. (Maybe defining a rotation rate in degrees/sec at a given speed is good enough?)

Am I dreaming? yes most likely! but why not asking?

Another way would be to convince FRSKY to develop an Rx line integrating these functionalities (including a baro)... but most probably a tiny niche market).
In the meantime, I will continue using FC's and Inav...

**Comment by mawzthefinn** [comment]
FrSky already sells FC's with that capability. If you want RTH, you should look at installing an FC with Ardupilot.

This is not a good idea to integrate in the transmitter, if only because of the long lag time. 

Note there's major regulatory issues with this request, it would for example render Canadian pilots unable to use the radio at all in controlled airspace due to the MAAC Safety code banning any RTH functionality being present on RPAS systems operated in controlled airspace.

**Comment by bsongis-frsky** [comment]
RTH should be done on board, not on the radio!
