### ISSUE TITLE
Trim Does not reverse with Mix weight

### ISSUE THREAD

**Issue by jfint** [FrSkyRC/ETHOS-Feedback-Community#292]
Tandem X20
Ethos 1.0.6
TD-ISRM 2.1.7
Archer R8 Pro on 2.1.7

I used the elevator Mix weight in a V-Tail Glider to invert the elevator control,(-50 instead of 50) this worked as expected, the elevator stick caused proper control movement, however the trim caused inverted control movement.

**Comment by centertrim** [comment]
I can see two possible solutions.

#1:  Do as you suggest and multiply the trim by the sign of the current mixer weight (keeping in mind that multiple rates on a switch are possible, which is why the trim is applied after the weight as it is.  I would think that any dual-rate type weights would normally have the same sign though, so this solution could probably work.)

#2:  Perhaps the elevator / aileron / rudder mixer output channel selections should have a "Reverse" option like the Free Mixer does, and then a negative weight would not be necessary.  As long as the trim was applied before the reversing of the mixer output then everything would work fine.

**Comment by jfint** [comment]
Ahhh, I see what you mean about it not being as simple as I thought initially.  I did manage to correct the issue by swapping the two VTail servos at the receiver.  Then everything worked as desired, and honestly was in the order I intended anyway (left 3, right 4)

**Comment by bsongis-frsky** [comment]
I will prefer not fixing something which works then :)

**Comment by jfint** [comment]
@bsongis-frsky , Please reconsider, this is actually broken the more I think about it.  The fact that you can have a negative weight on the mix called "Elevator" and that will invert your trim is a problem of some sort.  It is limiting to only have positive weight, but that is at least no broken.

**Comment by bsongis-frsky** [comment]
Then what about the curve? It could also be considered as a weight!

**Comment by bsongis-frsky** [comment]
What about weight = 0?

**Comment by jfint** [comment]
What about an invert option in the trims menu, separate from the mixes?  Believe me I hear what you are saying and I understand, I just don't agree that its not broken.  I do agree that it should not be a priority at the moment, there are several other issues I would rate higher.

**Comment by bsongis-frsky** [comment]
Honestly I don't understand why Aileron would even have a negative weight

**Comment by jfint** [comment]
It was the elevator, and the reason was that it was on the V-Tail, and to make the rudders move the correct direction the elevator was inverted.  Inverting the outputs created the opposite problem, so I tried to use the weight to deal with it.  I could have done a curve, but that would eliminate the easy way to do exponential, though a custom curve could still do that.

**Comment by jfint** [comment]
If I'm wrong, I'll accept it, obviously i found a fix and I am starting to feel bad for a long thread on what I would consider a low priority thing.   I did want to say, thank you for taking my comments into consideration!

**Comment by Willy163** [comment]
Hello everybody.
I see exactly the same problem.
If any mix weight is <0, then trim behaviour is inverted.
And it was difficult to understand that at the first flight because all my other radios do not work like this.
Please consider to make it automatic or, as suggested, to add the "invert trim" feature.
Thank you in advance.
Willy.

**Comment by bsongis-frsky** [comment]
The PR for this is ready. I will perhaps merge it for 1.0.10

**Comment by bsongis-frsky** [comment]
Automatically invert the trim seems to me a bad idea:

Imagine that the weight is controlled by a pot, and is around 0, oscillating between 0 and -1, then the channel value will always move because the trim won't be stable (negative / positive / negative)

**Comment by bsongis-frsky** [comment]
The only solution I can see is the toggle button. Invert trim YES / NO.
