### ISSUE TITLE
ETHOS V1.4.12 does not follow the curve correctly

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#2969]
ETHOS V1.4.12 does not follow the curve correctly
Free mixer 
Source Switch SA up mid down
5 point Curve 
5sec up and 5sec down for slow movements
only the final values are always approached
never the intermediate value at point 2 and point 4

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/0e5342d9-f33e-4c90-8e90-42b0599cc657)

**Comment by Dsrenger** [comment]
Isnt that as it should be?

Switch up mid down corresponds to -100, 0, +100
This corresponds to -70, 0, +70 in your curve.

Therefore, when you switch from SA down to up I expect the mixer value to go from -70 to +70 within 5s.

It doesnt matter what the curve is doing inbetween, right? As the switch is going from -100 to +100 immediately  without any value between these two end point.

The mixer has never 80% as input value at all.

Or do I get it wrong?

**Comment by mawzthefinn** [comment]
That's expected behaviour with ETHOS. It stems from a combination of how slow is calculated vs the curve calculation and how switches are treated when used as analog inputs

The short answer is that when a switch is used as a source, it does not do an analog transition between values, but jumps immediately between values, so the only curve points ever applied are 1, 3 and 5 in this example, with none of the interim curve points ever calculated. Then slow applies on the overall output transition, not before the curve.

The solution requires chaining the mix, with the slow and switch source in the first mix, and the curve applied in a second Free Mix using the first mixer channel as the input. Long term there is a better solution being considered, but it may not be ready for a while.

**Comment by hrenz** [comment]
What is very easy in OpenTx is not possible in ETHOS
and there is no description anywhere.

I thought I was too stupid to program that

and what if you apply the curve in the outputs?

**Comment by mawzthefinn** [comment]
Output curve will work, with the usual limitations (results can't be seen by mixers).

**Comment by bsongis-frsky** [comment]
> What is very easy in OpenTx is not possible in ETHOS and there is no description anywhere.
> 

Would you please confirm that what you wrote above is true?

**Comment by bsongis-frsky** [comment]
It will be part of the big FreeMix refactoring which is in progress

**Comment by bsongis-frsky** [comment]
Available in nightlies tomorrow

**Comment by hrenz** [comment]
Ok now it works
![2023-12-14_124729 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/5b05b496-19c2-4294-bd2d-75d56a4fd761)
![2023-12-14_124752 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/4f164410-7236-40ff-b4d1-14359a9c10c3)
