### ISSUE TITLE
x20 pro scratchy noise when you first turn the radio on

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2973]
not to be too picky but it is a thousand dollar radio made to compete with Jeti. x20 pro makes a short scratchy noise when you first turn the radio on.  makes it seem like a cheap radio. not going to show it off to all my Jeti friends

**Comment by bsongis-frsky** [comment]
I haven't noticed it. I will check it soon.

**Comment by williajgr** [comment]
it is just a small tick when one turns the radio on

**Comment by aeroplanebelg** [comment]
same thing for me . it's not great this scratchy. (x20 pro )

**Comment by ACCURA68** [comment]
My X20 Pro too, it's unpleasant.

**Comment by it-walter** [comment]
I can confirm this "scratchy" sound on X20 pro (1.4.1.4) after turn on.

**Comment by ACCURA68** [comment]
Yess, mine too, do this scratchy sound when turn on this baby...

**Comment by KevinFairgrieve** [comment]
Whilst not a critical issue, an issue none the less.

I suspect it is a hardware related "fault" and not something that can be resolved under ETHOS.

Like others have said for a 1000 £ $ ¥ (insert your local currency), it really should be resolved. I know it is there and it bugs the heck out of me.

If not ETHOS related perhaps @bsongis-frsky could pass it back to the R&D boffins at FrSky.

**Comment by it-walter** [comment]
The problem is certainly the speaker itself. Or in the hardware design in general.
The noise comes from some voltage in the device. I don't think this can be solved in software. Maybe the software can reduce the voltage in the first 1-2 seconds? Just an idea...
In general, I think the speaker is incorrectly sized. The sound is too quiet and too thin. Sure, you can improve this a bit with other sound files. But that doesn't solve the basic problem. A loudspeaker needs a resonance body. Carbon and metal are not ideal here, I think.

**Comment by bsongis-frsky** [comment]
I have noticed this problem too on the PRO AW which I just received, and I think I have nailed it yesterday.
#3844
