### ISSUE TITLE
v1.5 nightly: weight-up/down with negative slope are incorrectly translated to Positive/!Positive

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3014]
**Ethos nightly 1.5 31 October, X20 tx and sim**

In a mixer action, a 'Positive' condition in conjunction with a negative weight generates an incorrect curve, and an incorrect output.

Screenshots show minimalist examples.

- The first screenshot shows a positive weight - the curve is correct, the output value (not shown) is also correct.
- The second screenshot shows a negative weight - the curve is incorrect (same as positive weight), and the output value is also incorrect.

![goodb](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/f2bfdc20-5402-4068-abdc-469a6a6875f9)
![bad2](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/0389b533-0385-4b0d-a38b-7cc45d1048d8)

**Comment by bsongis-frsky** [comment]
Interesting use case!

Your source is positive in the right part of the curve. Then the first line is applied with weight -100%. It becomes negative.
Then the second condition is applied, and because the value from the previous line is negative it is also applied. As the weight is again -100% it becomes again positive.

**Comment by bsongis-frsky** [comment]
What about adding more "special conditions", like "THEN" (execute the action if the previous action was executed) or "ELSE" (execute the action if the previous action was not executed)?

**Comment by RC-SOAR** [comment]
@mawzthefinn, you're correct in suggesting that I didn't understand how Positive/!Positive worked (yes, I thought it was based on the source value). Thanks to Bertrand's explanation, I understand now.

However, there is still a migration bug, best illustrated with the following two screenshots. The first is the original mix from 1.4 (X18 sim), and the second the result _after importing the same model_ into X20S sim under 1.5 nightly.

I expect the two curves to be identical, but they are not.

![2023-11-01_132915a](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/65162938-ad3a-45ae-8ac8-cb40404e306a)

![2023-11-01_132929a](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6317479/579fec0d-e5ee-47c6-a0f5-76a3197a9a81)

**Comment by mawzthefinn** [comment]
@RC-SOAR - I agree this should be changed so that Positive is a condition that is based on mixer Source value, rather than current input to the Action line value. Then it would behave as expected.

**Comment by RC-SOAR** [comment]
I think that would work. So Positive and !Positive would be based on the source value, and the action would be applied to the current stack value.

If there are use cases for Positive as currently defined, maybe have an additional special condition, say 'PosSource'.

**Comment by RC-SOAR** [comment]
I've changed the title to emphasise the main issue, which is the incorrect migration of weight-up/down from 1.4 to 1.5.

**Comment by bsongis-frsky** [comment]
Agreed, the migration is incorrect. 

Also I would like to change this free mix a little bit more, because I find it is not easy to understand how it behaves when its global condition is false and/or when the condition of a single line is false:

Here is the situation today:
- the whole mix is executed when its global active condition is true or when it has an ADD operation (because otherwise SLOW would not work)
- a WEIGHT, CURVE or DIFFERENTIAL is then only executed when its line condition is true
- an OFFSET is always applied (active when both conditions are active, otherwise inactive)
- a SLOW is always executed

Here is my proposal for the next nightlies:
- either remove the global condition of the free mix, or completely disable the free mix (including SLOW and OFFSET) when this condition is false - I will choose the latter for now
- as proposed above base the Positive and !Positive conditions to the inputValue of the whole mix

**Comment by bsongis-frsky** [comment]
The last proposal helps me to solve the problem with Positive / !Positive and Bold

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/255a9768-71d6-417f-8618-8f90d3367216)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/2f0de883-eb5f-4fc3-af72-f1969139679c)

**Comment by bsongis-frsky** [comment]
It will be available in the next nightlies
