### ISSUE TITLE
Can the self level mode on sr receivers have its own channel

### ISSUE THREAD

**Issue by Szonu** [FrSkyRC/ETHOS-Feedback-Community#3025]
Looks like the self level channel ch12 on the old sr6 has been removed. 
can it be put back 
Or a option to put self level on a switch at the back of tx so it doesn’t stay on.

**Comment by mawzthefinn** [comment]
It's still there on the SR6 and all ACCST and Archer receivers, self-level on Ch16 on the new Archer Plus, TD and TW receivers was removed because of conflicts when using an R9 as a backup receiver (which has RSSI on Ch16).

It's trivial to replicate on ETHOS with a VAR mix, you can follow my video on how to do it here: https://youtu.be/w_2nIniBfro

**Comment by mawzthefinn** [comment]
Answer provided, closing off now
