### ISSUE TITLE
No Mixer delete confirmation.

### ISSUE THREAD

**Issue by KenLong51** [FrSkyRC/ETHOS-Feedback-Community#314]
Would it be possible to have a 'Do you really want to delete this mixer' prompt like all the other sections have please?

I am on X20 v1.0.7

Many thanks

**Comment by Hobby4life** [comment]
I want to add something:
(I am on the sim v1.02)

For example when setting 5 outputs.
How do I remove the 3rd output???? 
I see no way how to do that, only to remove all outputs, and start over again.. this make no sense.

Better is to **ADD** outputs seperately, instead of selecting how many outputs you want.
And a delete function for that output only.

**Comment by MIKE-DAILEY** [comment]
> I want to add something:
> (I am on the sim v1.02, correct me if this is already changed in newer fw)
> 
> For example when setting 5 outputs.
> How do I remove the 3rd output????
> I see no way how to do that, only to remove all outputs, and start over again.. this make no sense.
> 
> Better is to **ADD** outputs seperately, instead of selecting how many outputs you want.
> And a delete function for each output.

The delete function was added after 1.0.2..
