### ISSUE TITLE
1.5RC0: Incorrect migration of 'independent' trims

### ISSUE THREAD

**Issue by RC-SOAR** [FrSkyRC/ETHOS-Feedback-Community#3172]
When migrating a flight-mode independent trim to 1.5:

_Expected_: one behaviour should be created for each flight mode, behaviour type = 'normal'
_Actual_: the trim is shared across all flight modes

It's important that independent trims should be correctly converted, as (a) the user can easily miss the issue and (b) fixing it manually could potentially involve a lot of work, for users with several models and several flight modes per model.

**Comment by bsongis-frsky** [comment]
Ready for RC1

**Comment by agibson2** [comment]
I was just going to report this.

I just noticed this on my system.

**Comment by agibson2** [comment]
I just tested conversion of my M4 helicopter from 1.4.15 saved model file to 1/19 nightly and it looks like additional trims don't get converted correctly yet.  I don't see anywhere the new trim in 1.5.0 1/19 nightly is referencing channel 5 to adjust the Gyro gain on my flybarless controller.  I had created 3 Trim Mixes on 1.4.x for each IdleUp flight mode so that I could trim the gain per flight mode.  All 3 of the old Trim Mixes were created as Trims but I don't see anywhere where they are referencing to adjust channel 5.  I assume a regular mix is created to do that?

My 1.4.15 m4 model file is attached so that you can see how it gets converted.
[m4.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14002262/m4.zip)

**Comment by agibson2** [comment]
So yea... It didn't create the mixes to connect the addition trims to channel 5.  To fix it, I created an Offset mix to channel 5 referencing the trim.  I also cleaned up and removed the 2 of the extra trims and just have one with it set to 'value per flight mode'.  I assume I could have done that in 1.4.x too.
