### ISSUE TITLE
PC based application expectation and milestones?

### ISSUE THREAD

**Issue by BobCotsford** [FrSkyRC/ETHOS-Feedback-Community#319]
Is a PC based application along the lines of Companion in the pipeline, and if so when is it likely to be released?

**Comment by Hobby4life** [comment]
I hope something will be released soon, I always preferred to pre-program models on the PC.

**Comment by Sigee3** [comment]
This is a must have.

**Comment by GoodyearBiff** [comment]
This is one of the most important things that can be done for Ethos. I just programmed a 10 channel EDF. It was a chore using the dial and punch method on the radio. Unless this is done there is no reason to use this radio at all.

**Comment by CliffEvans** [comment]
This is a must-have item.

**Comment by Peschi90** [comment]
I think it is not a must have but it makes everything a lot easier

**Comment by higheronnitro** [comment]
This is an absolute show stopper. I have built a glider using the touch screen and dial and wont be doing that again. even just adding the name was a pain...All my fellow compeditors agree its a great looking radio but if you cant setup 95% of a new airframe and test on the PC before sending to the radio it will always be just a nice radio for Sunday flying.. As such I will be putting it back in the box and keep using my QX7 for now...

**Comment by VancouverUmbrella** [comment]
Since I encountered OTX Companion, I have never again programmed a model on a radio. And I hope never to do so again. In fact, I doubt I would be able to replicate some of the programming I've done Companion on a radio. Perhaps, I might with the aid of pencil and paper to keep notes.

In any case, a Companion-like PC app is now something I look for in a new radio or OS. Without such an app, I don't see myself using EthOS or buying any radio that runs only EthOS.

I can only imagine the complexities of building a new OS from the ground up. Judging from user reports, EthOS has come a long, long way in a short time. Kudos! Still, for folks like me, seeing a Companion-like app on the project timeline would be a great reassurance.
