### ISSUE TITLE
simulator.exe how to reduce its performance

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#3248]
When I develop my widget and run on my PC, each wakeup loop takes 0.000 seconds.
That's because my PC is very fast.

But on my X20Pro, each wakeup loop takes about 0.030 seconds

In order to troubleshoot and improve the performance of my widget, it would be AMAZING if the simulator had the same speed as my X20Pro processor.

Is there a way to achieve that?
Thank you!

**Comment by koakumaping** [comment]
change to Jeti.

**Comment by strgaltdel** [comment]
just my 2 cents as a user who does "a lot of lua stuff" :

It is imho obvious that the simulation of Ethos real-time behavior on all types of PCs and laptops, taking into account the respective load on the transmitter, is a complex, resource-intensive and costly undertaking, which imho can significantly drive up the prices of transmitters and blocks the development of other features under Ethos.

The feature is a very specific concern for a very limited number of users & demands a lot.

We'll have #2513 since 1.5, so I don't know what should justify an implementation

**Comment by bsongis-frsky** [comment]
I don't think it's worth spending time on this one. The delay between 2 loops is correct (same on the radio and the simulator). The loop itself is quicker on your PC, depending on his speed. If we wanted to reduce the speed, we would have to mimic the speed of the transmitter (depending on his CPU and the load from all components). It seems too difficult to achieve.

@strgaltdel is right, 1.5.0 brings some new tooling inside Ethos Suite to help you to test your scripts on real hardware, it becomes very simple now!
