### ISSUE TITLE
TD-R10 loosing telemetry data from AerobTec Altis V4+ (multifunctional competition altimeter)

### ISSUE THREAD

**Issue by 3D-Cat** [FrSkyRC/ETHOS-Feedback-Community#3303]
connecting Altis v4+ to TD-R10 at Pin 8 (S.Port)
X20S -> RF v2.2.6, TD-R10 -> FW v1.0.12  
1- takes very long time to find 3 Altis telemetry sources
2- looses frequently the altis telemetry data (turns red)

same Altis v4+ works fine with TD-R6 FW v1.0.12

**Comment by mawzthefinn** [comment]
This is likely a firmware issue on the Altis.

The TD R10 (and all the receivers with channel ports that can be assigned to S.Port/FBus/SBus) are stricter about S.port timing than the receivers with S.Port on the 4/6 pin connectors. Sensors must strictly follow the published spec to work properly with the TD R10 and similar receivers. 

That it has issues on the TD R10 and not on the TD R6 is an indicator of this issue, since the TD R6 is less strict on S.port timing.

**Comment by 3D-Cat** [comment]
thanks mawz, I'll contact AerobTec

**Comment by mawzthefinn** [comment]
Setting this as a non-ETHOS issue since it's Receiver/Sensor communications
