### ISSUE TITLE
Ethos Suite 1.5.0 RC1 switching to firmware in Mass storage mode doesn't work

### ISSUE THREAD

**Issue by pstasek** [FrSkyRC/ETHOS-Feedback-Community#3343]
After flashing the 1.5.0 RC1, the Remote version is missing until attempting to switch between bootloader and firmware in mass storage mode, the versions then populate but the Suite gets stuck.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4296578/1c348833-4a38-4751-872c-e7f62df7c733)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4296578/c6a1f18c-437c-41cd-81a8-a38dd4b8028a)

The same is switching back from Firmware to Bootloader.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/4296578/a4fca09e-eda1-4916-a9fa-96865d4c8e82)

The radio does the switch, mass storage devices appear in file explorer but the Ethos Suite is stuck on these messages.

**Comment by strgaltdel** [comment]
Just my experience:
working with the latest rc1 suite (i guess there was an update on friday) i have no problems regarding the dev tools on my x18 , using my main notebook, based on a 5 year old i7 cpu, running win10

connecting the same tx to my old m3 based win10 notebook, i ran into same problems
only every 10th try to change into serial mode was successfull
starting in admin mode doesnt seems to change anything.

i dont use the suite often and was wondering, that i had to connect the tx before starting the suite, so that the tx can be detected.
connecting tx in case suite is running prevent the app from detection on botg of my notebooks.

i'm really not sure if its a timeout related problem, driver or something else.
the fact that i was able to switch into serial mode on my old notebook (this time started in admin mode) seems to point into a timing problem
tried admin mode several times, but was not successfull a 2nd time

**Comment by ronron84** [comment]
In the picture you want to go back to 1.4.17?

**Comment by Nicholas-Luoyi** [comment]
After switching to firmware / bootloader. Could you see flash and sdcard disk in file explorer?

**Comment by strgaltdel** [comment]
I can only speak for my use case, lua dev tools on the older notebook:

the suite seems to send a valid command, and the tx changes into corresponding mode.
(so a change from suite mode into serial mode let disappear the mounted volumes & the transmitter is requesting the checklist) which is confirmed in less as a second
But the suites screen stays on "switching to..", runs into timeout after several seconds and tx detection got lost

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/3794d417-fcd8-4f98-860b-26744f7351ac)


maybe @pstasek can approve for changes into bootloader/firmware mode...

**Comment by pstasek** [comment]
> In the picture you want to go back to 1.4.17?

No, it's there by default as the Stable branch is selected. This is my second radio I'm using for experiments, so no harm done.

> After switching to firmware / bootloader. Could you see flash and sdcard disk in file explorer?

Yes, the flash and the sdcard drives are visible and available in the File Explorer.

Before clicking the Write All the detection worked fine even with the 1.5.0 RC0, just the i18n version was never detected correctly. Just for the sake of being sure everything is flashed correctly, I also manually placed the bootloader.frsk and firmware.bin onto the SD card and performed the flash manually with no difference. Even after uninstall and reinstall of the Ethos Suite.

**Comment by bsongis-frsky** [comment]
Problem confirmed with the latest Ethos Suite from 1.5.0 nightlies? Or it is fixed now?

**Comment by pstasek** [comment]
Latest version installed from 1.5.0 RC4 assets resolved the issue. Thanks!
