### ISSUE TITLE
Yappa calling out the wrong flight modes ethos x20s

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#3351]
Yappa calling out the wrong flight modes ethos x20s

**Comment by bsongis-frsky** [comment]
Who understands this issue?

**Comment by williajgr** [comment]
not sure what the problem is, works on one of my drones but not the other.  interesting the drone it doesn't work on works fine on my opentx transmitter.  Pixhawk controller. yes it is a yaapu widget, sorry.

**Comment by williajgr** [comment]
all of the other telemetry is working fine

**Comment by RealTadango** [comment]
Sounds like an issue with yaapu? Better check with the developer there....

**Comment by mawzthefinn** [comment]
Yes, please report this to Yaapu

**Comment by williajgr** [comment]
if i switch from the model (drone) that works on the x20s to the one that doesn't work on the x20s (and rebind) then everything works  seams like something isn't getting reset when one switches models.

**Comment by RealTadango** [comment]
> if i switch from the model (drone) that works on the x20s to the one that doesn't work on the x20s (and rebind) then everything works seams like something isn't getting reset when one switches models.

Mmh, maybe the lua state is not reset correctly when switching between models. This could be a Ethos issue also. The lua script should not have to do this i think.

**Comment by strgaltdel** [comment]
another possibility would be a lua coding bug in the create handler which is called once by tramsmitter boot.

in case there is initialization of "model specific" variables, these wouldn't be re-initilized by a model change.
Without knowing the details what's done in the script its hard to make a decision if the bug is script or Ethos driven.
I 've the feeling that a "problem" like returning wrong FM indizes in the corresponding lua method due to changing models would have been reported even in other cases.  

Again, the most effective way would be to descibe Alessandro the problem.
I really don't know why the operator is resisting so hard to give it a try

**Comment by williajgr** [comment]
i had hooked these drones up many releases ago and there were no problems.  haven't changed the yaapu firmware.  I just haven't used them for a long time.
