### ISSUE TITLE
Ethos Suite 1.5 crashed

### ISSUE THREAD

**Issue by doloebig** [FrSkyRC/ETHOS-Feedback-Community#3434]
Hello
i have freshly installed Windows 11 and Ethos Suite 1.5
The Suite crashed soon in connect the X20S
Drive from Transmiter kann acessed normal

Maybe someone can see the probem in log
Regard 
[crash-20240213.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14278552/crash-20240213.txt)

Doro

**Comment by samsab1** [comment]
same crash for me

**Comment by bsongis-frsky** [comment]
Fixed, I am uploading a new bin in RC3 release

**Comment by ferincr** [comment]
Hi, can you tell me a bit more how you solved it? mine hang out but I know it's something on windows side since it happened in win10 and now in 11 but it works fine for a while when I start the pc.
It has to be some service or app that makes it crash. I tried disabling Defender and other services but no luck so far.
Thanks,
