### ISSUE TITLE
Rssi value

### ISSUE THREAD

**Issue by lotus1235** [FrSkyRC/ETHOS-Feedback-Community#3501]
Hello,
I'm using a gr6 2.4ghz and a Frsky x18se. When I go to the range setting and walk away from the sailplane,  my rssi reading goes down to 40 within about 100 feet. I have the antennas on the outside of the fuselage at about 90 degrees from each other. My vfr seems to be fine, well above 55. Not sure what to think at this point. I have not flown it, new tx and rx, because of the low rssi value. Any thoughts would be helpful. 
Thanks to all, what a great community. 
Cheers

**Comment by mgsanna** [comment]
Those value come out at 100 ft in "range check" ? 
This more than normal, if you read about the range check you'll notice that the transmission power is a very little percentage of the normal rf power output... (let me say something about 1% of the real power output).
so let's imagine a range check with full power output you have to walk for km/miles before getting signal lost, so for my experience go flying your "bird"....
And Last but not least : rssi is a variable value and it's normal to get value decreasing when you walk away from the receiver, it's not a fix value, remember that VFR is the valid frame rate more important than RSSI, because you can i.e. fly in a disturbed area and get very low rssi but very good VFR, your flying will be safe in any case, it is worst to get a low (under 50 VFR).... 
Remeber if you come from other brands, that when you get the feedback of telemetry about signal and transmission during the flight it's normal to get worried about, because you were not aware of what is happening with other brand system... (personal experience some years ago, starting using FrSky) 
have a nice weekend!!!!

**Comment by hrenz** [comment]
The range check is performed at Frsky with -10dBm, which is 1/1000 of +20dBm
At the beginning the RSSI value drops rapidly and then remains at approx. 35dB for a long time
The receiver AGC adjusts the gain as much as possible and keeps it at RSSI 35dB for a long time.
Only when this is no longer possible does the RSSI value drop further until the failsafe is triggered at 22-25.
This is why the warning thresholds are set to 35 and 32
for every 6 dBm it is always a doubling of the range

**Comment by lotus1235** [comment]
Thank you very much for responding to my question. I totally misunderstood what the values were. thanks again.
