### ISSUE TITLE
Slow and reverse on all mixes

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3508]
It would be nice if the slow and reverse option were available for all mixes.  (this is missing, for example, on the Flaps => Elevator mix where a slow option is very important)

**Comment by RealTadango** [comment]
More is missing but it is by design apparently. The idea is that you slow the flap mixer and use the flap channel data as input for the flaps elevator mixer, not the flap input slider / switch. If you use the flap channel it is already slowed down. Sometimes you want different durations for flaps and the compensation so i agree, this would be great. I never use the preset mixers and always use free mixers because i want to do things my way. Offset is another thing that is missing.... so use the free mixer ;)

**Comment by hrenz** [comment]
With FreeMixer ( V1.5.0) you can do what you want.

![2024-02-27_120453 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/5a312dfa-e364-473e-8891-dc32cc68b9c4)
![2024-02-27_120408 jpg](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/764d4f30-271a-4c80-953b-625348e29e91)

**Comment by spoke2570** [comment]
These would be really nice. I know there are ways around, but these would be really nice.

**Comment by mawzthefinn** [comment]
A clouple notes.

1. If you are using your flaps input as the source for a Flaps->anything mix, you are not mixing Flaps to anything. You need to use the Flaps output channel. That solves most of the slow issues and also means that adjusting the flaps slow does not require a second adjustment of the other related mixes.

2. Offset is a separate mix as when you are using canned mixes, the use of Active Conditions can result in inconsistent application of offsets if you do the offset in a canned mixer. Therefore you should set that separately with the Offset mix.

3. Delay is in Logical Switches, if you want a delay, use an LS to control the mix. This was a deliberate change to separate control functionality from mixing functionality.

**Comment by mawzthefinn** [comment]
> I have several models where the controls surfaces aileron, elevator, rudder move very quickly, violently even, thanks to modern equipment. It would be nice to be able to slow these down particularly for scale.
> 
> I like to look in the outputs section and compare the mix sum and the output reality with bars that go the same direction. The old eyes ain't what they use to be and the text is hard to read. Also is is counterintuitive that for ailerons for example the mix should send one servo 0 to 100% and the other should be 100 to zero (X graph) when the two servos are both turning the same direction clockwise.
> 
> I have moved to using mostly canned mixes now but even if a base slow up/down were added to outputs reverse at the mixer is still a large desire for me.

Consider that several configuration items for Ailerons must be applied in opposite fashion for each side, particularly Differential. That's why each side is applied in an opposed manner. It's much simpler and more intuitive to apply Differential identically then just output via opposed curves.

**Comment by spoke2570** [comment]
Just saying, I don’t think this is a finished conversation.  I think a lot of folks  want this.

**Comment by mawzthefinn** [comment]
> Just saying, I don’t think this is a finished conversation. I think a lot of folks want this.

I suspect more would regret output reverse if it was actually implemented at the mixer level. It will lead to inconsistent mixing issues and doesn't actually solve a real issue since any other mixes now applied to the channel will need the same reversing (and would not if you reverse in Outputs).

Note that many other systems do the same thing, just silently. Spektrum most notably (just watch Monitor for a 2 Ail wing type on Spektrum). The ETHOS implementation is very standard for aileron direction, it just is nice enough to show you exactly what it is doing.

**Comment by spoke2570** [comment]
Admittedly more of a PITA for the folks doing the coding, but I don’t remember any users griping about it. As for comparison to other radio systems. I never found one I liked until OTx and I have high hopes for ETHOS to fully replace it.

**Comment by WhiskeyGolf** [comment]
Is it a very big effort to add reverse options to all mixers?  Personally, I don't understand why, for example, the ailerons are always crossed, since the servos often work in opposite directions due to the installation themselves, which would require a reverse.  In my opinion, getting around this with a freemix requires a huge amount of effort until everything is configured.  The risk of forgetting important functions such as trims via offset when programming with freemix is ​​great.  In addition, trims over offset behave differently on a free mix (0.2% trim corresponds to 1% offset in the mix).  Furthermore, it is much more impractical to edit all Expo and weight parameters in the new Freemix.

**Comment by RealTadango** [comment]
Just set the weight to -100???

**Comment by WhiskeyGolf** [comment]
That's not a real solution for flipping individual channels from the input.  This means you can only reverse the entire input and not the paths to the individual outputs.  This would only work if you had individual weights per output, which would also be a good idea.  I've been working with openTX for a very long time and know enough detours to get to the goal, but with Ethos it always requires very large detours and messes up the whole structure and overview

**Comment by mawzthefinn** [comment]
> That's not a real solution for flipping individual channels from the input. This means you can only reverse the entire input and not the paths to the individual outputs. This would only work if you had individual weights per output, which would also be a good idea. I've been working with openTX for a very long time and know enough detours to get to the goal, but with Ethos it always requires very large detours and messes up the whole structure and overview

If you want the canned mixers to work together properly, reversing the output is the correct method to go.

If using Free Mixes, it's a non-issue since those can reverse per-channel.

I'm still failing to see how doing this will not create more issues than it solves for the canned mixers, since it will let you break the expected output of the mixer compared to other canned mixers. That's why Canned mixers do not have reversing per channel, because when you layer canned mixes if one is reversed in the mixer, adding another one (like a rudder to aileron mix) on will also need the same reversing applied. By reversing at the output all the canned mixers will work together correctly and you only need to address channel direction when applying a free mix. 

The Aileron canned mixer's implementation is very much standard practice. Even in OpenTX/EdgeTX it's common for the second aileron channel aileron mixers to be negative weight for exactly this reason, as shown in the RC-Soar guide here:

https://rc-soar.com/edgetx/basics/index.php

**Comment by spoke2570** [comment]
@mawzthefinn, 
There are no end to the ways a user can break these systems. We are just asking for one more opportunity to be thoughtful about how we break them.

**Comment by mawzthefinn** [comment]
> @mawzthefinn, There are no end to the ways a user can break these systems. We are just asking for one more opportunity to be thoughtful about how we break them.

And I'm opposing the change because it would hurt less technical users more than it would help more technical users. It's very easy to work around for anyone familiar with a Free mix, but the moment a new user does this in a canned mixer instead of reversing their output channel, they will have problems with any other canned mixers they add to these channels. 

In general I oppose adding complexity in the canned mixers, and support adding it in free mixers to balance the needs of less technical users vs more technical users.

**Comment by bsongis** [comment]
> I have several models where the controls surfaces aileron, elevator, rudder move very quickly, violently even, thanks to modern equipment. It would be nice to be able to slow these down particularly for scale.

There are Slow up / Slow down parameters for that purpose in outputs

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/5603504/4d316076-db50-4f45-ae1c-0a3a16209a49)

**Comment by spoke2570** [comment]
I get that there are plenty of ways to get around this. In my own radios I have, of course. 

I am relatively certain that if the option for inverse were put in a hamburger menu they would be out of the way enough that a beginner user would blow right past it. ..and the more experienced user that is moving their models from a 1.4.x to 1.5.x would come up against fewer issues getting a bunch of cobbled mixes sorted out into the more streamlined, canned options. 

I am raising the issue no more, but I will chime in when I see it mentioned as I do support this. I do feel like the canned mixers are quite close to being fully featured. 
Thanks all that this team does. I really appreciate it.

**Comment by mawzthefinn** [comment]
I hadn’t considered putting it in a hamburger menu, that would be a good balance between usability and flexibility. I’d been thinking about a slide switch like in the free mixer

**Comment by spoke2570** [comment]
I think there is a way. It may require a little thought and care, but we will get there. Right now I think there are bigger items to spend time on, but this topic should continue.

**Comment by WhiskeyGolf** [comment]
I think the idea of ​​hiding reverse as a “burger” is great.  Then you could also use weights instead of the reverse switches, which you can turn negative to flip individual channels or adjust the weights.  All in all, I'm very happy with Ethos!  I think a very good job has been done here!  I see this addition as more of a cherry on the cake.
