### ISSUE TITLE
stuck in bootloader

### ISSUE THREAD

**Issue by Rem11111** [FrSkyRC/ETHOS-Feedback-Community#3557]
Stuck in bootloader my radio only goes into bootloader this happened after update to turn it off do I have to switch off the battery what can I do. frsky x20 When I try to turn it on normally it does nothing

**Comment by strgaltdel** [comment]
very little description for such a problem
which kind of update ?
which bootloader ?

maybe update from 1.4x to 1.5?

common problem if x18 user didn't update bootloader at first

would advice to read the postings starting with 1907 and follow the given steps for solution
https://www.rcgroups.com/forums/showthread.php?4108571-FrSky-X18-X18S-X18SE-Tandem-24-Channels-with-ETHOS/page128

i'm wondering about your issue because the 1.5 "bootloader" issue was announced for X18 only, but may apply to x20 too
https://www.rcgroups.com/forums/showpost.php?p=52191009&postcount=1894

**Comment by mawzthefinn** [comment]
What bootloader version? You need 1.4.15 or later

**Comment by Rem11111** [comment]
I wanted to update it to 1.5.0. release from 1.4.3

**Comment by mawzthefinn** [comment]
Latest bootloader for the X20 is 1.4.15

1.4.3 won't boot ETHOS 1.5, which is your problem.

Solution: Flash ETHOS 1.4.17 manually (download the firmware, copy to your SD card, boot radio in bootloader, the bootloader will automatically flash any firmware.bin file found in the root folder of your SD when booted into Bootloader mode)
Then update your bootloader to latest 1.4.15
then update the radio to ETHOS 1.5

**Comment by bsongis-frsky** [comment]
Latest Ethos Suite update shouldn't allow you to flash firmware 1.5.0 if you use a old bootloader

**Comment by Rem11111** [comment]
Thanks its workt.
________________________________
