### ISSUE TITLE
Ethos 1.5.1 bricks X12S ISRM

### ISSUE THREAD

**Issue by Luznatural** [FrSkyRC/ETHOS-Feedback-Community#3571]
When successfully flashing (apparently) my X12S ISRM with Ethos 1.5.1, the radio produces multiple bricks (having to remove the battery to unlock) especially when you turn on the radio. If you leave the radio off for a while, is impossible to turn it on. All the times, when pressing the on button, only the blue light remains on and you do not see anything in the screen. You are not able to turn it off, having to remove the battery to recover control.
When you are able to turn it on, when you move between menus very frequently you get emergency mode.
This issue happened also in Ethos 1.5.0

**Comment by bsongis** [comment]
Is your bootloader up to date?

**Comment by Luznatural** [comment]
Yes, version 1.4.17. There is no other version available, and Ethos confirms that is updated

**Comment by strgaltdel** [comment]
How many lua scripts do you have in the /scripts folder?
During Tx Boot, they all are initialized, even in case your actual model doesn't use one

In case you have several scripts it may be worth to rename the scripts folder so they can't be "loaded"
This would prevent the tx to suffer from 1.5 incompatibilities / memory problems caused by a problematic luas

i may recall that, in history,  problematic / slow SD cards could generate EMs too,
don't know but in case 1.5 generates a little more i/o it could be a cause too.

**Comment by bsongis-frsky** [comment]
What makes the beeps? The ISRM module? Or the radio itself?

**Comment by bsongis-frsky** [comment]
Is it the same with Ethos 1.5.3?

**Comment by Luznatural** [comment]
I guess you meant 1.5.2. I have checked and apparently the problem has been solved.
Good Job.
