### ISSUE TITLE
TD SR18 Emergency Mode

### ISSUE THREAD

**Issue by 4qr1hu9n7** [FrSkyRC/ETHOS-Feedback-Community#3596]
Emergency mode (CH 16) on TD SR 18 receiver does not work.

**Comment by Dsrenger** [comment]
Note in the TD-SR18 manual:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/c89abb90-5df1-426b-b59d-95af9d96f735)

The Ch16 emergency mode is not avaiable anymore.
As the emergency Mode is the same as the automatic level mode, it get activitated by Channel 14 SW up

There was some kind of unwanted behaviour with R9 receivers.

**Comment by chenbevis** [comment]
Have all the stabilized receivers discontinued the 16CH function?

**Comment by Dsrenger** [comment]
Not sure, just look up the manuals of the receivers you are interessted in.

**Comment by mawzthefinn** [comment]
> Have all the stabilized receivers discontinued the 16CH function?

Yes. 

Note the functionality is still there, it's just not on Ch16 anymore, because that caused a conflict when using an R9 as a backup on Archer Plus and TW series receivers (R9 hard-codes RSSI on CH16 which could trigger emergency).

The emergency mode is identical to triggering self-level via CH14 (Quick Mode) or Ch14/15 (Regular Mode). If you are using VAR's or Var mixes to set stabilizer modes, you just need to add a top priority value line triggered by the desired switch. I did a video on this here:

https://youtu.be/w_2nIniBfro

**Comment by 4qr1hu9n7** [comment]
Thanks for the help.
