### ISSUE TITLE
Offset curve always active when controlled by Logical Switch

### ISSUE THREAD

**Issue by dWoolridge** [FrSkyRC/ETHOS-Feedback-Community#3615]
Setup:
X20S, Ethos 1.5.1

Problem:  An action of type "Offset" in a free mix does not deactivate when the active condition is a logical switch, and the logical switch is off.  The "Offset" action remains on all the time, regardless of the Logical Switch set as the active condition.

Free Mix: Action-->Offset, Active Condition set to lsSmkPulse (Logical Switch)
lsSmkPulse is a Logical Switch, Timer generator, Duration active 0.5s, Duration inactive 0.8s

The Offset Action is always active (as the lsSmkPulse logical switch goes on & off.)

Actions of type "curve" and "weight" activate/inactivate as expected with the lsSmkPulse logical switch.

I didn't test any other actions, so I'm not sure if other actions behave correctly or not.

**Comment by Jedsters** [comment]
@dWoolridge I was curious so thought I'd give this a go on 1.5.2 and it works fine for me using what I understand you have done from the above. 
Although maybe I've misunderstood your point. If you are saying that the output channel is fine but it's just that the Action line doesn't change between bold and not then I agree, the Offset Action line remains bold all the time even when e.g. a Weight Action line changes between bold and not.

**Comment by dWoolridge** [comment]
Hi Jedsters,

I tried it again (on my X20S with ETHOS 1.5.1) and confirmed that the output channel is not fine.  After I did the numbered items below in my transmitter (1.5.1), I tried the same setup in the 1.5.2 X20S Simulator and the channel output was correct, but the bolding stayed bold and did not toggle.

Below is what I did (just to make sure we're on the same page and that it may be fixed in 1.5.2)

1)  Create a logical switch, Timer Generator, 0.8s on, 0.5s off
2)  Create a free mix, Leave the default Action (Always on, Weight 100%)
3)  Add new action, Active Condition:  the Logical switch, Action: Offset, 50% active, 0% inactive.

In this trial (1.5.1), the "bolding" of the action flashed in time with the logical switch, but the channel does not change (the 50% offset is always active)

4)  Changed the Offset action Active Condition to a switch (SF in my case).  The switch does not turn the offset action on/off, but the bolding works correctly.

**Comment by Jedsters** [comment]
OK, my setup is I believe the same. 

I've not tried your list items 1 to 4 on 1.5.1 so I'll take your word for that but it's good we agree what's happening with 1.5.2 (I think). I suspect the Devs are more interested in what happens with 1.5.2 since that's current code which will be checked and updated. 

@bsongis-frsky  I believe @dWoolridge  and I agree with 1.5.2 for his items 1 to 4  it is just the bolding which doesn't change for an Offset Action but the output does. It doesn't matter if the Action is e.g. SF Down or SH down or a LS (e.g. your timer), the bolding remains bold all the time. 
With 1.5.2 it appears to be a 'cosmetic' issue which needs fixing rather than a functional issue.

This video shows 2 actions using the same TIMER LS, but only the Weight Action flips between bold and back
https://www.dropbox.com/scl/fi/3l53rd72djii9cyawcxvi/VID_20240311_155541.mp4?rlkey=fe5jnulavphypmd0bi6ubj39p&dl=0

**Comment by dWoolridge** [comment]
Thanks @Jedsters and @bsongis-frsky 

Based on my limited 1.5.2 testing, I agree that, in version 1.5.2, it is a cosmetic rather than functional issue.
