### ISSUE TITLE
Image manager

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#3617]
Tx: - X18SE with ETHOS 1.51

In the Image manager in ETHOS Suite, can there be an output to cater for the default screen when you switch ON the Tx?

The attached image is what I am referring to. Images created by the Image Manager are greater than what the bitmap box support, and horizontally, part of the image is cropped, unless I am missing something.

![Screen](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/68815554/2a387425-7cc4-464a-a926-e18874c8334f)

**Comment by bsongis-frsky** [comment]
The problem is ... all the placeholders on your screenshot (and in all other layouts) have a different size!
If you need to know the exact size for your placeholder, just do a screenshot and open it in photoshop / gimp, it will tell you how many pixels you need your bitmap to fit exactly to the zone

**Comment by salibaj2** [comment]
Thanks for the suggestion. I tried by guessing the screen size and there I failed. 

Now got your idea and will work around that.

Thank you
