### ISSUE TITLE
1.5.2 Conversion issue: FreeMix Weight up/down

### ISSUE THREAD

**Issue by Dsrenger** [FrSkyRC/ETHOS-Feedback-Community#3639]
Hello,

I just converted one of my models from 1.4.15 to 1.5.2

I found a conversion issue, that is probably worth to fix (if possible)

Free Mixer in 1.4.15:

Curve and weights

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/98de7f5a-47b5-4d91-9315-eaca96de74d7)
 
And thats the used curve 
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/99aee045-3896-430a-9352-50e31fed1557)

In 1.5.2 This gets converted to:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/51758752/48940210-241d-4200-9ed9-9eb965da56d3)

Clearly, the output is not the same and needs manual corrections.

I dont question, that the mixer logic in 1.5.2 is wrong. The mixer itself is calculated correctly.

But the conversion from 1.4 to 1.5 is not correct.

Weight up and weight down are not equal to positive/weight and negative/weight.

Weight up in 1.4 had an effect on everything above the x axis
Weight down in 1.4 had an effect on everything below the x axis

Positive/weight has an impact on everything right of Y axis
negative/weight has an impact on everything left of X axis

I get, that the fix i probably not easy, as there is no action like weight up and weight down in 1.5

But at least I wanted to open the issue. Perhaps you know an easy fix to make the conversion better. 
I guess it can cause a lot of frustration for not so experienced users/power users.

Regards
Dennis

Attached you will find a showcase model file (1.4.15 to check before and after conversion)

[conversion test.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/14578292/conversion.test.zip)

**Comment by strgaltdel** [comment]
Hi Dennis,

We both addressed the problem yesterday
therefore as a supplement:

To migrate the above example directly, there is a lack of "weight up" and "weight down" objects in Ethos actions

We have the pair "weight" and "differential" in 1.5
With static values it would be no problem to convert
80% weight up and 40% weight down result in e.g.
weight 80% and diff 50%
 
In more complex cases, however, we cannot perform a 1by1 conversion, 
for example if a value in 1.4 was dynamically "pulled" from a channel.

It may be useful to add dedicated weight-up / weight-down objects,
or give a hint during the conversion ?

regards Udo

**Comment by bsongis-frsky** [comment]
I can fix it easily, by saying that Positive / !Positive check the intermediate value (in your example, it's after the curve is applied). But ...
1) it could break 1.5.2 setups
2) I am not sure there are many use cases, applying Positive / !Positive to the Input of the FreeMix seems better to me

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8c11f7aa-1c25-4303-9a5c-4561b836131a)

**Comment by strgaltdel** [comment]
Bertrand,
i've the feeling we're talking not about the same "issue"

"I can fix it easily, by saying that Positive / !Positive check the intermediate value "
i don't think that's the issue we mentioned.

"Inside" 1.5.2 , the last image, everything is correct.
The output is, as the mixer is configured, no problem and we see a logical flow of data calculation

The problem is the conversion,
weight up/down was "translated" into positiv/negativ Input distinction which "crashes" the configuration for the user after migration  a little bit.

In our scenario the user didn't know why his template was "messed up",
we gave him some hints (delete second action & configure 3rd into "always on"),
which was OK for this dedicated situation

All in all it's a conversion issue,
we don't expect that anything within status quo of the mixer calculation should be changed,
maybe, as mentioned, 2 more "objects" (weight up/down)  and a change in the migration method.

As stated, by know,
everytime a user uses weights up/down in 1.4 in a free mix the migration produces a failure..

**Comment by bsongis-frsky** [comment]
The problem is simple:

1.4 - Positive / !Positive are applied to the result of the previous operation (this is why the user speaks about everything on the upper part of the graph)

1.5 - Positive / !Positive are applied to the Input Source

I wonder which one is best. Or if I can introduce some other conditions.

I am not a fan of the 2 lines Weight Up / Weight Down, because they are more difficult to reuse in other mixes.

**Comment by mawzthefinn** [comment]
We need both really. 

1.5's Positive behaviour is needed to duplicate Inputs functionality from OTX, and in particular to do per-side rates easily.

But it doesn't mimic 1.4's behaviour in the edge case where the curve is in the upper left or lower right quadrant, which breaks conversions as demonstrated here.

Perhaps the solution is to always put them first in the conversion? I suspect the conversion would work as expected if the curve was after the rates, not before.

@Dsrenger - can you recreate your curve line after the rates line? I think it will behave as expected then.

**Comment by strgaltdel** [comment]
Hi mawz,
as mentioned, it was another user,
Dennis reproduced the problem
dennis and me helped to solve his issue.
but both of us agreed to open a case, because root cause was conversion misbehavior and so it could result in some "user dissatisfaction" 

"Perhaps the solution is to always put them first in the conversion?"
Good point!
and as far weight up/down would be equal, one more action for weighting would be sufficient.
In case you have fixed value for down, you could recalc by a "diff" action

I think that would serve 90% of the problematic 1.4 templates.

**Comment by bsongis-frsky** [comment]
@mawzthefinn Move the curve up won't work, the result will be very different, we cannot change things order, it would be too simple!

**Comment by strgaltdel** [comment]
let's say we have an amount of 100 different 1.4 user, each has 10 model configs which are to be converted into 1.5

i would assume 15% of these users are using free mixers  in combination with a curve & different up/down values like in the case above, 
not each model of these users may show such an construct, so we've maybe 100 models or 10%  "missing rate"
(just an assumption)

now they are converted into actions
1) always // use curve
2) pos // weight:(1.4 weight Up)
3) !pos // weight:(1.4 weight  down)

one more assumption is, that 80% of the failing model configs are using fix/static number values
in case the transfomation would look like
1) always // use curve
2) always // weight (1.4 weight Up))
2) always // differentiation((1-1.4 weight down/1.4 weight up)*100)

all these cases would have been transformed with a correct result without change in ethos, only in the transformation algorithm

so the "trouble cases" would have been significantly reduced

are there other cases, where such a conversion would cause new issues?

**Comment by bsongis-frsky** [comment]
I have changed my mind many times today about this issue.
Right now I am thinking about adding:
- RIGHT => input is positive
- LEFT => input is negative
- TOP => intermediate value is positive
- BOTTOM => intermediate value is negative

**Comment by bsongis-frsky** [comment]
It works now!

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/631da24b-e8e3-442a-a46f-7d9d8e1ade41)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/dc6a4b12-924e-4204-8662-1e72c37829fb)

**Comment by bsongis-frsky** [comment]
It will be part of the next nightlies.

**Comment by Dsrenger** [comment]
You are doing an awesome job!

**Comment by RC-SOAR** [comment]
It seems that there is no sequence of Top/Bottom/Right/Left actions that will reliably emulate weight-up/down, since the second action in the sequence is not looking at the original data.

Suggestion of two possible solutions:

1. split the original mix into two 'ADD' mixes during migration, each with one action.
2. include both up and down options for weight actions
