### ISSUE TITLE
Delay of mixer

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#3645]
More a question than a issue.

If i use a mixer with source ch2 for example. Is there a noticeable delay from the output of this mixer to the output of ch2 direct? so i want to use my mixers from ch17 to ch26 for example and then the first 10 channels can be mapped to channel 17 to 26 with 10 mixers. Or is it possible to add a channel remapper in the system?

**Comment by mawzthefinn** [comment]
No, that should be evaluated in real time, as it's all mixer task. So long as you don't proxy through a VAR, there will be no delay.

What are you trying to achieve with this?

**Comment by loetefix** [comment]
when i use a template for a helicopter i dont want to change the channeloutput in all mixers for a new model when the channelorder is different. so i can map the channels quick.

**Comment by mawzthefinn** [comment]
You're moving changing the channel output in 6-10 mixers to changing the channel input in 6-10 mixers. I'm not seeing the advantage to doing it this way for this application. Mixing to high channels then mapping function channels to output channels makes the most sense for highly complex programs like one of Mike Shellim's templates.

A Channel remapper Lua would be neat. But it's potentially very complex (as you'd have to know and remap possibly dozens of mixer lines for it to work well)

**Comment by strgaltdel** [comment]
thats exactly what i did with my ethos templates

 ch-14 up to ch-30 are the "reference channels". (8flap glider)
these channels are mapped to the "lower" channels, so that i'm flexible and independent from glider, Rx or RB type

including "helper & input mixer" i have more then 50 channels and maybe 60 mixer in the so called "fat template"
this can be reduced by app 25%  targeting a 4 flap sports e glider

lets say including 40 SF"s and 50 LSW's:

Regarding mixer / LSW / SF processing i'd "zero, nada,null" problems (-;

But you can recognize that it "stresses" the system by adding mid..to ..complex luas.
this wont compromise the mentioned mixer processing (probably priorized) but the lesser time slots for peripheral functionality like luas & sounds can possibly be noticed under some circumstances

**Comment by loetefix** [comment]
ok, thank you all
