### ISSUE TITLE
Yep, -x* -10 = 10x

### ISSUE THREAD

**Issue by Skippydi** [FrSkyRC/ETHOS-Feedback-Community#3681]
Yep, -x* -10 = 10x

That should never work as programmed, because of the negative multiplication line.

_Originally posted by @mawzthefinn in https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3676#issuecomment-2010632713_

That's just math and that's how it works in OTX

**Comment by mawzthefinn** [comment]
> ```
>           Yep, -x* -10 = 10x
> ```
> 
> That should never work as programmed, because of the negative multiplication line.
> 
> _Originally posted by @mawzthefinn in [#3676 (comment)](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3676#issuecomment-2010632713)_
> 
> That's just math and that's how it works in OTX

Don't assume that a mixer flow that works in OTX will necessarily work identically in ETHOS. The mixer processing flow is not identical (although in 1.5 and later, you can arrange the flow so it is the same)

Your previous issue is occurring because the multiplier is applied before the curve due to the order in which you have set them up.
