### ISSUE TITLE
Suite 1.5.3 error

### ISSUE THREAD

**Issue by kvak1** [FrSkyRC/ETHOS-Feedback-Community#3703]
After installation of Suite 1.5.3 (on Win7) and its launch, error message appears. Is not possible to work with it. Karel
![Snap6](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/66553590/e26fbe8f-918f-485b-a4b0-9dba6fc9bcfb)

**Comment by Toffs** [comment]
Hi Karel,
I cannot speak to your direct issue, but please can I implore you to upgrade to Windows 10?

Windows 7 was a fantastic OS on its release in 2009, but 15 years later it’s ridiculously unsafe if on the internet + completely unsupported by any applications you want to use today.
It’s a little like saying to a car mechanic “why can’t I plug in one of those electric charging boxes to my 15 y/o car?”.  The technology and programming has moved on significantly.

In no way does this devalue the greatness of what Win7 was, and I’m sure it still runs programs from that era extremely well - but please recognise it’s not appropriate for modern use.
Win10 will likely run just as well on whatever device you’re using: And, I highly suspect your error above will be fixed also :)

**Comment by FlipAirboost** [comment]
After upgrade ,as usual, the "improved" ethos suite  freeze .

Thank you for your excellent work!

**Comment by kvak1** [comment]
> Hi Karel, I cannot speak to your direct issue, but please can I implore you to upgrade to Windows 10?
> 
> Windows 7 was a fantastic OS on its release in 2009, but 15 years later it’s ridiculously unsafe if on the internet + completely unsupported by any applications you want to use today. It’s a little like saying to a car mechanic “why can’t I plug in one of those electric charging boxes to my 15 y/o car?”. The technology and programming has moved on significantly.
> 
> In no way does this devalue the greatness of what Win7 was, and I’m sure it still runs programs from that area extremely well - but please recognise it’s not appropriate for modern use. Win10 will likely run just as well on whatever device you’re using: And, I highly suspect your error above will be fixed also :)

You are generaly right. But previous version 1.5.2 worked without this problem. I am not aware that version 1.5.3 needs higher vwrsion of Win. Thank you.

**Comment by kvak1** [comment]
> After upgrade ,as usual, the "improved" ethos suite freeze .
> 
> Thank you for your excellent work!

Thank you :)

**Comment by FlipAirboost** [comment]
Same for me .
1.5.1 freeze 
1.5.2 work
1.5.3 freeze
make fun of the customer while you can . 
I'm saying what I think of your equipment in the RC world and I'm probably not the only one.
There is the real world and YouTube and tic Tok.

And for your information my os is win 10.

Regards Philippe

**Comment by Nicholas-Luoyi** [comment]
> Same for me . 1.5.1 freeze 1.5.2 work 1.5.3 freeze make fun of the customer while you can . I'm saying what I think of your equipment in the RC world and I'm probably not the only one. There is the real world and YouTube and tic Tok.
> 
> And for your information my os is win 10.
> 
> Regards Philippe

In 1.5.3. Do you have the same error window with kvak1?

**Comment by Nicholas-Luoyi** [comment]
Please try installing the driver in #3732 before running Suite.

**Comment by FlipAirboost** [comment]
Not exactly.  
Ethos suite not responding and and the blue ring spins endlessly.

What difference if I upgrade my radio with the ethos 1.5.2 suite rather than with 1.5.3?

Why does the frsky server automatically offer me the upgrade to suite 1.5.3 and the github server does not offer it even if I make the request?

Édition	Windows 10 Famille
Version	22H2
Installé le	‎17-‎02-‎24
Build du système d’exploitation	19045.4170
Expérience	Windows Feature Experience Pack 1000.19054.1000.0

**Comment by Nicholas-Luoyi** [comment]
It makes no differences. 1.5.3 just trying to help the users whose Suite is able to running but cannot detect radios

**Comment by kvak1** [comment]
> Please try installing the driver in #3732 before running Suite.

I would like to know if Suite 1.5.3 is step to finishing functionality of Suite generally on win7 or it is error. Suite 1.5.2 works but 1.5.3 gives the error message and stops. Most of advices above speak about upgrading to w10 or install new driver for win10. In my case it is not possible to upgrade - the machine is old and is not reasonable to upgrade - better is new one. Thank you. Karel

**Comment by Toffs** [comment]
Hi Karel, have look over this post by a fellow user with Win 7. Looks pretty similar to your Suite error, maybe?
[https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3766]

I have a 2007 Core 2 Duo with 3GB RAM that runs Win 10 okay for basic tasks. The secret is to use a SSD instead of a Hard Drive.  If you have the ability to upgrade to a SSD, or already have, then you’ll likely find Win 10 will run fine on your current hardware.

**Comment by kvak1** [comment]
> Hi Karel, have look over this post by a fellow user with Win 7. Looks pretty similar to your Suite error, maybe? [https://github.com/[/issues/3766](https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/3766)]
> 
> I have a 2007 Core 2 Duo with 3GB RAM that runs Win 10 okay for basic tasks. The secret is to use a SSD instead of a Hard Drive. If you have the ability to upgrade to a SSD, or already have, then you’ll likely find Win 10 will run fine on your current hardware.

OK. Thanks. Karel

**Comment by kvak1** [comment]
OK. No reaction from FrSky. So it should be said (by FrSky) that Suite is not support on Win7 and is just for Win 8(?) an higher.  Thanks.

**Comment by strgaltdel** [comment]
.. but then it must be stated too, that suit doesn't support Win XP, Win Ultimate, win 98, 95, 3.1,  2.x ...??

My understanding in general is, that an actual Software product has to run on Operation System Revisions which are supported from the OS manufacturer at the time when the Product in the dedicated revision is published.

According to MS actual lifecycle policy, Win10 and Win11 are supported.
(End of support for win10 even is dated on  Oct. 2025!)

as mentioned above, when OS revs were "phased out" from manufacturer since years but the end of supporting this revs by a 3rd party product must be mentioned, where should be the end in history ?
