### ISSUE TITLE
Add  DELTA WINGS menu .

### ISSUE THREAD

**Issue by GIB2A** [FrSkyRC/ETHOS-Feedback-Community#373]
Hello
I suggest adding a DELTA WINGS category in the wings selection in the models menus (airplane and glider).
cordially .

**Comment by TWSreviews** [comment]
I agree..... I have about 7 wings, 5 multi rotor but only 2 gliders.
Would be nice to have a category for wings.
Also when I change the model category please make it so it doesn't delete all the mixes.
All my wings are under glider at the moment by mistake not choice. I can't move them because it wants to delete the mix settings for some reason.

**Comment by mawzthefinn** [comment]
The ability to have  Delta Wings category  has functionally been added with the new model folders function. 

As to the mixer reset in the Edit Model, this is because Heli and Multi  have different core mixer functions and require the reset to not be broken by a change.
