### ISSUE TITLE
Bind Register problems Fw 1.5.X

### ISSUE THREAD

**Issue by seilfly** [FrSkyRC/ETHOS-Feedback-Community#3742]
My problem is that I cannot bind any (**new**) receivers after updating from 1.4.17 to 1.5.0 now 1.5.3
It seems that the X20 will not receive those signals from the receiver. (anny new receiver)
I have tried all different firmwares on the receiver and even installed 1.4.17 on the X20
It is only the receivers that have been bound/registered before that the X20 responds and re-binds.
I mean myself that I have tried everything and I am relatively familiar with my X20 and ETHOS

**Comment by builda1** [comment]
Quick Question, Have you tried Flashing your New receivers with the latest Correct Firmware version VIA CABLE from the TX with all the latest firmware updates as I have encountered bind issues in the past identical to yours and as a last resort I re-Flashed all the new RX.s I had recently bought with the Latest firmware and it fixed all my issues. I can only assume the RX's were flashed with EU instead of FCC firmware (in my case) but regardless It fixed the issue. If you have not tried that yet give it a go, if it works don't forget to do "Over the air" updates with any buried in planes so everything is the same version. Hope it fixes your issue like it did mine :)

**Comment by seilfly** [comment]
Hello and thanks for the good suggestions. I have tried all firmwares that belong to the new and old. As I wrote, I have some experience with FRSKY and have had it for many years. So it's not that.
It is a program/data error that my X20 does not read the binding signals from the receiver.
What I wonder about is whether the wise minds who make the firmware can figure out what the problem is

**Comment by builda1** [comment]
No worries, and I'm glad you said something because I have yet to upgrade my X20S to 1.5 as its my main radio and i do not want to risk anything. I usually wait a month or so with my main radio anc update my X18se sooner and will choose a Sacrificial lamb from my hangar to try with the newer releases before updating the X20S. Interested to see how you get on👍

**Comment by seilfly** [comment]
Hi, the only thing I have concerns about is the lack of binding of new receivers, otherwise the new version of the program (1.5.4) works very well.
I also bought the new one (Twin Lite Pro) and one (TW GR6) before update.
Then everything seemed fine, but after updating to 1.5.x I bought a TW GR8. Then I couldn't get in touch with it.
Then tried other new ones (GRX8) with normal ACCST no, no contact there either. So now I'm a bit worried......?!?

**Comment by builda1** [comment]
I also have a Twin lite S that came with 1.0.4 on from new 
And I had to update the Radio internal module to work with all new TWIN Rx's (which were 1.0.5 when i bought some) and also my TWIN module in my X20S module bay so again, I'm sure you have checked, but just make sure that you have at least internal module firmware 1.0.5 on it too I think it is).
I've been through this issue as well last year and then I decided to be a sucker for punishment and updated every single receiver in every single aircraft....45 models later 😩😂

**Comment by seilfly** [comment]
Hello and thanks for the good suggestions.
I have all receivers updated to the latest firmware.
The transmitter is also updated to the latest firmware
it does not solve the problem !

**Comment by builda1** [comment]
Sorry to hear that hope you manage to get it sorted.

**Comment by builda1** [comment]
> Hello and thanks for the good suggestions.
> 
> I have all receivers updated to the latest firmware.
> 
> The transmitter is also updated to the latest firmware
> 
> it does not solve the problem !

Try tagging Bertrand to the issue if you are still having issues (use the @ symbol and look for bsongis to pop up-either one will get his attention, or the same @ symbol and Mawsthefinn will get you help too). 

I had issues with 1.5.4 corrupting all 40 model files when I went from 1.4.17 but I got it sorted after a few days and some Reading. I notice the Register/bind procedure is slightly different on  the new 1.5.4 but it makes sense once you go thru it and check the manual. Try tagging one of the guys I'm sure somebody will help👍

**Comment by bsongis-frsky** [comment]
No need to tag, I receive all the notifications from here

**Comment by bsongis-frsky** [comment]
Happy that @builda1 has his issue sorted, I though he had switched to Futaba because of me ;)

**Comment by bsongis-frsky** [comment]
The only idea I have with this issue has been already given: different flavour of the RF, EU on one FCC on the other.

**Comment by builda1** [comment]
> Happy that @builda1 has his issue sorted, I though he had switched to Futaba because of me ;)

Maybe I still will....you will never know (or care) lol
