### ISSUE TITLE
Special function -> override channel

### ISSUE THREAD

**Issue by WhiskeyGolf** [FrSkyRC/ETHOS-Feedback-Community#3797]
It would be nice to have a special function with which you can overwrite a channel or another value (I used something like that a lot in OTX)

tnx

**Comment by bsongis-frsky** [comment]
You can use a Free Mix with a "Lock" action to do exactly what you need. And it will be in the right place, the Special Function are not the best choice!

**Comment by WhiskeyGolf** [comment]
I just thought it would be much easier with OTX over an SF. 
In ETHOS you first have to create a freemix, set it to lock, set a max value or an offset and then the mix has to be patched to the respective channel.  
This also makes the mixer page very confusing, as very little information is displayed per strip and you first have to go to edit to see that it is a lock mix.  
But I also understand your point.

**Comment by mawzthefinn** [comment]
For most uses of override that are not locking out mixer stacks, a VAR is far more useful.

One VAR can replace a whole set of Override statements.

**Comment by WhiskeyGolf** [comment]
But how do you use VAR to overwrite a mix without creating an extra mix?  The workaround is even more complicated.

**Comment by mawzthefinn** [comment]
> But how do you use VAR to overwrite a mix without creating an extra mix? The workaround is even more complicated.

There's two common uses for Override SF.

1. Overwriting mixes/locking out mixer stacks. The Lock mixer type replaces this. It's a 1 for 1 replacement (Lock mixer replaces Override SF) and the Lock mixer is grossly superior as it respects your output limits set in Outputs, which override SF does not (one reason why Overrides were dangerous, they could break surfaces because they did not respect endpoint adjustment

2. Sending arbitrary values to a channel without them being tied to Flight Modes. VAR's replace this (used to be VAR mixers, now VAR's as a source for Free Mixes).

In 1.4 and earlier, you could have a source reliably as one value in the VAR mix, so you could have it lock out the regular mixing by switching between static values and sources. I would not do that directly in a VAR today, as they are no longer processed in the mixer task. You can replace with multiple weights in a Free Mix though.

**Comment by WhiskeyGolf** [comment]
Okay, that's exactly how I did it.  That seemed a bit complicated to me, but I can live with the solution. 

It's just about putting complicated stick inputs on switches for inav (Save...)
