### ISSUE TITLE
Multiple servo matching or balancer on single surface

### ISSUE THREAD

**Issue by uragano47812** [FrSkyRC/ETHOS-Feedback-Community#38]
I don't know if it is the right place for asking, but i want to know if there will be a multiple servo matching or balancer on single surface function on Ethos, like a special stock mixer. It will be nice for bigger planes with for example 2 servos on each wing.

**Comment by pstasek** [comment]
That could be achieved only when using a device able to measure the current draw of the receiver battery, such as RB-20/30/40 and displaying that value on the output screen, where you're able to set curves for outputs. The goal would be to set curves of two connected surface servos, so the drawn current is at a minimal level on all input positions and the servos don't fight against each other. 

Not sure how the UI should look like for this functionality though.

As an inspiration, here's how Jeti does this https://youtu.be/-TZ3ezUE0Cg?t=163

**Comment by centertrim** [comment]
There's no need for a device to measure servo current.  The "old school" way (and better way IMHO) is to just remove the screw from the control horn for the second servo you're trying to match up and then adjust the point on the output curve until the moves freely in and out of the control horn.  And then move onto the next point on the curve and repeat until the entire range is perfectly matched.  

The problem I think is that there's not an easy solution to make this easier in the software because with the Input/Mixer/Output framework you have infinite flexibility, but this also means that it's difficult to predict how someone is going to use the functionality to accomplish what they are trying to do.  Ideally, I think the matching for hardware/linkage differences should be done with a custom Output curve on one of the two channels for each aileron (or two output curves on two channels for a 3 servo aileron).  The only really good way to ensure that the matching is done right is to ensure that you only have one single mixer on each channel going straight from the aileron input to the aileron channel outputs with the exact same weight for both mixers.  Then, conceivably the Curve editor could have a couple of things added to help the aileron servo matching process go a lot faster:   

  1) Have an area above the curve editor that allows you to select any input and then override that input to a desired value.  This would let you quickly set the output to the X value for the point on the curve you're trying to adjust.
  2) Have the curve editor show where you are on the curve (X/Y points) for the output that you began editing the curve on.  This would be similar to what you see on the Mixer page.

Keeping in mind that since it's a custom curve, it could be used anywhere in the Inputs/Mixers/Outputs, so this idea of temporarily overriding an input and "showing where you are on the curve" really only makes sense if you began editing the curve from a specific location (like a channel output view).   Or maybe there should be a special type of "Matching" output curve that can only be applied to a single output, and then those "Matching" curves have the functionality outlined above.

**Comment by mawzthefinn** [comment]
As noted there are well proven methods for balancing in ETHOS, based on the OpenTX curve methods.

That said, there's definitely an opportunity for improvement here, or for a custom Lua script.

**Comment by bsongis-frsky** [comment]
I will close this issue, let's continue the discussion on this new issue, with a proposal from @Nicholas-Luoyi 
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2790
