### ISSUE TITLE
Lua time loops lead to error message

### ISSUE THREAD

**Issue by uj-berlin** [FrSkyRC/ETHOS-Feedback-Community#3850]
I build functional models. I use various switching modules for this. Some differentiate between long and short pulses to trigger switching states. A short pulse is 0.3s, a long pulse is 1.0s. In my case, these pulses are triggered by a Lua widget with virtual buttons. The pulse duration is generated with clock.os() + t and a query loop. This worked well. With the current Lua versions, an error message "Max instructions count reached" now appears. How can I solve this problem?

**Comment by strgaltdel** [comment]
what about let two LSW's create the "time based" impulses and "feed" the LSW's by an source-lua ?


Regarding time based "while ..loops" within Ethos lua
(it's my personal guess, only Bertrand know details)


each lua handler (paint, wakeup...) should be coded under the premise of short runtimes.

My tests two years ago showed that the handlers of a widget were executed "in a closed sequence", meaning that the wakeup handler of one script had to finish before the next one could start.

There was no "parallel processing", so a loop "blocking" for a long time would have a dramatic impact on the performance/cycle times of other scripts.


To make matters worse:
imho the ethos "task scheduler" is based on a (naturally) hierarchical model

,
- maybe something like a "RF DATA" max prio scheduler/task,
- a "very high prio" mixer loop
- a "high prio" LSW/SF loop
- and then comes the rest and Lua


On the other hand, I assume we have some fixed cycle times for RF / mixer / LSW / SF loops, 
that is, the more complex the mixers are, the more LSWs and SFs we have, the less time there is for executing Lua and other things like audio and logging, 
which seem to have the same cycle time / execution loop / handler as the Lua handler.

Anyway, you have less free "time slices" left for execution

and so the "tiny time-based while do loop" will have a significant impact on logging, audio etc. because it generates runtimes that are a factor of 10 higher than a large, complex script would do....

just my assumptions

**Comment by bsongis-frsky** [comment]
@uj-berlin Is your script public? If no would you still send it to me by email / Discord?

**Comment by bsongis-frsky** [comment]
Since 1.5.0 there is a protection against Lua infinite loops, based on the instructions count. If you get this error "Max instructions count reached", it means that you have reached the limit. But perhaps there is a mistake elsewhere and the counter is not reset, for whatever reason. I would need your script (or a portion of it) to reproduce the issue

**Comment by bsongis-frsky** [comment]
It's strange that heavy scripts like Yaapu one don't show this error though!

**Comment by uj-berlin** [comment]
Hello Bertrand,
it is a simple subroutine to implement a wait statement:

local function sleep(s)
    local ntime = os.clock() + s
    repeat until os.clock() > ntime
end

Since 1.5 this produce the error  "Max instructions count reached"

Regards Uwe

**Comment by bsongis-frsky** [comment]
An active wait? But you really want to kill the perfs of your radio? Why do you need such a sleep funtion?

**Comment by uj-berlin** [comment]
Hello,
it is used for switching modules like the [CTI PS4a](https://www.cti-modellbau.de/PS4a-Schaltmodul-4-fach-648.html)
This module is to be operated with a widget with 4 buttons. Button 1 should output pwm 1024 for 1s on the channel, button 2 pwm 1024 for 0.3s, button 3 pwm-1024 for 1s, button 4 pwm -1024 for 0.3s. The module has a memory function, the 4 outputs are controlled by the different length and polarity of the pulses.
The wait function is required to generate the pulse duration.

**Comment by bsongis-frsky** [comment]
You will have to avoid such loops. Perhaps do this instead::
- on button press adjust the output value and store the "end time" = "current time" + "button duration"
- in wakeup() check the "current time"
- if "end time" > 0 and "current time" > "end time" then reset the output value and set "end time" to 0

**Comment by uj-berlin** [comment]
Perfect solution! Thank you very much !!!
