### ISSUE TITLE
"Bind receiver" in flight

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#3855]
Tandem XE, Ethos 1.4.17
MPM iRange, Graupner receiver

A user in the German forum reports that the transmitter reported "receiver bind" **in flight** and then no connection was possible (crash, total loss).

Presumably this is an MPM problem, but what could have caused Ethos to issue this message in flight?

**Comment by bsongis-frsky** [comment]
Obvious quetion ... he was on Model / RF and he pressed the "Bind" button?

**Comment by bsongis-frsky** [comment]
How did the transmitter reported "receiver bind"? Audio? Display?

**Comment by strgaltdel** [comment]
thats's the only info i could find:
(translated)

_Yesterday I had the problem for the first time that I had to rebind the receiver first on one model and then on the other.
Two flights with model 1 were as usual.

Then model two:
1st flight was ok
2nd flight after a few minutes the transmitter suddenly said "Bind receiver"
From then on it was over with controlling - the model was a total loss.
The only thing I noticed afterwards:
Three models had ID 63 as the model in the TandemXE - including the crashed aircraft._

**Comment by Target0815** [comment]
> How did the transmitter reported "receiver bind"? Audio? Display?

Via Audio.

**Comment by sto-online** [comment]
Hi, I am the german user with the crashed Plane
Target0815 postet this issue here - thanks.

If you habe any questions about that topic you can ask.


- Mullti Module is a iRangeX iRX4 lite
- Transmitter is Tandem XE, Ethos 1.4.17
- Receiver is Graupner GR-12 

Informations about the MultiModule:

Reading MULTI-Module via native USB
Reading flash memory ... done

Multi Firmware Version: 1.3.3.20 (STM32F1)
Firmware Target: STM32F103CB (128KB)
Expected Channel Order: AETR
Telemetry Type: OpenTX or erSkyTx (MULTI_TELEMETRY)
Invert Telemetry Enabled: True
Flash from Radio Enabled: True
Bootloader Enabled: True
USB Serial Support: False
Serial Debug Enabled: False

EEPROM Global ID: 0x097D4D14

MULTI-Module read successfully



I used this LUA-File to use the MultiModule with the Transmitter

[main.lua.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15016837/main.lua.txt)


[Es gibt ältere Versionen dieses Beitrags](https://www.frsky-forum.de/index.php?edit-history/&objectType=com.woltlab.wbb.post&objectID=135328)

**Comment by bsongis-frsky** [comment]
And impossible you were on Model / RF and you pressed the ENTER button with the focus on the BIND button?

**Comment by sto-online** [comment]
Hi bgsonig-frsky,

I did not have the RF Menu open. Despite that, the connection was not there anymore. The Model flew about 10 seconds after the audio message "Empfänger binden". After the message there was no connection to the receiver.

I've testet this yesterday with the same Components. 

When I press the bind field on the TandemXE the connection is lost only until the first audio message "Empfänger binden" is over. After that, the Bind Mode is on, but the connection is working as before.
