### ISSUE TITLE
Slow movement through menus after coming back from folder navigation

### ISSUE THREAD

**Issue by Lleston2** [FrSkyRC/ETHOS-Feedback-Community#3861]
I went into the audio folders and after coming out and using the rotary right button.  The movement in screen is slower than the movement of the rotary wheel button. I started noticing the behavior in 1.5.6 in my X18SE

**Comment by bsongis-frsky** [comment]
Would you do a video to show this problem? I think nothing has changed in this area, it would be interesting to know if you feel the same problem in 1.4.X

**Comment by pstasek** [comment]
I noticed similar behaviour when checking logs in the field back in v 1.5.3 on my XE. It was intermittent and I couldn't replicate it to make a video since then. 

Maybe it's because we didn't have much of a reason to browse too much in the File Manager before the Log viewer was implemented, so maybe some issues were always present and we noticed it after the 1.5 upgrade.

**Comment by Lleston2** [comment]
Here is the video
[IMG_1277.MOV.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15026779/IMG_1277.MOV.zip)
