### ISSUE TITLE
Trim Mixers not converting correctly to 1.5.6

### ISSUE THREAD

**Issue by mawzthefinn** [FrSkyRC/ETHOS-Feedback-Community#3870]
Trim mixers are correctly replaced by Trimmers, but a Free Mix with the Trimmers as a source is not provisioned as a replacement for the mixer. 

Just tested, X20 on 1.4.17 FCC, create a new model, create a Trim Mix on Ch9. Update to 1.5.6, an extra trimmer is created, but the mix is deleted so the trim is no longer connected to the channel.

**Comment by Dsrenger** [comment]
Can confirm
Took me a while to find out why my model was "broken" after updating

**Comment by Wolepo** [comment]
The trim can be found in the Trims menu almost at the bottom under Extra trim

**Comment by Dsrenger** [comment]
Yeah, that one gets converted.

But in my case, the extra trim was not connected to a channel anymore, as there was no mix that connected the trim to a channel as the old trim mixer did.

**Comment by Wolepo** [comment]
It could be that this is a new error.

**Comment by bsongis-frsky** [comment]
Yes the radio could create this mix during the conversion, then if it is unused the user can remove it

**Comment by builda1** [comment]
I tried to bring this up but I got shut down so I had to reprogram 80 models over two radios so it's nice to see somebody else have the same problem and it wasn't just me. 

"Was Not my Idea to fix it at all" so I wonder if the same insult gets made to them as I did very unnecessarily

**Comment by Dsrenger** [comment]
Sorry, you just complained in the issue and refused to send model files or state what specificly broke.

You just complained that everything broke. What should a developer do with this information. In this Issue you see how it should be done. 

Analyse why it is not working, make it reproducable, create an issue, best with a model file to show off.
If theres a problem where you are not able to analyze why it broke, just open an issue and attach the model file (of the old version), so other people, like interessted users or the developers, can analyze what the issue is.

If you just want to complain, thats what forums are for ;) 

And now we should concentrate on help to make Ethos the best system out there...(thanks Bertrand, you are doing an outstanding job)

**Comment by builda1** [comment]
And that is exactly why I do not post issues here because if I don't talk like I'm speaking in C++ or Python nobody wants to even pay attention. If I treated people in the aviation engineering industry with the same kind of responses that I got from you guys when people were asking me things or trying to communicate something to me and make a suggestion I wouldn't have insulted them. Anyway it doesn't matter because it's not my problem I fixed mine-and I didn't complain I made a suggestion that perhaps you contemplate the idea of an easy and advanced version of the software (depending on who the user is) because from the manufacturers perspective it is not good for them to have a radio that is too complicated for customers to program. if people saw my constructive criticism as bitching that their problem. Anyway just for the record I'm not complaining I am just pleased to see that somebody else has raised this issue in the language of C++ or python or whatever it is and suddenly it is getting fixed. Personally I don't know why the trim mix could not have just been left in there as well but I'm not a programmer and it seems common sense by anyone who is not "in the club" as it were is treated quite badly by people who are supposed to be professionals. 

I'm sure it will be sorted out, I spent a whole week fixing my radios because of this, but it was actually a good thing because I learned a little bit more about a few features so it was a big win for me at the end of the day I've got nothing to complain about👍 have a good day everyone. no offence or malice of any kind is directed at anyone intentionally or otherwise, but I can't be held responsible for what people think.

**Comment by builda1** [comment]
> Sorry, you just complained in the issue and refused to send model files or state what specificly broke.
> 
> 
> 
> You just complained that everything broke. What should a developer do with this information. In this Issue you see how it should be done. 
> 
> 
> 
> Analyse why it is not working, make it reproducable, create an issue, best with a model file to show off.
> 
> If theres a problem where you are not able to analyze why it broke, just open an issue and attach the model file (of the old version), so other people, like interessted users or the developers, can analyze what the issue is.
> 
> 
> 
> If you just want to complain, thats what forums are for ;) 
> 
> 
> 
> And now we should concentrate on help to make Ethos the best system out there...(thanks Bertrand, you are doing an outstanding job)

Again I am always very quick to thank Bertrand and the developers for all their hard work, regardless of my issues-the very very few times I might say something, but the insult destroyed any possibility of me helping. Anyway I concur the developers do a very good job I certainly couldn't do it myself and I am the 1st to admit that, I'm sure he will rectify the problem in due course👍

**Comment by bsongis-frsky** [comment]
@mawzthefinn agreed that it should be "Full Range"?

Otherwise it will be limited to 25%

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/0bed0bc1-28ef-4445-b2f2-ce95deaba02c)

**Comment by pstasek** [comment]
Yes, please go full range as we can use that as regular input, for a gyro gain as an example.

**Comment by mawzthefinn** [comment]
Agreed, should be Full Range. Behaviour needs to be the same as 1.4.17 Trim Mixer at the channel to avoid breaking.

**Comment by mawzthefinn** [comment]
> Yes, please go full range as we can use that as regular input, for a gyro gain as an example.

Note this is for the conversion, you can already select Full Range for mixers you are building yourself from Trim sources.

But the old Trim Mixer was full range, so the conversion should be too.

**Comment by bsongis-frsky** [comment]
> The old Trim Mixer was full range, so the conversion should be too.

Exact

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/9550bb4f-2dcf-4e17-a276-ac22b8f25e2c)
