### ISSUE TITLE
Easy screen (or easy fine tune screen)

### ISSUE THREAD

**Issue by Flaperon88** [FrSkyRC/ETHOS-Feedback-Community#3901]
Hello,
Here is one idea for fine tuning the model setting especially when using phase of flight , but not only....
This screen exist on the MX20 Graupner transmitter. He is very useful, but basic. Here is one enhanced screen.
See picture for description.
The goal is  to adjust the output and fine tune the settings easily on the field.

Brand new user of X20. I still need to deepen my Ethos knowledge.
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/166108558/fe910767-701e-4482-881e-5b73f35e6865)

[Easy screen.xlsx](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15081564/Easy.screen.xlsx)

Up to you to decide if this idea can enhance the Ethos soft.

Best regards

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/166108558/9e8f1200-4b50-44c5-8fbb-d177fb96aa3d)

**Comment by bsongis-frsky** [comment]
But if the easy way is selected, it is very limited! I am sure that everybody will like to add things to this easy way, and at the end it will become very complex!

**Comment by spoke2570** [comment]
I have not used this one, but In other applications I have used a graphical quick chart that bypassed a lot of the complex questions in addition to a the normal detailed sub menus. ..like a shortcut for all the things put together by the new model wizard, with some limited access to output and trim settings.

**Comment by spoke2570** [comment]
I am not sure it could fit on an X20 screen very well, but it sure would be a nice in Suite.

**Comment by strgaltdel** [comment]
This type of table only works with ready-made templates with fixed channel assignments.
This was typical for e.g. classic graupner or Futaba systems.

the result of the wizards can be seen as a template
But Ethos has a different, freer and more flexible basic principle
But even beginners who use wizards have the option of free channel selection.
This makes such a table obsolete, imho

In addition, the recommendations are only average values that refer to a specific model type with a specific construction method.
A current competition model as described in the table, today, would use offsets and other values.


 
my proposal would be to add a something like a "best practice" description into the ethos manual

perhaps the topic should not focus on “simple spreadsheed” but on a “best practice ethos blueprint”

the new 1.5 offers a big and unique advantage over all other operating systems:
the number of variables that can represent the above settings
(weights / offsets / positions etc.)
 
My suggestion would be to include something like a “best practice” description in the Ethos manual
one topic could be how to use variables for user-friendly model settings
The idea could be to differentiate between the mixer logic, which is the complicated part, and the setting via var's.

That way all the settings like weights, expo, diff, offsets, ratios etc are completely independent of how the mixer works and the user can just focus on the vars when fine tuning the setup.

(there would be even no need to "undestand" the mixer logic, but this would not be a desirable state for the user)

An “official” Ethos manual could provide recommendations for naming variables.
If users used these naming conventions, it would be easier to exchange templates, as users would only need to change the variables in a first step, and due to the standardized names it would be easy to understand which variable they need to set to get a certain flap rate.

For simple templates, value recommendations could be given like in the spreadsheet above...

**Comment by Flaperon88** [comment]
I understand the Ethos is completly diffrent off Graupner or Futaba, but after a lot of years in competition, what competitor want is one easy way to fine tune the model on the field. 
When fine tuning is done, i forget completly how i did it.  This is a bit my question with my X20. How to remember settings made 6 months or 1 year ago ?
I am a brand new user of X20. I still need to deepen my Ethos knowledge...

**Comment by strgaltdel** [comment]
what i meant,
the Vars are ease to use, "one pane of glass"
and even after 3 years you would know that the var "diff" changes your aileron differentiation (-;

do you know mike shellims F3F / F3B .. etc templates ?
https://rc-soar.com/ethos/

widely used by competition pilots

**Comment by Flaperon88** [comment]
Will have a look on that  :-)

**Comment by Flaperon88** [comment]
> But if the easy way is selected, it is very limited! I am sure that everybody will like to add things to this easy way, and at the end it will become very complex!

'easy screen' or what the name can be, is not there to do all the model settings. The settings will be done as they are now. it's just a way to 'fine tune' the seettings allready realized without going deeply into all the mix's screen or menu, one by one.

**Comment by Flaperon88** [comment]
> what i meant, the Vars are ease to use, "one pane of glass" and even after 3 years you would know that the var "diff" changes your aileron differentiation (-;
> 
> do you know mike shellims F3F / F3B .. etc templates ? https://rc-soar.com/ethos/
> 
> widely used by competition pilots

I did have a look. It's interresting, but you allways need the templates in whatever form to do your fine tune.

**Comment by strgaltdel** [comment]
i must confess that i never used a graupner system.

actually, in a standard model (4flaps), i use app. 40 vars for fine tuning
a 8 flap gilder needs app 55
some vars deliver different values dependent on flight mode,
so there are app 60..80 values at minimium,
all easy to access in the var menu, not by browsing in more or less complex mixer menues, or via luas

for the "most wanted" 10 vars i've a lua for inflight trim, including switching between the old/new setup

dependent on model type, i've 4 different channel assignments, doesn"t matter because a var is the "single point of truth"

at the moment i don't get it where the "easy setup" would be more powerful then the existing methods that Ethos can offer because i never used it (graupner / easy access).
how would the graupner UI support these bunch of settings in the easy sheet / menue?
how can i fintune the main items during flight, does it support the flight modes ?

thanks 
udo

**Comment by Flaperon88** [comment]
> i must confess that i never used a graupner system.
> 
> actually, in a standard model (4flaps), i use app. 40 vars for fine tuning a 8 flap gilder needs app 55 some vars deliver different values dependent on flight mode, so there are app 60..80 values at minimium, all easy to access in the var menu, not by browsing in more or less complex mixer menues, or via luas
> 
> for the "most wanted" 10 vars i've a lua for inflight trim, including switching between the old/new setup
> 
> dependent on model type, i've 4 different channel assignments, doesn"t matter because a var is the "single point of truth"
> 
> at the moment i don't get it where the "easy setup" would be more powerful then the existing methods that Ethos can offer because i never used it (graupner / easy access). how would the graupner UI support these bunch of settings in the easy sheet / menue? how can i fintune the main items during flight, does it support the flight modes ?
> 
> thanks udo

Hello, nice to discuss on this topic and share experience
Do not focus on the name. the goal is to have a screen where it's easy to do some ajustment without going deeply in the diverse menu.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/166108558/291e4e5b-4b3d-4cd7-b294-e38b386396bc)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/166108558/2aed451b-875d-486b-b8cb-826b1426d27c)


Cheers

**Comment by strgaltdel** [comment]
In fact, I focused on a screen of sorts that displayed "best practice" rates/weightings as a suggestion for an appropriate menu..,
and these suggestions would be "tied" to fixed channel orders....

So you are simply concerned with a "simpler" setup?
It doesn't matter how it works, but it should provide a quick way to change some tuning parameters, right?

For example, I'm working on a widget / script that allows me to easily migrate (even complex) models from openTx or tune them locally without needing dozens of clicks/scrolls  
(I have already mentioned the working method above)

this could be something that points in your direction

basically I am in the area of interest with two touch's:
let's say i want to change mixing rates for butterfly / camber etc on the flap elevatot,
I have to touch (1) the tail and (2) the elevator 
then I can set the desired variables

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/4fb11fac-06c6-4262-980b-23f6cf8c5d8b)



when i want to change on wing flaps the snapflap rates, i have to touch
(1) wing (2) snapflap

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/1637c1ee-5b3c-46be-b9a2-e8b6561dded2)

of course there is a trade off:
individual configuration of the widget (like 4..5 different types of screens for any sort of model types a user owns) is some tipping work...
it is the way i wanted to do, we are individuals and everyone has at least slightly different approaches.

but ist demonstrates one of the principles in Ethos.
there are enough methods ( in this case combinations of Vars, lua scripting and a "forms" library) available so that a user can  implement his own ideas.

the requirement above is yours ?

my advice:
- don't use direct values in mixers for values, that must be trimmed or change in different FM's, but use Vars, so no need for browsing mixers
- read lothars manual, especially about "repurpose" function:
repurpose means, you can define a condition(a switch position) that triggers the trim to change Vars instead of the main function, so you can much more easily trim 2..3 vars inflight.

regards
udo

**Comment by Flaperon88** [comment]
> In fact, I focused on a screen of sorts that displayed "best practice" rates/weightings as a suggestion for an appropriate menu.., and these suggestions would be "tied" to fixed channel orders....
> 
> So you are simply concerned with a "simpler" setup? It doesn't matter how it works, but it should provide a quick way to change some tuning parameters, right?
> 
> For example, I'm working on a widget / script that allows me to easily migrate (even complex) models from openTx or tune them locally without needing dozens of clicks/scrolls (I have already mentioned the working method above)
> 
> this could be something that points in your direction
> 
> basically I am in the area of interest with two touch's: let's say i want to change mixing rates for butterfly / camber etc on the flap elevatot, I have to touch (1) the tail and (2) the elevator then I can set the desired variables
> 
> ![grafik](https://private-user-images.githubusercontent.com/20392683/325497235-4fb11fac-06c6-4262-980b-23f6cf8c5d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTY2ODUsIm5iZiI6MTcxNDExNjM4NSwicGF0aCI6Ii8yMDM5MjY4My8zMjU0OTcyMzUtNGZiMTFmYWMtMDZjNi00MjYyLTk4MGItMjNmNmNmOGM1ZDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA3MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlODhkZTNjYmRmOGRlYjAxZGQyNTRlY2ZmYmNkYWE2MDRlMTNmNTc0ZGQzMzdlYmMzY2ExNGExMDljODdmYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fCDzutT5sRqy432zXadT35S68gSnTBIqzy8AvPpjQmI)
> 
> when i want to change on wing flaps the snapflap rates, i have to touch (1) wing (2) snapflap
> 
> ![grafik](https://private-user-images.githubusercontent.com/20392683/325497386-1637c1ee-5b3c-46be-b9a2-e8b6561dded2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTY2ODUsIm5iZiI6MTcxNDExNjM4NSwicGF0aCI6Ii8yMDM5MjY4My8zMjU0OTczODYtMTYzN2MxZWUtNWIzYy00NmJlLWI5YTItZThiNjU2MWRkZWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA3MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiODcwN2RmNmI3ZWZkMjY0ODUyOTVhNzBjMGU3ZGIzYzA1ODc0YTZjNWU3MDZlZjdiNzk3NTM0MTJhMzE2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M0ktfw-mi2_aOu6dNPBmnL7lNYfzSeFyYQsVhqTLPcM)
> 
> of course there is a trade off: individual configuration of the widget (like 4..5 different types of screens for any sort of model types a user owns) is some tipping work... it is the way i wanted to do, we are individuals and everyone has at least slightly different approaches.
> 
> but ist demonstrates one of the principles in Ethos. there are enough methods ( in this case combinations of Vars, lua scripting and a "forms" library) available so that a user can implement his own ideas.
> 
> the requirement above is yours ?
> 
> my advice:
> 
> * don't use direct values in mixers for values, that must be trimmed or change in different FM's, but use Vars, so no need for browsing mixers
> * read lothars manual, especially about "repurpose" function:
>   repurpose means, you can define a condition(a switch position) that triggers the trim to change Vars instead of the main function, so you can much more easily trim 2..3 vars inflight.
> 
> regards udo

_So you are simply concerned with a "simpler" setup?_   Correct, simpler way to adjust some basic settings
_It doesn't matter how it works, but it should provide a quick way to change some tuning parameters, right?_  Yes. I was thinking this kind of table because you have a direct access and a global overview of the settings and waht to do.
For exemple, you want to give more camber to your flaps to test it , then you add directly some % to the concerned output (channel)  ;  You want to reduce the Ailreon differential --> reduce some % on the Ail diff output.
This screen is just a help (or easy way) for fine tune the model on the field.

Your way to direct access to some settings is very interesting, 
On what i see and understand, you are going deeper then my idea, as counter part you need to devellop one script (or more than one) by type of model.
On my side, one screen is common to all model, where you can set ' offest/  rate (or course)/ limit/ expo / diff '. These settings are the basic of 'all models'; for the mixing or going deeper in the setting you go via the existing menus.

Thanks to your advice. 
I am far away in my Ethos knowledge. 
When changing sytem, you tend allways for refer at what you know.... 

My concern for now is to migrate my models on my X20 and Ethos syst, and be sure i have the same settings and behaviour.
At the first time, i wanted to keep my Graupner recievers and use it with the multiprotocol modul. Like that i can use indifferently my FrSky TX or My Graupner TX during the transfer and to fly.  That's working (in my workshop) , unfortunatly the telemetry isn't yet ready (need Ethos LUA script for Graupner RX).
