### ISSUE TITLE
Lua support for ELRS 3.4.0

### ISSUE THREAD

**Issue by kakashi2018** [FrSkyRC/ETHOS-Feedback-Community#4052]
Seeing errors near baud rate after updating elrs to 3.4.0 on my x20 radio. Not sure what has changed but can we get the support for latest elrs update?

**Comment by glipski50** [comment]
I am usung the X14 / Ethos 1.5.8 and the BetaFPV ELRS Tx nano with 3.4.0. No problems at all, I can setup baud rate between 400 k and 5.25 M without any issue. Fo you use the latest lua script from the 1.5.8?

**Comment by robthomson** [comment]
Has your ethos also been updated?  What where you on before

**Comment by kakashi2018** [comment]
currently using 1.5.8 on ethos with latest lua downloaded from 1.5 branch. It was working with no issues when using elrs 3.3.2. Updating to 3.4.0, Iam seeing errors under baud rate. I have tried it with radio master ranger and happymodel slim pro modules and they both showing errors on 3.4.0. Some thing might have changed on elrs side that we need to fix in ethos or in lua fille.

**Comment by robthomson** [comment]
Suspicion here is that the elrs module is taking longer to initialize than it used to.

It does not seem to cause any issues in running.

**Comment by rburrow87** [comment]
Yeah I noticed this too after going to ELRS 3.4. It has not caused any issues, it just seems to take an extra second or two before the module is ready after starting the TX.

**Comment by robthomson** [comment]
So 3.3.2 has no errors at all.

Have to question here...  the request is to make ETHOS support ELRS.. yet clearly it seems that maybe ELRS have changed something?

Do we know if same issues occur for example on spectrum/crsf implementation's?

**Comment by doloebig** [comment]
> Yeah I noticed this too after going to ELRS 3.4. It has not caused any issues, it just seems to take an extra second or two before the module is ready after starting the TX.

my observation too

**Comment by mawzthefinn** [comment]
I suspect #4010 is the same underlying issue. 

I'm still running 3.3.x on my ELRS stuff with no issues on 1.5.8. Something has to have changed with 3.4.0

**Comment by robthomson** [comment]
Yup.. For sure elrs have changed something.

Has the issue been reported to them?

**Comment by mawzthefinn** [comment]
There's a long connection delay  issue reported here:

https://github.com/ExpressLRS/ExpressLRS/issues/2686

But nothing so far about flaky telemetry/errors.

**Comment by xbutz** [comment]
Same error pattern with X20pro 1.5.8 with Happymodel es24tx slim pro 3.4.0 / 3.4.1

Errors are also displayed.

**Comment by andika207** [comment]
> Yeah I noticed this too after going to ELRS 3.4.

are you sponsored by Radiomaster now ?

**Comment by andika207** [comment]
~~comment removed by bsongis as it brings nothing except fight with @rburrow87~~

**Comment by bsongis** [comment]
@andika207 Please use forums for this kind of comments, or I will have to report abuse to github

**Comment by andika207** [comment]
fight ? abuse ? LOL.
he's flying the newly released Radiomaster flight controller on ELRS so I asked about it.

**Comment by robthomson** [comment]
It not personal - just not relevant to the thread - so best discussed on discord of fb groups.

**Comment by Freshprinc84** [comment]
Hello everyone. I have the same problem with the twin x lite s. Latest frimware from ethos and Happymodel slim pro on 3.4.1.
Baud rate works above 400k but the higher the more errors next to the baud rate. at 400k about 620 and the higher the more. I haven't flown yet because I previously had an x-lite pro and now got the new twin. has anyone already found a solution?

**Comment by Target0815** [comment]
There are probably problems with the baud rate for some transmitters. I have not noticed this with my X18SE, but Twin Lite and ProAW have been mentioned.

Furthermore, with the current LUA script it is not possible to re-map the channels for ELRS PWM receivers, as is possible under EdgeTX with the original LUA script.

**Comment by xbutz** [comment]
X20Pro  Ethos update 1.5.9 Eu and Elrs 3.4.1 Ce_Lbt the errors still exist. 

@bsongis 
is there any news yet?

**Comment by Freshprinc84** [comment]
Push this... does nobody have a solution? I think it's the Lua that needs to be tweaked or a fix in firmware 1.5.8. The 3.4.1 works fine in OpenTX/EdgeTX so it would be nice if the developers would look into this issue.
I know Frsky isn't that interested in working on this because they want to sell their own stuff. But losing their own customers can't be the solution either...

**Comment by Freshprinc84** [comment]
@Target0815 As you can see, many people have the same problem with the X20. It actually works for me. It's just the errors that are displayed that worry me. But X20 users have the same errors.

**Comment by rburrow87** [comment]
I really doubt there's a problem here. The errors are more than likely just because it's trying to talk to the module while it's still booting, and now ELRS 3.4 takes a touch longer to get to the same state as before 🙂 I've been using ELRS as usual and it's working just as well as it did before before ELRS 3.4 released and the error counter was added Ethos.

**Comment by Freshprinc84** [comment]
@rburrow87  Thanks for the answer. I'll test it out in the field. I've already flown a few times at home and couldn't spot any problems. But with a 5" or 7" it's not so great if something goes wrong in the middle of the flight.

**Comment by robthomson** [comment]
Yup.. not caused me any issues flying my end - pretty sure its just the module startup time being longer.

It would be great if the elrs team could confirm this.

**Comment by Freshprinc84** [comment]
The guys from ELRS would love to work on it and help, but since FRSKY doesn't work with them, it's not of interest to them. I also reported the problem to ELRS on the Discord server, but without open communication from FRSKY, it's not possible. Maybe they'll buy an ETHOS radio to test it out, but it's a shame.

**Comment by Freshprinc84** [comment]
deadbyte — heute um 09:04 Uhr (DISCORD)
their ExpressLRS lua is not really the same as the ExpressLRS Lua Script we're using on EdgeTX/OpenTX radios
And they aren't working with anyone in the dev team to ensure it works on every version of the expressLRS firmware

**Comment by Freshprinc84** [comment]
deadbyte — heute um 09:32 Uhr (DISCORD)

-me: I think, as I see it, it's really just about the startup communication, which has been delayed since 3.4.1.
-The errors weren't there before.

this is the hardest part to check as none of the dev team has any ethos handsets. 

And the Ethos source code isn't publicly accessible, afaik, so checking will be tedious. 

You'd be lucky if someone in the dev team would be willing to fork their own cash to get a unit (which can be just part of the  solution, since there are sevaral ethos radios now) not to mention the time to check.

**Comment by doloebig** [comment]
i can confirm, there is no problems during flight. 
X14 Ehtos 1.5.8 ERLS 3.4.0 LPT

**Comment by bsongis** [comment]
I will contact them, when time allows!

**Comment by bsongis** [comment]
Why there is mention to Lua here, I don't think it is related to Lua, but rather the module startup time, right?

**Comment by robthomson** [comment]
I 

> The guys from ELRS would love to work on it and help, but since FRSKY doesn't work with them, it's not of interest to them. I also reported the problem to ELRS on the Discord server, but without open communication from FRSKY, it's not possible. Maybe they'll buy an ETHOS radio to test it out, but it's a shame.

Maybe they should reach out and discuss on here?  Frsky have always in my experience had open communication and are very happy to help.

**Comment by Freshprinc84** [comment]
I believe that this is not the case and that there will be problems in the future. The devs at ELRS would be open to it but FRSKY has closed the door for them. They say so too, so unfortunately it is a real shame. It would be such an enrichment and would also help to increase sales, but it is what it is

**Comment by Freshprinc84** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/discussions/4107

Go an Vote, so that we see how important it is

**Comment by bsongis-frsky** [comment]
Done :)

**Comment by Target0815** [comment]
> Why there is mention to Lua here, I don't think it is related to Lua, but rather the module startup time, right?

The errors mentioned with some transmitters are not due to the LUA but rather to Ethos. My X18SE, for example, also runs with ELRS 3.4.1 without errors. There seem to be differences between the transmitters.

As far as the LUA is concerned, the Ethos LUA does not contain all the functions that are included in the EdgeTX LUA. I have already tried to synchronise the functions myself, but LUA debugging is a pain if you are used to Visual Studio (code) for other projects ...

**Comment by dsolaray** [comment]
> The guys from ELRS would love to work on it and help, but since FRSKY doesn't work with them, it's not of interest to them. 
> The devs at ELRS would be open to it but FRSKY has closed the door for them. They say so too, so unfortunately it is a real shame. 

The Xlite's ELRS compatible mode is stuck on version 2.3 
since there is not trade agreement or cooperation between ELRS and FRSKY team I suspect the code was stolen or rever engineered as they did with their FASST compatible receivers because it's being used in a closed source system

The 4 in 1 module is made by FRSKY but they can't sell it under FRSKY brand because it's not FCC certified and they don't want to get into trouble because it's not legal to use

**Comment by robthomson** [comment]
How do you jump to assuming code is stolen?

This is stupid paranoia fed my ignorant masses.

It's far simpler to consider that the codenwaa built as being compatable with elrs - and with the rate that elrs release changes it has become impossible for Frsky to keep up making it compatable.

Far simpler to put elrs support into an external module and do it that way.

**Comment by doloebig** [comment]
this maybe right or wrong but i do not solve our technical problem!

Regards 
Doro

**Comment by dsolaray** [comment]
>  the rate that elrs release changes it has become impossible for Frsky to keep up making it compatable.

LOL so the excuse now is that ELRS changes rate is way too fast because you think FRSKY devs are dumbs who didn't know about this ahead of time ?

**Comment by dsolaray** [comment]
> How do you jump to assuming code is stolen?

The code was made available to the public so it's easier to just stole it rather than reverse engineer it as they do with MPM or Futaba FASST protocols

**Comment by dsolaray** [comment]
> How do you jump to assuming code is stolen?

The code was made available to the public so it's easier to just steal it rather than reverse engineer it as they do with MPM or Futaba FASST protocols

**Comment by robthomson** [comment]
Speculation, heresay..  Completely impossible to back up a statement like that. 

Kind of days more about yourself tbh.

**Comment by doloebig** [comment]
is there any news or even better a solution this  issue ?

**Comment by rburrow87** [comment]
The solution is to just ignore the error counter until it is removed :) The error count climbing immediately after boot is no problem other than it scaring people when they look at it.

**Comment by bsongis-frsky** [comment]
Errors counter removed in 1.5.10
