### ISSUE TITLE
Lua widget key '' not found warning after update to 1.5.8

### ISSUE THREAD

**Issue by mrskynavi** [FrSkyRC/ETHOS-Feedback-Community#4079]
After updating to version 1.5.8 and also 1.5.9 I always have the above mentioned warning. The warning is present irrespective of selected model. Also creating a new model does not solve the problem. Any ideas how to get rid of this warning.

**Comment by mawzthefinn** [comment]
1.5.8 introduced better error reporting for Lua scripts.

You have a lua widget loaded onto the radio with a syntax error. Remove it, or fix it to resolve.

**Comment by mrskynavi** [comment]
Thanks for the hint. Deleting all the scripts on my radio did not help, but removing all models fixed the issue. It seems that there was a model with a faulty definition.

**Comment by mrskynavi** [comment]
Thanks for the hint. Deleting all the scripts on my radio did not help, but removing all models fixed the issue. It seems that there was a model with a faulty definition.

**Comment by bsongis-frsky** [comment]
Your current model uses a Lua script which has been removed from the radio. You have either to restore this script, or to remove the use of this script from your model. It should not be done automatically as it is a real error. 1.5.8 shows better this error which perhaps you have since long without knowing it!

**Comment by fdm225** [comment]
I have checked all of the scripts on the model and have this issue on all of my models.  are you suggesting that the script is continuing to execute even though it is not present? I have literally gone through all of the widgets in use and checked them all to ensure that they are valid; if it requires that I delete the model and start from scratch it's a bug in the implementation or at a minimum a not very well thought out feature as it does not give enough detail for the user to actually fix.  Please re-open (or I will) this issue as it is absolutely not fixed in my opinion

**Comment by bsongis-frsky** [comment]
It's not necessary to check all the models, just the current model.
You should paste your model here so that I can check it for you

**Comment by fdm225** [comment]
Hi Bertrand,
I have found the issue on the single model, but it's persistent across every model I have (20-30 at this point) due to cloning of that single model.  The error is coming from the scenario where I have a screen with a grid of 9 widgets and 3 of them are left blank (a widget was never selected); so the only solution is to go and touch every model and setup the blank widgets so that they have a empty text box or the like.  I can get if there is an actual script error, e.g. the script doesn't have a key but in this case the error is that a widget was never assigned to the screen's slot.  At a minimum it would be helpful to know that it's the fact that the widget slot has not been filled in vs a generic error such as invalid widget key.  Hitting out of the park would be to list the screen number and widget slot in the error code so we do not have to actually look at each and every location on the 5 screens of widgets I have per model.

On a related note, changes like these (where I have to do it between 20-40 times) would be a lot simpler if there were a companion app; is that still in the works?  The radio UI is super functional but slow.  I have the x20 pro and it can be painful swiping between screens and scrolling due to the lag.  I have worked as a software engineer for 26 years and am all for new features but it seems that we will get to a point were (with the smaller embedded micros in these radios) navigation will be too painful causing the need for a companion app to be critical (IMHO).

if my tone before was harsh I apologize, letting frustrations from other parts of life enter into what should be a civil conversation  around a great piece of software (ETHOS is fantastic btw).

dave
