### ISSUE TITLE
addTextButton() crashes lua

### ISSUE THREAD

**Issue by dwheeld** [FrSkyRC/ETHOS-Feedback-Community#4081]
I may have discovered a bug in addTextButton(). While testing it on the X20S sim, along side a script using touch screen code, I left it running while going for a walk. When I returned, both widgets had crashed. I then removed the addTextButton() code from the widget it was being tested in (an old faithful widget called Lua Gauge) which then ran continuously for over 3 hours without crashing. After adding the code back into the widget, it would again crash at around the 1 hour mark of continuous running. I then tested with no other widgets running, and again it crashed at a little over 1 hour.

I have included a video showing my testing, along with both widgets, in the attached zip file. 

Testing performed on X20S 1.5.8 sim. Not tested on transmitter.

If I have implemented the code improperly, please explain my error and I will close this issue.

[addTextButton crashes lua 2.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15449313/addTextButton.crashes.lua.2.zip)

**Comment by dwheeld** [comment]
EDIT:
Still crashes with the change mentioned below.

~~Could~~ ~~have~~ ~~found~~ ~~my~~ ~~mistake.~~ ~~Should~~ ~~only~~ ~~use~~ ~~'form.create()'~~ ~~1~~ ~~time~~ ~~instead~~ ~~of~~ ~~during~~ ~~each~~ ~~time~~ ~~through~~ ~~wakeup().~~ ~~Will~~ ~~close~~ ~~issue~~ ~~if~~ ~~testing~~ ~~is~~ ~~successful.~~

~~if~~ ~~widget.ini~~ ~~==~~ ~~0~~ ~~then~~
     ~~form.create()~~
     ~~widget.ini~~ ~~=~~ ~~1~~
~~end~~

**Comment by strgaltdel** [comment]
Hello!

I took a quick look at your script:

(1)
each call to the addTextButton() method creates a new object that requires mem resources.
In each wakeup loop, new “button objects” are created/added, so your widget will create a mem overflow after some time

(2)
You call lcd.invalidate() even in the paint handler.
as described a few weeks ago on rcg, lcd.invalidate triggers the paint handler (e.g. from wakeup), it should not be used in the paint handler itself

(3)
i would suggest to discuss lua coding problems in our special rcg thread, so that info and exchange of experiences can be passed on to a larger “audience”. 

even if a possible lua bug is discovered, it could be “cross-checked” there.

regards 
Udo

**Comment by dwheeld** [comment]
Thanks strgaltdel. I placed it here because I felt I had found a bug in 'addTextButton()'. It now appears that I was using it wrong. It eventually used up too much memory when it was, as you stated, called repeatedly. 

I noticed this morning that 'form.create()' has been deprecated, and the only way I have seen 'addTextButton()' used was after 'form.create()', so it looks like the issue is moot for 2 reasons. 

I will close the issue and take it to the discussion area if I decide to pursue it.
