### ISSUE TITLE
X18SE - Layout problem with external module

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#4091]
X18SE, Ethos 1.5.7, ExpressLRS module

New model, select external module, ELRS is to be elected, "Type"-field mismatch:

![screenshot-2024-05-27-44912](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/31627548/27b4bbba-4176-4c8e-9937-cb635be67b06)

**Comment by bsongis-frsky** [comment]
I will change the layout for this screen, so that we don't loose space for fields which have no meaning:

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/a34283a9-5050-4944-bcee-203be2906adf)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/279f39fd-0056-4f05-997f-96810e54b881)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/063fc59b-54f8-472b-9f27-cc7f99b6547c)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/5f301c12-ff3b-45e7-a3f3-22be10545efe)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/26c25e52-dd11-4901-9aad-c8e9b88f3b19)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/f91e8284-668b-4260-b2f7-436dc30886de)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/c586b3d0-5937-46b7-a4d7-a6ef32a0ef1d)
