### ISSUE TITLE
Special Functions disappearing 

### ISSUE THREAD

**Issue by ninodesposati** [FrSkyRC/ETHOS-Feedback-Community#4121]
90% of my Special Functions have disappeared  after upgrading to 1.5 and above. What’s up with that. I had over 20 models programmed. Also lots of the model needed to be re binded. Those special function took a long time to develop and I spent lots of time creating them. Is there a way to copy all of them for other models? This isn’t right.

**Comment by hrenz** [comment]
use your backup

**Comment by strgaltdel** [comment]
i believe this is the first report of a complete loss of sf since 1.5 introduction

unfortunately no details are given to get an "picture" of the problem

source version
target version
types of lost sfs
example of an original template causing the update problem
.....



i think there used to be problems with play audio sfs when the new audio system was not initialized correctly under 1.5, but i have never heard of a complete deletion of an sf

**Comment by bsongis-frsky** [comment]
Do you have a backup of one of those models to understand how it is possible?

**Comment by ninodesposati** [comment]
Yes I do. How do I find and install the SF files onto the current model. Thanks


Nino Desposati
Sent from my iPhone
203-501-8848
***@***.***

On Jun 3, 2024, at 04:03, Bertrand Songis @ FrSky ***@***.***> wrote:

﻿

Do you have a backup of one of those models to understand how it is possible?

**Comment by bsongis-frsky** [comment]
Would you paste the backup of your model file so that I can check why the update failed?
