### ISSUE TITLE
V1.5.6 and higher  Some RSSI warnings are not played, think some filenames are too long (>32 characters) 

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#4150]
V1.5.6 and higher 
Some RSSI warnings are not played, neither in German nor in English
ok on simulator, ok at X20s file manager play sound
but not on XE not on X20Pro, 
Test with tandem receiver, Test with file manager at Tx
think some filenames are too long (>32 characters)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/6217896/06acf703-3ac2-4cd0-9a81-c6c34d7eae70)

**Comment by pmullen503** [comment]
Hmmm, been trying to track down an issue with 900mHz. Logs show RSSI value down in the 20s but no warnings ever played. I wonder if this could be why. (Radio was on 1.5.9) 

Everything else was fine, turned out to be a receiver antenna issue.

**Comment by hrenz** [comment]
perhaps directory names and file names together are too long`?

SD/audio/de/default/system/namexyz.wav  tool long

**Comment by bsongis-frsky** [comment]
Your audio file is on local storage?

**Comment by bsongis-frsky** [comment]
64 chars seems the max? Ethos allows 63 ...
If we are right, then 
`SD:/audio/en/default/system/rssi-int900m-critical-warning.wav` ... [OK]
`RADIO:/audio/en/default/system/rssi-int2g4-critical-warning.wav` ... [OK]
`RADIO:/audio/en/default/system/rssi-int900m-critical-warning.wav` ... [KO]

**Comment by EngelMT** [comment]
The idea that the problem is caused by paths that are too long came up in our forum because a customer has the problem that no warning is issued when the value falls below the warning threshold.

I have just done some testing and believe that the problem is not just due to the paths being too long. I used a TDSR-12 and also set the warning thresholds to 100. Then shielded the antennas to get below 100. There is no warning. However, if I do this with an X8R, for example, the warning appears immediately.

There seems to be another problem here. @bsongis-frsky Please check this.

**Comment by bsongis** [comment]
Perhaps hrenz will tell us if my fix is enough tomorrow. It seems to me that his first analysis was right, the filename was 64 chars long when the limit was 63

**Comment by EngelMT** [comment]
O.k. let us wait. But why it works with a X8R but not with a TD receiver?
