### ISSUE TITLE
MIXER Plane: Flaps=>Elev, slow up or slow down is not possible!

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4151]
MIXER Plane: Flaps=>Elev, slow up or slow down is not possible!
Problem when using slow down (up) for Flaps and it is not possible for Elevator compensation!
If I use a different curve for Flaps and Compensation,
I still need a separate mixer for compensation.

**Comment by strgaltdel** [comment]
I can use slow functions in free  mixers  without any problems
(slowed elevator compensation when motor starts on an e-glider)

![grafik](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/8a5351e7-1e38-4701-9e9d-ce6440e93d1b)

maybe you show a screenshot of your implementation ?

By the way
if you only have "a few percent weight" for the elev compensation, you need a large "deceleration value" to achieve a remarkable effect, because the parameter is intended for the entire travel!

**Comment by philippe-warnotte** [comment]
Ok, I understood that. For the Free Mixer I found a submenu in "actions" with a slow option like you. 
But in the Mixer plane: "Flaps=>Elev, there are no "actions" and no "slow" option!
![screenshot-2024-06-10-49396](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/165813792/6ce750b0-dd94-4b7f-9efd-9e52d46dad3e)

**Comment by mawzthefinn** [comment]
You need to use the output of your flaps mixer as the input to your Flaps->Ele Mixer. Then it will track the slow settings in the flaps mixer.

Do NOT use the input to the flaps mixer as the input to Flaps->Ele, because then you are mixing that input, not flaps, to ele
