### ISSUE TITLE
lcd.loadFont("fonts"xxxl.fnt")  will not work

### ISSUE THREAD

**Issue by Benno00** [FrSkyRC/ETHOS-Feedback-Community#4152]
Hello Bertrand,

testet with ETHOS 1.5.2, and 1.5.10
font_idx1 = lcd.loadFont("fonts"xxxl.fnt")  will not work
`local font_idx1 =	lcd.loadfont("/fonts/xxxxl.fnt")`
Error Message
/scripts/colorwert/main.lua:106: field 'loadfont' is not callable (a nil value)

lcd.loadfont how should the function be used which file type should be used.
The descriptions in the LUA-DOCU are very modest, please add better descriptions instead of keywords

Many thanks Benno

**Comment by aviat40** [comment]
Hello Benno,

lcd.loadFont("xxxl.fnt") is working but you need to copy the fonts folder from the FLASH to the SD card.
I asked Bertrand to be able to run callable lcd.loadFont("FLASH:/fonts/xxxl.fnt") but not working yet

Check my github, the Xicoy script use this

BR

**Comment by Benno00** [comment]
Hello,
why should I load existing fonts? I understand that additional fonts can be loaded, but what type should they be?
The fonts can be used via lcd.font(Font_STD) and no lcd.loadfonts(Font_STD) is required.

Benno

**Comment by aviat40** [comment]
lcd.loadFont() will be used in the future to load any TrueType font Type.
For the time, 2 extra size are available if needed.
Other font are directly available
FONT_STD, FONT_BOLD, FONT_ITALIC, FONT_XS, FONT_XS_BOLD, FONT_S, FONT_L, FONT_L_BOLD, FONT_XL, FONT_XXL

I think you can close this issue which is not an issue

**Comment by Benno00** [comment]
Sorry but I always get this error message in the SIM. What's wrong with that?


 paint() error: /scripts/colorwert/main.lua:106: field 'loadfont' is not callable (a nil value)←[0m

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/64bd1f54-174d-4a3c-b7bc-7c942ec5e90a)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/32254a21-7891-4a81-988f-2b542c6f1e7c)

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/97786547/ea7fa0b7-6f4f-44d7-9479-a67fd3aa18a8)


Benno

**Comment by aviat40** [comment]
Check the CAPS... loadFont
lcd.loadFont("xxxxl.fnt")
but the fonts folder should be copied to the SDCARD
lcd.drawText(1,1,"test",lcd.loadFont("xxxxl.fnt"))

**Comment by Benno00** [comment]
Hello
the first problem, the font can only be loaded in the build function
`local function build(widget)
	widget.font = lcd.loadFont("xxxxl.fnt")
	print("Font loaded as: ", widget.font)
end`
the second problem, the path must not be specified
`lcd.loadFont("xxxxl.fnt")`

it works now, but wath is the file type for font

**Comment by bsongis** [comment]
From next nightlies:
`lcd.loadFont("xxxl.fnt")` will load a font from the fonts folder
`lcd.loadFont("FLASH:/fonts/xxxl.fnt")` will load a font from anywhere

**Comment by Benno00** [comment]
Hello Bertrand,

 

thank you very much, that works fine.
can you tell me witch format is the font file, or is it a special Frsky format?

 

Mit freundlichem Gruss 

Benno Jurisch

 

Benno Jurisch
Siedlung 5, 27624 Geestland
Telefon: +49 (0) 4708 707
Mobil: +49 (0) 152 337 76 727
 ***@***.***> ***@***.***

 

 

Von: Bertrand Songis ***@***.***> 
Gesendet: Dienstag, 11. Juni 2024 22:09
An: FrSkyRC/ETHOS-Feedback-Community ***@***.***>
Cc: Benno Jurisch ***@***.***>; Author ***@***.***>
Betreff: Re: [FrSkyRC/ETHOS-Feedback-Community] lcd.loadFont("fonts"xxxl.fnt") will not work (Issue #4152)

 

From next nightlies:
lcd.loadFont("xxxl.fnt") will load a font from the fonts folder
lcd.loadFont("FLASH:/fonts/xxxl.fnt") will load a font from anywhere

**Comment by DH106Comet** [comment]
Hi - I'm trying to write a script for the X20 using **both** these 'extra' fonts, but I'm finding that when I load them in the 'build' event like this:-

local fntXXXL, fntXXXXL

local function build()
  fntXXXL = lcd.loadFont("xxxl.fnt")
  fntXXXXL = lcd.loadFont("xxxxl.fnt")
end

...then try and use them like this in the 'paint' event....

local function paint(widget)
  lcd.font(fntXXXL)
  lcd.drawText(50, 100, "XXXL", LEFT)
  lcd.font(fntXXXXL)
  lcd.drawText(400, 100, "XXXXL" , LEFT)
end

... what happens is that ONLY the first of the two fonts loaded (XXXL in this case) is drawn correctly. The other uses a standard font. If I reverse the order of the load in the 'build' event so that the XXXXL is loaded first, then the XXXXL font works, but not the XXXL.

Is there some sort of resourse restriction I'm coming up against here - that only allows one font - the first - to load and function correctly?

Thanks for any help.
