### ISSUE TITLE
Customers get confused with the Lua scripts for the gyro systems

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#4153]
We receive feedback every week that customers are having problems with the gyro receivers or the RBs with gyroscopes. Many of these problems are due to customers using the wrong Luas. So here are a few suggestions for a change.

Solution idea 1: This is the worst option, but better than nothing. I don't know whether it is technically possible to realise this. A message such as "You want to use a Luas script that is not suitable for your receiver" would help. This message should appear when a Lua is started and the data cannot or can only partially be read by the recipient.

Solution idea 2: Offer all current Luas for setting FrSky gyro receivers in a menu structure under Sensor Config. These Luas should then be updated immediately when flashing via the suite. It could look like this.

Sensor Config >>>Lua Gyro Receiver/RB

- SXR receiver
                      -Lua Basic
                      -Lua Stab
                      -Lua Config
- SRX receiver
                      -Lua Basic
                      -Lua Stab
                      -Lua Config
- RBXXS
                      -Lua Basic
                      -Lua Stab
                      -Lua Config

Solution idea 3: This will be the best solution. If all products can use the same Luas. Then it would be good if, for example, when setting an SXR receiver, all fields that can be used with this receiver are highlighted in orange, for example. All fields that cannot be used are grey.

I hope that the developers will think about the problem as soon as possible. Because we could avoid a lot of frustration for FrSky customers.

**Comment by strgaltdel** [comment]
This type of feedback, of course,  is not “limited” to the “engel support desk”,
even on rcg you can regularly read about users and their “lua - gyro - issues”.

e.g. have a look on "todays postings", i guess netherland, canada, britain and US is represented ... 
it starts at 30424

https://www.rcgroups.com/forums/showthread.php?3703807-FrSky-X20-(S-HD)-X20R-(RS)-X20-Pro-(AW)-Tandem-24-Channels-with-ETHOS/page2029


and in addition:
This "lua-bouquet" may be the main problem for the users at the moment,
but i'm afraid that it would need some tiny redesigns of the rf firmware of the several products to get a more unified usage of FrSkys different Gyro solutions too in order to get the mainstream user satisfied.   

regards
Udo

**Comment by pmullen503** [comment]
I Agree. A great percentage of help requests come because of stabilized receivers. 

Taking EngelMT's idea one step further.

How about Ethos selecting the right configuration tool? It knows what receiver is connected, it's firmware version etc. A simple lookup table could have Ethos run the correct tool.  You could still have an option to choose a different tool if you'd like.

**Comment by RealTadango** [comment]
The lua can be made adaptive, showing only the enabled / allowed options for the user to select. The options themself are not the biggest issue but finding / enabling the options is.  Also having multiple scripts is confusing....

**Comment by EngelMT** [comment]
Is there any solution to the problem? Because we can do no more than name the problem and offer ideas for a solution. The development team has to implement it. An indication of whether this is happening or not would be helpful. Then we could also close this issue here.

**Comment by mawzthefinn** [comment]
Fixed with the new Stabilizer Config UI in 1.6.0, where there's updating from Suite and just 2 UI's (old receivers and new receivers).

**Comment by EngelMT** [comment]
Yes, tested it and looks good.
