### ISSUE TITLE
Custom trims must have a safe default value

### ISSUE THREAD

**Issue by lthole** [FrSkyRC/ETHOS-Feedback-Community#4168]
Ethos 1.5.10 nightly

When using Custom trims, they should have a safe default value, in case you forget to take care of all possible active conditions. The best solution is to default to the FM0 trim like in OpenTX, even though you may not end up using flight modes to define the custom trim values.

In my case I defined some flight modes with FM0 as the base trim, see below. 

 ![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/5c29732b-bbe7-43ac-830d-ad36177add80)

However I had not defined custom trims for ALL flight modes, including Thermal and Speed. The result was that in Speed mode I have a trim value of -25%!!! (see below). Which is not safe at all! At the least it should have been 0.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/b77c9e7a-5305-46e7-bd08-39f4d2c4846e)

**Comment by bsongis-frsky** [comment]
I don't understand this screenshot

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/668c96f4-7bdc-439f-a1ec-5c226a83d034)

FM0 is written in bold, so the default should be active, no? Why the trim is not 0.4% then?

**Comment by bsongis-frsky** [comment]
Otherwise, I don't see any mistake, let's suppose that no condition can be applied, the trim will go to the default position (the one that you can see when you choose the "Easy mode".

**Comment by lthole** [comment]
The bug extends to the value display. If I switch to FM0 the trim value is shown correctly in the main display, see below. But the value says -25% in Trims.

I am also attaching the model file. Please note that throttle (Right slider) must be at 0 to get out of Power flight mode. Remember X20 Pro has right slider reversed.) Then Cruise and Speed are on SW SE.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/3ae8301b-7054-483c-967c-0b7a02e4ddc3)

This image below is when in FM5 Speed mode, which is undefined in Trims.

![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/26259987/336631c9-723b-45de-a634-898068a7d2a0)

[x-dream02.bin.zip](https://github.com/user-attachments/files/15863871/x-dream02.bin.zip)

**Comment by bsongis-frsky** [comment]
If the condition is not defined in trims, you get the default value of your trim. Which is -25% in your case, because perhaps you have setup it using Easy Mode

**Comment by lthole** [comment]
I do not recall setting any trim to -25%.

**Comment by bsongis** [comment]
Please try to switch to Easy Mode and check what is the value there. Normally this value is used in such a use case

**Comment by lthole** [comment]
Yes, there was a -25% in Easy Mode. But I recall a bug fix earlier which was to ensure that trims are zeroed when the mode is changed, to avoid having hidden offsets.

**Comment by bsongis** [comment]
If you setup -25% in easy mode, revert it to zero is perhaps dangerous!

**Comment by lthole** [comment]
But I think it is worse having a hidden offset. There should be a warning if the trim is non-zero when changing modes.

**Comment by strgaltdel** [comment]
by chance i'd to deal with the same issue last week (1.5.9)

Changing Trim mode into "custom" sets last known "easy mode" value as default, and you can't reset until you go back into easy mode.
in my case it was a tiny deviation (0.4), not recognized on 1st view, because the top "trim" value indicates only "integer values"
(green)

i did "interprete" this as an intented behavior: 
- trim model in easy mode, then change into custom mode:
- now default value is the "trimmed" model attitude

.. a popup / hint maybe a good idea

another 1.5.9 custom trim issue:
custom step didn't work in custom trim mode
even set to 2% stepping, trim value increased in 0.4 steps (red)
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20392683/d30c3742-8ad4-46d7-af4d-f37ef3ed49a1)

fixed in 1.5.10 or should i open another issue ?

**Comment by bsongis-frsky** [comment]
The default trim value will be reset to 0 in 1.5.10
