### ISSUE TITLE
Motor starts up (50%) when doing OTA update on Archer Plus SR8

### ISSUE THREAD

**Issue by FireflyJar** [FrSkyRC/ETHOS-Feedback-Community#4202]
I needed to update my Archer Plus SR8 trying to solve a different issue and the electric motor started up (50%) when I try to do an OTA update, which failed anyways. (radio FW was on 1.5.9)

so idea of OTA is so you don't have to get access to RX but yet we need to unplug ch 3 and add separate power to RX when we need to do OTA update?  I feel there is an issue with this.

could this be related to https://github.com/FrSkyRC/RF_Feedback_Group/issues/15 ?

**Comment by mawzthefinn** [comment]
The ESC shouldn't even be arming in this case, because it should never be seeing low throttle to allow the arm. I'd suspect this is an ESC issue of some sort.

I've not seen any of my OTA-capable receivers ever engage the ESC on OTA update, because they never output low throttle until after boot (and OTA updating occurs in the bootloader)

**Comment by FireflyJar** [comment]
> The ESC shouldn't even be arming in this case, because it should never be seeing low throttle to allow the arm. I'd suspect this is an ESC issue of some sort.
> 
> I've not seen any of my OTA-capable receivers ever engage the ESC on OTA update, because they never output low throttle until after boot (and OTA updating occurs in the bootloader)

are you leaving your throttle half way up when you plug in battery? I don't understand, soon as I plug battery in its armed because my throttle is down.  I will also try it on another model to see.

**Comment by T16-Pilot** [comment]
Are your receiver powered on before you select OTA on your transmitter?

Because i have seen that if i power on the receiver first and then select OTA on my radio everything is doing the funky chicken dance and the OTA is failing...

If i select OTA, then power on my receiver everything is working great. It updates my RX and no movement on servos/motor.

Best regards
Simon

**Comment by FireflyJar** [comment]
> Are your receiver powered on before you select OTA on your transmitter?
> 
> Because i have seen that if i power on the receiver first and then select OTA on my radio everything is doing the funky chicken dance and the OTA is failing...
> 
> If i select OTA, then power on my receiver everything is working great. It updates my RX and no movement on servos/motor.
> 
> Best regards Simon

### Yup, I it's me not following instructions.  but instructions in the readme is not clear.

" keep the receiver under working mode. " does not make sense to me.  I had it registered and bound already.
would be safer if they just say with RX off,  start OTA  update first then turn on RX.

How to update ACCESS receiver firmware:
1. Put the firmware under the folder [FIRMWARE] of SD card.
2. Register and bind the receiver with your radio, keep the receiver under working mode. 
3. Find the firmware file in SD folder, select it by press [ENT].
4. Select Flash receiver OTA, re-cycle the receiver power and wait for flash ends.
5. Re-cycle the receiver power and wait for 3 seconds to have connection with your radio again.

**Comment by ETHOSWarrier** [comment]
I have seen this happen before.Your failsafe throttle position must not be set to off.What happens as part of the OTA process during reboot /reset /process / the tx is off and the rx is on(or the link between Tx and rx  is not active due to the OTA process) so failsafe is activated and thus the throttle will fire up if the failsafe position is not correctly set....

**Comment by RealTadango** [comment]
Never connect a drive battery when doing an update to the receiver. Always use a separate battery connected to the RX for safety.

**Comment by FireflyJar** [comment]
> Never connect a drive battery when doing an update to the receiver. Always use a separate battery connected to the RX for safety.

I used to until it fried a ESC, brand new neuron 80 v1.
