### ISSUE TITLE
1.5.10 Nightly (LUA) - LiPo options (OPTION_CELL_COUNT, etc) are not working

### ISSUE THREAD

**Issue by Alex00101** [FrSkyRC/ETHOS-Feedback-Community#4208]
Tested on X10Express, X20S and X20 Pro simulators (will retest on the actual radio later).
**Before 1.5.10 nightly (Expected behavior):**

local v = lsource:value() 
local c = lsource:value(OPTION_CELL_COUNT) 
print(v, c)    

Output: 19.2   6

**On 1.5.10 nightly (error?):**

local v = lsource:value() 
local c = lsource:value(OPTION_CELL_COUNT) 
print(v, c)    

Output: 19.2   19.2

Same applies to all other options, i.e. [OPTION_CELL_HIGHEST

**However:** 
If I configure a value widget and set source option to count (long click on the source), this works as expected (shows 6).

**Comment by bsongis-frsky** [comment]
Right, there is a change in this area. Because it's now possible to call `value` to set a sensor value, and it is not compatible with options.

So you have to give the options in the source itself

**Comment by Alex00101** [comment]
Sorry Bertrand, may I please ask you to elaborate on what should I do?
I'm trying to read a number of cells in the flight battery into a widget
from standard FLVSS sensor (LiPo).
How can I achieve this in 1.5.10 without asking the user to input it?
Thanks

**Comment by bsongis-frsky** [comment]
This should work:

```lua
local lcellscount = system.getSource({
  category=lsource:category(), 
  member=lsource:member(), 
  options=OPTION_CELL_COUNT
})
print(lcellscount:value())
```

**Comment by Alex00101** [comment]
Thanks a lot!

**Comment by i3dm** [comment]
> ```lua
> local lcellscount = system.getSource({
>   category=lsource:category(), 
>   member=lsource:member(), 
>   options=OPTION_CELL_COUNT
> })
> print(lcellscount:value())
> ```

tried running this in paint and im getting:
001612 /scripts/Cells/main.lua:416: attempt to index a nil value (global 'lsource')

**Comment by fdm225** [comment]
hi all,
is it possible to get the example scripts updated when you make a change like this?  Also, is the api going to stabilize?  i ask as it seems to keep changing during the point releases breaking scripts.  It's making it a bad environment to invest time and develop tools around as it seem like the tools themselves are breaking when in fact it's the system breaking them with updates.  I get that you want to add new functionality but if you want a 3rd party community (if not then why publish an open api) there needs to be some sort of stability so that community can actually exist.
