### ISSUE TITLE
X18S 1.5.10 Simulator LUA issues

### ISSUE THREAD

**Issue by salibaj2** [FrSkyRC/ETHOS-Feedback-Community#4238]
What just happened to the X18S 1.5.10 simulator?

Usually I uninstall the previous simulator, and then install the latest version. 

When I launch it, everything normal.

However, this time it asked to make new models as it did not found the ones I had, and none of the LUA scripts I had are being found.

I am still on 1.5.8 on the real Tx. If 1.5.10 is going to cause me problems, I stay with the older version.

**Comment by Alex00101** [comment]
This because there were changes in 1.5.10 simulator file structure. Before 1.5.10 your scripts were in your install directory and models were in your user directory that was looking like .ethosX18S

Now, both your models and scripts need to be in your user directory under .ethos and under it X18S (.ethos\X18S), which has models and scripts  like so:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/27343158/83b13d0c-6bec-4cb0-b4aa-6c69b594d1d7)

**Comment by salibaj2** [comment]
Thanks, 

This only apply to simulator or even for real TX?

Your method works. I moved the models and scripts to the user folder and worked. However, this is rather confusing as I am replicating the Tx, and would have preferred that everything was as per Tx.

**Comment by Alex00101** [comment]
Acrual radio is not affected, my scripts and models are in the same radio folders as before 1.5.10 upgrade.
