### ISSUE TITLE
Touch screen

### ISSUE THREAD

**Issue by andrescuadrosjdc** [FrSkyRC/ETHOS-Feedback-Community#4248]
Hello find 2 issues with the screen and menu
When changing models and after selecting the new model I want, the option Set current model, doesent work
have to wait it changes alone.
And in all the menues the top left corner only works if I press the far end of the screen, previously it worked touching the word
Maybe the return sign is to small for my fat fingers

**Comment by bsongis-frsky** [comment]
Which radio? Any possibility to make a video?

**Comment by kramgrand** [comment]
hello, I agree with andrescuadrosjdc.   Since updating to 1.5.10, when in a menu, the back arrow on the top left of the screen has become very particular where it is touched. You used to just touch the top left of the screen to back out of a menu but now I have to keep pressing/touching the screen in the far far left for it to work.  Not saying it's really a problem, but I have noticed it and it's not as easy as it used to be.  X20PRO and X20S.

**Comment by andrescuadrosjdc** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/cc693bce-3ef0-48e4-be9b-08016fe347ea


https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/89352761/465ff168-abd3-4bcb-9ac4-c618f7190b31

Hello
I use a Pro and a X20S, same issues on both and they where also on 1.5.9

**Comment by bsongis-frsky** [comment]
I think that your problem with "Select current model" is that the bitmaps are slow to load, and the action is done between 2 bitmaps load.

1.5.12 will include a enhancement which multiplies by ~10 the load speed for bitmaps, so it will be fixed in the same shot.

The other problem is fixed. It will be available in the next 1.5.12 nightlies

**Comment by PeterGraz** [comment]
Since updating to 1.5.10 I have the same issue with the top left corner on my X18SE. I was already afraid that this was a problem with my touchscreen!

**Comment by agibson2** [comment]
> 1.5.12 will include a enhancement which multiplies by ~10 the load speed for bitmaps, so it will be fixed in the same shot.

That is great news for the future of Ethos.  Looking forward to seeing that.
