### ISSUE TITLE
Source selection laggy in Logic switches

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#4333]
Not sure what version this started happening in, but I noticed in 1.5.11 and 1.5.12 pre-release that the source selection menu is extremely laggy in Logic switches but not in Special functions.

Laggy in Logic switches:

https://github.com/user-attachments/assets/f5e0323e-e0ae-477b-85af-6f42e85ac064

Fast in Special functions:

https://github.com/user-attachments/assets/4c6b8d45-d9ec-4c0f-8625-44e4c1343185

**Comment by bsongis-frsky** [comment]
You compare a switch selection (i.e. boolean) to a source selection (i.e. number)

**Comment by bsongis-frsky** [comment]
Also when you select a telemetry value, Ethos has to adapt the Value2 line so that it is displayed correctly.

**Comment by BladeScraper-Designs** [comment]
It did not used to be that way.  I put my X18 back to Ethos 1.5.1.  Source selection in LSW was very fast, like it used to be.  Then I updated to every single version after 1.5.1.  It took a while lol.  From 1.5.1 to 1.5.9, the menu is very responsive, high refresh rate, feels excellent.
https://github.com/user-attachments/assets/c80f1adc-e0ed-4cd3-a368-78a241cf54ee

From 1.5.10 onwards, the lag is noticeable and in some cases quite severe as seen in the first video from OP.  So it seems the issue started in 1.5.10.

My X20 PRO is considerably worse, bordering on unusable. 
https://github.com/user-attachments/assets/a2fc1189-e2a1-486e-be22-552b883632c6
Presumably because of the much larger display resolution.

**Comment by bsongis-frsky** [comment]
@BladeScraper-Designs Thanks for the time you have spent on this issue. I have found something bad, which indeed has been introduced in 1.5.10: the page title in Model / Logic Switch is refreshed every 20ms for nothing and it makes the whole screen very badly responsive. It will be fixed in the next nightlies. Would you take some time tomorrow to confirm this problem has been nailed?

**Comment by BladeScraper-Designs** [comment]
> @BladeScraper-Designs Thanks for the time you have spent on this issue. I have found something bad, which indeed has been introduced in 1.5.10: the page title in Model / Logic Switch is refreshed every 20ms for nothing and it makes the whole screen very badly responsive. It will be fixed in the next nightlies. Would you take some time tomorrow to confirm this problem has been nailed?

Just installed latest nightly to my X18, indeed logic switch menu is back to responsive and normal.  Thanks!
