### ISSUE TITLE
Faster paint rendering after hooking up USB!!!!

### ISSUE THREAD

**Issue by noamkrief** [FrSkyRC/ETHOS-Feedback-Community#4374]
This is very strange, but very REAL!

All this widget does is load the PNG once, then paint it.

After radio is booted up, scrolling is fairly smooth.
If you hook up USB and then unplug, the smoothness of the scrolling gets even better!

Can someone explain why?

https://www.youtube.com/watch?v=3h7JPG4q3eY

**Comment by bsongis-frsky** [comment]
Interesting. There is another user who reported it.

**Comment by bsongis-frsky** [comment]
Would you attach the script and the PNG?

**Comment by noamkrief** [comment]
@bsongis-frsky 

local function create()

end

local bg = lcd.loadBitmap("landscape.png")

local function paint(widget)	
	lcd.drawBitmap(0,0,bg)
end



local function wakeupnow(widget)
		lcd.invalidate()	
end

local function init()
    system.registerWidget({key="test1", name="test1", create=create, paint=paint, wakeup=wakeupnow, title = false})
end

return {init=init}
![landscape](https://github.com/user-attachments/assets/56af5e6c-2083-419a-97ad-310b0c091ae8)

**Comment by bsongis-frsky** [comment]
I cannot reproduce it.
Does it happen on a blank model (no RF / no logging)?

**Comment by bsongis-frsky** [comment]
On which radio? X20S?

**Comment by noamkrief** [comment]
@bsongis-frsky 

In the video you will see it's X20pro not connected to any RX.
If it's been connected by USB at any point AFTER boot up, the swipe is extremely smooth.
To get the swipe to slightly chatter, you must turn off and turn the radio back on without any USB plugged in.

It's very small difference, but I hope the video demonstrates it well.

**Comment by bsongis-frsky** [comment]
OK. I cannot see the radio, because the video shows only the LCD, not the whole radio.
It's difficult to see the difference in the video. I think you have to "feel" it 
I have tried on X20S and I see no real difference.
Does it happen on a blank model (no RF / no logging)?

**Comment by noamkrief** [comment]
@bsongis-frsky 
Wow. I just tried it. On 100% new model, no RF, it's super smooth swiping ALL THE TIME.
I can try to troubleshoot more to find out what about my existing model file that is causing this?

**Comment by bsongis-frsky** [comment]
It explains why there is no difference on mine. It would be interesting to find what makes it slow. Then I can try to understand the reason...

**Comment by noamkrief** [comment]
@bsongis-frsky 
So it's only when my own personal widget runs  on a different screen.
If my widget is very heavy, ok.
But why is there such a large performance improvement after USB is plugged in and then unplugged?

Just to make sure there isn't something specifically nasty with my own widget,
I loaded the BATT Zavionix widget  on page #3.
Page #1 is the landscape background
Page #2 is empty.

Same effect. A little chattery when swiping, but after plugging in USB and unplugging, it goes to 100% smooth.


So to replicated.
Use my code above for Page #1
Leave Page #2 no widgets
Use Zavionix Batt widget on Page #3


Upon boot up of radio, scroll from Page1 to Page2 back and forth. A bit lagging.
Plug in USB to PC (ethos mode) and then unplug.
Lagging goes away 100% smooth.

**Comment by bsongis-frsky** [comment]
Again I cannot reproduce. Would you remove as many elements from your Nand as possible, then attach a zip of the Nand here?

**Comment by strgaltdel** [comment]
The effect is similar to what is described in #3884, and I suspect the same root cause.

By "cycling" the USB connection, you get a significant performance boost (not just in rendering).

From what I understand of this description, the complexity of the template also plays a role. If I find the time, I will test whether it's more related to the mixers/LSWs and SFs, or the number/extent of active or initialized Lua scripts. Usually, I have 3-4 Lua scripts configured, but I always check if the widgets are running on the active screen and otherwise terminate the handler.

**proof of performance gain:**
I can always see a significant boost in the Log-write rate.
Interval set to 200ms.
With a complex model, Ethos may only achieve 370.
After "USB cycling," it is noticeably faster (if I recall correctly, by about 25%-30%).

If it helps, I can also put together a ZIP file including the model and all the necessary files.

**Comment by bsongis-frsky** [comment]
Yes it will help! Try to reduce at minimum the ZIP file if possible!

**Comment by strgaltdel** [comment]
i'm on work, so a slightly older setup
was not sure if audio folder & radio.bin was needed,  i added only radio.bin from sim 1.5.12!
in case you need audio director, please tell.

test on X18:

- template:  you'll find only one model, keep switch posis regarding checklist
- root: image folder must be in root of volume
- scripts folder: two widgets & the corresponding lib folder

(1)
after successfull load of the template, enter model menue and use wheel as fast as you can, pay attention to speed of browsing

(2)
connect tx to notebook, start suite, enter debug mode, and try again browsing in model menue as fast as you can using wheel, you should experience a far faster behavior

(3)
disconnect USB, performance gain should stay until reboot of tx

[0 env mini.zip](https://github.com/user-attachments/files/16673377/0.env.mini.zip)

**Comment by bsongis-frsky** [comment]
With this zip I see no difference at all on X20 PRO. Moreover there are Lua errors. 
It would be nice if you have time to do a simple setup which replicates the issue 100%

**Comment by strgaltdel** [comment]
strange

(I had already seen the lua errors on the sim, but it should have nothing to do with the effect)


tonight is already reserved for the tutorial (chapter 1, short for finishing) & a few adjustments to the Uni-Firmware Luas
hope i get to set up something "lean" tomorrow

**Comment by strgaltdel** [comment]
Yesterday, I spent two hours on this topic. The result was surprising to me:

Although last week I was still of the opinion that I had "seen" the performance boost even under 1.5.12, I couldn't really verify it yesterday.
Nothing had changed since then (except the battery level, which was fully charged yesterday)

Since the speed in menu browsing and swipe movements might also be subject to subjective perception, I used the log interval as a benchmark.
"Earlier," there was a noticeable improvement here when the dev tool was used.
Unfortunately, I couldn't detect any reliable differences now.

I started by
a) using the above-mentioned configuration.
b) Then I copied a variety of Lua scripts into the scripts directory to generate a more extensive initialization.
c) Tested the Tx with and without Rx (telemetry).
d) Also tried older suites.
e) Tested various templates.

In all tests, the operating time was at least 4 minutes.

never could detect significant performance differences.

My suggestion is to put the issue on "hold" for now, as long as there are no reproducible results elsewhere.

If I find some time, I will perform downgrades to reproduce "the old effect" and narrow it down to a minimal environment.
Then, I will document the performance differences (e.g., using logs) and compare them with the current performance.

From this, it will become clear, in my opinion, whether (at least #3884) can be finally closed or if there might still be optimization potential "somewhere."

Best regards,
Udo

**Comment by bsongis-frsky** [comment]
I keep the issue open in case we find something later. Could it be the `print` method which is slower, and that you removed later?

**Comment by noamkrief** [comment]
@strgaltdel @bsongis-frsky 

I found an issue that is related that may shed some light and give us a step forward.
In the video I'm showing extreme UI slowness when scrolling through a source of an LS.

Then I clone my model, and select it.
And the scrolling of the source is nice and smooth.
https://www.youtube.com/shorts/ksc_qrrXaZo

To clarify. If I go back to the original model, the issue of slowness is still there. Only the clone is fast.

Please lets keep trying to find the source of this UI slowness, because it's VERY real and once we find it, we may find a very evil bug in the system overall.

**Comment by noamkrief** [comment]
@strgaltdel @bsongis-frsky 
I did alot more troubleshooting.
The difference is that the cloned model RF is OFF.
Turning ON the RF uses alot of resources of the radio CPU it seems. Can anyone confirm?

**Comment by bsongis-frsky** [comment]
The mixer runs far more often when the RF is started, depending on the module type!

**Comment by noamkrief** [comment]
@bsongis-frsky I don't know what you did, but this latest ethos update is a HUGE step forward in terms of performance!
The swipe is super smooth now even if I don't hook up a USB cable.
The overall UI is extremely smooth now.
Telemetry seems to work better - I have over 40 telemetry items and they were really bogging down before, now they are doing much better in terms of lag.

You can close this. This is fantastic!

**Comment by bsongis-frsky** [comment]
It is the chdir which was called before each wakeup / paint / event Lua function which made the system very slow. Happy that someone gives some positive feedback today on 1.5.18 :)

**Comment by Dsrenger** [comment]
Just updated to 1.5.18

This feels so good. Holy crap....

One of the most "feelable" changes...holy crap....thanks Bertrand!!!
