### ISSUE TITLE
[1.6 nightly] Can't flash internal module firmware

### ISSUE THREAD

**Issue by rburrow87** [FrSkyRC/ETHOS-Feedback-Community#4739]
1.6 nightly #2ce9808b
X20RS

When choosing a frsk file to update internal module firmware, the pop up does not have an option to flash internal module. External module and RX firmware seem to be fine though.

**Comment by Nicholas-Luoyi** [comment]
Would you please try to shorten the firmware name?

**Comment by rburrow87** [comment]
No change.

However, I just found that if I connect the radio to the computer while it's on (in Ethos) and then disconnect it, it'll show the option to flash the internal module. But if I turn the radio off and back on, the option goes away again.

**Comment by BladeScraper-Designs** [comment]
Same on my X20 PRO AW.  Unable to flash internal RF (no option available) but connect to USB to PC  then eject and disconnect, the option is there until restarting radio

**Comment by mawzthefinn** [comment]
Same on my X20

**Comment by bsongis-frsky** [comment]
I have modified the process. The option will be displayed as before. Then the check will be done (since the user has chosen to update the module, it's not a problem to stop it and retrieve its version). Then if the check is not good, the user will be informed there is a problem but he will be able to continue if he really wants to do so.

I have adapted the confirmation message from the RX to be valid also for TX.
