### ISSUE TITLE
Transferring models from Taranis X9D+ 2019 to Tandem X20S

### ISSUE THREAD

**Issue by flyboywbl** [FrSkyRC/ETHOS-Feedback-Community#475]
Is there an easy way to transfer my 30+ models from my X9D+ to my new X20S or do I seriously have to set all my models up again on the new radio?  I think I know the answer but I don't want to believe it.

Thanks!

-Matt

**Comment by Hobby4life** [comment]
It is another operating system so yes.
Best learning experience. I have done arround 30 models on my own tx past 2 weeks. And some more on my friends tx 😉

**Comment by jreis1** [comment]
You will see that weighs and channel order will be the same as in x9d. Just copy the same values and test it afterwards

**Comment by flyboywbl** [comment]
Ok, darn.  I wish they made a converter or something. But I guess if I copy the values, I should be in the ball park.  I'm just more worried about how all my voltage logical switches will transfer over. 

Not to mention I need to get at the bind buttons,  oh joy.

**Comment by higheronnitro** [comment]
Better might be a way of configuring and testing models on PC and then saving to Ethos..

**Comment by flyboywbl** [comment]
Is there a "Companion" like Open TX has?

**Comment by higheronnitro** [comment]
Not that I know of but this would be the highest item on my wish list..

**Comment by TWSreviews** [comment]
I feel you pain....however, in the past I spent more time fixing the conversion errors, misallocated switches, audio file mismatch etc that I could have set them up from scratch quicker. 
What I found works is to set up the perfect configuration for a plane, wing and multi rotor and then keep cloning as I introduce each of them to my model.....so you are only technically configuring three models and all compatible set ups.

**Comment by NorbertHeli** [comment]
Yes - most of I wrote is right for heli, copter, motor airplane, thats fast done.
BUT: I own nearly 30 Gliders - with 4 or 6 flaps, most with 6 FM ( Motor, 2xthermik, 2x fast + normal ) every with its own triming. V and also cross rudder.
Also crow for landing and all servos must run syncron.
I fly most OLC - a GPS offline race - with about 40 virtSwitch and specFunct to annonce and alarm distance, high, direction in 10° steps and so on.

I transfered 3 Gliders with all settings from Horus X12 to X20S. Both transmitter laying side by side.
 Transfering  direction / max min / center/ syncron / all settings of FM / about 30 virt Switches / and so on.....
OK - the model was flighing nearly as it should - but I was for every model ~ 5h working.

Of cource I can copy the model and take it to adapt it for the next - but its not much less work, because all have to be done at transmitter.

Isn´t there a possiblity to edit and copy a model by PC, best move and copy blocks of lines?
Best where a transfer from OTx to ETHOS, after that editing.
