### ISSUE TITLE
Sensor conflict with TDSR10 and RB40

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#4853]
TD SR10  with a RB40
one Gyro deselect is ok

but Both have a Vario
can´t deselect the vario at TD SR10 or at RB40

Name change or ID change, now solution

so got a Sensor conflict

**Comment by hrenz** [comment]
If you could at least hide, deactivate and ignore sensors in telemetry

even deleting them does not help.

Although deleted, the sensor conflict message still appears.
and even plugging it in afterwards doesn't help.

Deleting everything and searching again messes everything up again, including displays on the screens.
There is still a lot for ETHOS to do, including an automatic systematic sequence of all telemetry values.

**Comment by bsongis** [comment]
It's difficult to understand your issue. You seem to mix different problems. Remember that when you delete a sensor, and unlike OpenTX, all the reference to this sensor are cleared.

What is the vario sensor? Would you fully describe your setup so that we can try to reproduce with exactly the same environment?

**Comment by bsongis-frsky** [comment]
The real issue is there #4857
