### ISSUE TITLE
Xact servo temperature sensor data wildly inaccurate. 

### ISSUE THREAD

**Issue by BJR981S** [FrSkyRC/ETHOS-Feedback-Community#4858]
I have tested 12 Xact serves unmounted close to each other with no servo commands to move and no servo arms attached, and watched the temperature reported in the telemetry menu.

The temperature ranges from 24C from lowest sensor reading to 35C degrees on the highest. They all seem the same temperature to the touch. I will test with laser temp sensor as soon as it arrives.

**Comment by EngelMT** [comment]
Interesting, but do you have the same settings in the servos? If, for example, the deadband is set to different sensitivities, then this should also lead to different temperatures because the servos have different sensitivities around the centre position. And if you readjust more often, the servos will also heat up more.

However, this is certainly not an issue for this Github group. Because this is about the ETHOS firmware.

**Comment by mawzthefinn** [comment]
This issue belongs in the firmware-oriented https://github.com/FrSkyRC/RF_Feedback_Group/issues

That's for non-ETHOS issues, ETHOS is just reporting what the servos send.

**Comment by BJR981S** [comment]
Sorry gents, used the wrong bookmark. And the servos are all identical except Channel ID PhyID and App Value.
