### ISSUE TITLE
Timer with throttle % control

### ISSUE THREAD

**Issue by KAD370** [FrSkyRC/ETHOS-Feedback-Community#49]
When selecting timer control with throttle%, it triggers only when I get over neutral point (0 or half throttle), needs to be selected point.

**Comment by bsongis-frsky** [comment]
at neutral point you should get half speed, please double check

**Comment by hrenz** [comment]
take it simple
Throttel Trigger     Thr Tr   Gas Trg
Throttel StartStop Thr SS  Gas SS 
Throttel %             Thr %   Gas %

**Comment by mawzthefinn** [comment]
Closing off stale issue as no new info provided.

@hrenz - Your feature request is noted, but there are other Issues which address this, notably #654

**Comment by KAD370** [comment]
Bullshit🤬
Thank you frsky for listening your costumers....

**Comment by mawzthefinn** [comment]
@KAD370 Nobody has been able to duplicate what you initially reported in April 2021, Timer % triggers on throttle > -100 and has since implemented, this is as designed. @bsongis-frsky asked you for more information immediately, but it was not provided. 

I’ll re-open if you provide more information as to what the problem you are experiencing is and how to duplicate it.
