### ISSUE TITLE
Kavan V20 update 8Mo "FLASH" drive.

### ISSUE THREAD

**Issue by philippe-warnotte** [FrSkyRC/ETHOS-Feedback-Community#4910]
I regularly update my transmitter with Ethos Suite.
The "bitmaps/system" files are installed in the 8Go "Radio" drive.
There are also "bitmaps/system" files in the "Flash" drive but 
they are old (March 2024). Idem for Fonts.
Do I have to download the V20_FLASH.zip file on Github to copy them manually
on the "Flash" drive?

**Comment by Nicholas-Luoyi** [comment]
You mean Suite install the bitmaps also into the 8GB flash?

**Comment by philippe-warnotte** [comment]
RADIO= 8Go   FLASH= 8Mo  on Kavan V20.
Updates with Suite are done in the 8Go “radio” drive. No update in 8Mo “Flash” drive. Suite doesn't install anything on FLASH. Nothing has changed on this drive since I purchased my radio. This is why I wonder why these System Bitmaps and Plane Base Bitmaps files are on Flash and what is the use of the file published on Github V20_FLASH.zip
This is simply a request for my information because my transmitter works perfectly well with Ethos 1.6.0.
![image](https://github.com/user-attachments/assets/da939798-0094-4167-aafb-d5fea98dbfb2)

**Comment by Nicholas-Luoyi** [comment]
I just understand your problem. I think it's normal if you don't lose any bitmaps in the Ethos. Suite does a binary level check for every bitmap file. If the local file is identical to the remote file, then Suite won't do anything to the existed bitmap file. That's why the modification date of the bitmaps stay. And the bitmaps in 8Go Radio drive are not needed. You can delete them.

**Comment by philippe-warnotte** [comment]
Yes, thank you Nicholas. I have all my bitmaps on Flash. I misunderstood because the dates were not the same and now I understand your explanation very well. You can close this post. Everything is perfect. I wish you a happy holiday season.
