### ISSUE TITLE
No support for joystick for X12S

### ISSUE THREAD

**Issue by KAD370** [FrSkyRC/ETHOS-Feedback-Community#51]
No support for mini gimbal on left side (gimblal with up/down page buttons)
X12s ethos V1.0.1

**Comment by eijowk** [comment]
Agree - missing the gimbal/mini red joystick - one of the advantages with X12S! Should be quite easy to implement?

**Comment by gjm8455** [comment]
I upgraded my FrSky X12S to ISRM and installed ETHOS from OpenTx. The mini gimbal was supported in OpenTx and appears in ETHOS on the Hardware Check page but is inoperable. I used this feature for telemetry call outs and look forward to it being activated in ETHOS. To me its like not having one of the switches work.

**Comment by Luznatural** [comment]
This feature was implemented in OTX since the very beginning. Indeed, the radio came from factory with the analog stick perfectly working and you were able to calibrate it and use is as source for many good things, like gimbal for moving a camera, make the pilot in a plane moving, etc.
I kindly request to rise the priority for this issue to incorporate it as fast as possible, as we are thousands the owners of this radio that are eager to move forward to a more modern firmware like Ethos, and the radio continues being sold by many shops.
I simply cannot understand how being Ethos a firmware supported by Frsky, this X12S is not receiving enough attention nor priority to get a solution requested so long ago.
Thanks in advance.

**Comment by Michal2112** [comment]
Please add joystick support. It's been too long since all X12s hardware is not fully supported on Ethos. The broken joystick is keeping me from switching to Ethos and I'd love to use it. Thank you for any response from the developers.

**Comment by bsongis-frsky** [comment]
I see the code is there since 2 years and the issue has been kept alive, I wonder why.
Checking right now...

**Comment by bsongis-frsky** [comment]
It will be added to 1.4.11 final

**Comment by Michal2112** [comment]
Perfect. Thanks.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/b68d60f3-cfb5-410c-b225-264e4cc354c6)
