### ISSUE TITLE
how to make good model documentation with ETHOS

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#515]
how to make good model documentation with ETHOS
Many screenshots are not the solution
It needs to be as simple and clear as the mixer views under openTx with mixer settings all in one line

ETHOS also has a hidden view of the mixers.
The GUI is just put on top

**Comment by jreis1** [comment]
Not sure what is the question but I feel Ethos very intuitive and almost self-explanatory in terms of mixing.

**Comment by T16-Pilot** [comment]
Otx is a lot easier to get all the basic info on one channel than Ethos. With Ethos we need to scroll down the page on each channel to get the info. In Otx all the data for all channels are in one picture on the screen. 

Dont get me wrong, Ethos works, but i might be a good idea to take a good long hard look at the Otx way of doing things... i for one am missing Otx, but i love the hardware in my X20... you can't get it all they say!

**Comment by loetefix** [comment]
The only i miss in ethos is the better overview what inputs are assigned to wich channel. A second  "reversed" view would be nice in opentx style.

**Comment by Hobby4life** [comment]
> Otx is a lot easier to get all the basic info on one channel than Ethos. With Ethos we need to scroll down the page on each channel to get the info. In Otx all the data for all channels are in one picture on the screen.
> 
> Dont get me wrong, Ethos works, but i might be a good idea to take a good long hard look at the Otx way of doing things... i for one am missing Otx, but i love the hardware in my X20... you can't get it all they say!

Personally I disagree on this one, I use opentx from the very first beginning and know almost of its in and outs now.
Specially due programming in Lua you get the real OTX feel and knowledge.
But anyways the step to Ethos was way more easier then I thought, even my clubmates find Ethos more logically then OTX, too much info on screen confuses a LOT for new beginners.. Ethos guides you starting off scratch,  Ethos only shows you stuff you have configured, not endles lines of empty unused stuff. thats the major advantage over OTX.
You dont have to tell Bertrand to overlook OTX though, he is littarly the father of OTX ;-) He just tries to make it better from scratch :-)

If lua is added in the near future, I gues I will dont go back that much to OTX, alltough I am a big fan of OTX.

**Comment by hrenz** [comment]
this has nothing to do with "intuitive and almost self-explanatory" programming

ETHOS is completely confusing if you have many mixers and states

Assembling dozens of screenshots is a joke to be able to explain a model setting.

what takes 3 lines in openTx, takes in ETHOS 4 pages
This is an impossible state

**Comment by jreis1** [comment]
> this has nothing to do with "intuitive and almost self-explanatory" programming
> 
> ETHOS is completely confusing if you have many mixers and states
> 
> Assembling dozens of screenshots is a joke to be able to explain a model setting.
> 
> what takes 3 lines in openTx, takes in ETHOS 4 pages
> This is an impossible state

I can’t agree with you. I’ve a decathlon with many mixes including ail>rud, flaps>ele, flaps as extended ailerons, all with double rates, which I’ve programmed in ethos in just a few minutes (mostly due to pre-existing templates) ,whilst in openTX it was literally a pain in the butt. IMHO the mixing is one of the strongest points of ethos :) anyway this is just my personal opinion and we are all here to help to improve the current state :)

**Comment by Hobby4life** [comment]
Creating a manual about a system that is constantly expanding and changing by use request is a no go task.
Only way just like OTX, is just dig in too much.

At my club I stopped pre-programming models for them.
If you dont spend time in these kind of systems that constantly expand and refine its just not for you.

As in Ethos many way lead to rome. If you know that path to walk thru.

For now I have managed to get arround 30 models programmed, where 12 gliders.. some very complex.. 10, acro/scale/tow planes. and 8 Scale helicopters..

All working nicely and some are programmed far more easily due some other approach in Ethos. Where in OTX I had to create loads of Logic, and now it is right in the mixers.

**Comment by hrenz** [comment]
You have not understood what is at stake
Based on your answers, I see that you have never written an operating manual. 

This has nothing to do with programming with ETHOS. intuitive or not.

**Comment by Hobby4life** [comment]
ok 👍

**Comment by T16-Pilot** [comment]
> > Otx is a lot easier to get all the basic info on one channel than Ethos. With Ethos we need to scroll down the page on each channel to get the info. In Otx all the data for all channels are in one picture on the screen.
> > Dont get me wrong, Ethos works, but i might be a good idea to take a good long hard look at the Otx way of doing things... i for one am missing Otx, but i love the hardware in my X20... you can't get it all they say!
> 
> Personally I disagree on this one, I use opentx from the very first beginning and know almost of its in and outs now.
> Specially due programming in Lua you get the real OTX feel and knowledge.
> But anyways the step to Ethos was way more easier then I thought, even my clubmates find Ethos more logically then OTX, too much info on screen confuses a LOT for new beginners.. Ethos guides you starting off scratch, Ethos only shows you stuff you have configured, not endles lines of empty unused stuff. thats the major advantage over OTX.
> You dont have to tell Bertrand to overlook OTX though, he is littarly the father of OTX ;-) He just tries to make it better from scratch :-)
> 
> If lua is added in the near future, I gues I will dont go back that much to OTX, alltough I am a big fan of OTX.

The reason that people might find Ethos easier than otx is that they are coming from a menu driven radio system in there previous radio systems. Ethos is exactly that, menu driven. Otx is not a menu driven system. That said, the "logic" behind Ethos is very much the same as otx, only with a "shell" on top to try and make it a litte bit more logical and easier to understand than otx.

I used to fly with Hitec Aurora 9 witch was the first real touch based "high end" radio out there. It was very intuitive and very easy to program. What killed that system was that Hitec did not lissen to the users when it was time to upgrade the system. We wanted more channels and better telemetry and so on.. and got nothing of what we wanted and the system died. But the Aurora 9 was and still is a great example of a very good touch screen controlled radio witch could do just about anything you wanted for airplane use.

Fast forward some years, i bought a Horus X12s with FrOS. That was in 2016. Back then FrOS was at about the same state as Ethos is today. In other words unfinished. I found FrOS to not give me what i wanted and then tried OpenTX. In 2016 otx was a working system, but no wear near what it is today. At that point in 2016 i gave up and sold my X12s. 

Today otx is a very good system, but you have to want to learn how to use it. What i like about otx is that it gives me what i need in very few clicks in the "meny". 

Here is where i don't like Ethos, i have to click like 14 times to get to where or what i want in Ethos. It might be because i am used to apple computers and hate windows for the same reason. Apple is a few clicks, and windows is double clicks and jumping true hoops with drivers and stuff to get to where i want to go. I might get a lot of flak for sying that ;) Only to show that we are all different and think different and that is what makes it interesting to hear how other people look at different things in the Ethos system.

So what am i trying to say?

Well, Ethos to me is at the same point now that FrOS and OpenTX was back in 2016 when i first bought my X12s radio. It worked kind of. But in reality it was very much unfinished like Ethos is at the moment.

I think Ethos can be a very good operating system in a year or two defiantly, at the moment we are trying to use a system that has its kinks because it is very new both as a system and because there is not much information online to help us to work around the things that might not work at the moment. All that is because the system is very new too all of us.

I am going to keep my X20 and hope that Ethos evolves in to what it is ment to be in time, i think it is important to give it time and continue to give feed back if we find bugs or have ideas to improve the system.

Happy flying
Simon

**Comment by jbesse262** [comment]
How is any of this an "issue" with Ethos. Getting tired of all the none issue posts in here. If you dont like the layout...

**Comment by bsongis-frsky** [comment]
This is not a repository to discuss Documentation, please don't give us more work and don't open issues for nothing if you want that Lua (or other features) come one day.
