### ISSUE TITLE
Time drift of Transmitter Clock

### ISSUE THREAD

**Issue by mherke** [FrSkyRC/ETHOS-Feedback-Community#549]
already after a few days it can be observed on the Frsky Tandem X20S with Ethos firmware 1.0.9 LBT that the time in the transmitter deviates from the actual time by several minutes. The deviation is very high within a month.

many greetings

Michael

**Comment by Ceeb182** [comment]
Just to document this issue, there is a time shift of 25mn per month (for me, it's 25mn in advance).
This is not dramatic because it does not affect the general operation of the radio.

**Comment by Hobby4life** [comment]
this is rather "normal" for battery backed up RealTimeClocks.

This is not an Ethos issue either. it is hardware related.

**Comment by Ceeb182** [comment]
I agree that this issue is not a development priority.

However, 25 minutes every month is still a lot !

Here is a proposed solution:
Like all RTC clocks, there is a digital calibration register.
To solve this problem, it is enough to calculate the offset at the next time setting by the user.
ETHOS then calculates the offset in ppm and adjusts the digital calibration register.

**Comment by timmybeetle** [comment]
It still runs to fast, I have 1.0.10 on it, but as stated above it's a hardware issue.
BUT still I don't like it, using telemetry data, the time of recording and saving isn't right then.

Regards Hans

**Comment by Ceeb182** [comment]
Cool : :+1:

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/142935670-7432e592-0674-41f0-b410-e34d657f1452.png)

**Comment by pld74** [comment]
How does Adjust RTC Speed work and how do we know the unit value to replace it with?
