### ISSUE TITLE
Slider improovement

### ISSUE THREAD

**Issue by loetefix** [FrSkyRC/ETHOS-Feedback-Community#635]
the new "value slider" is a realy nice feature but i have some little improovements.
1. Show the actual INC/DEC value next to the slider (Picture right side)
2. with page button snap the slider into the next range ( 10,100,1000 depending on range of setting,picture on the left side) ,page long return to 1
3. In german there is allways "Servoweg min" and "Servoweg max". that is wrong because the slider is not only for servo values.only min and max similar to english is right here.

![slider](https://user-images.githubusercontent.com/28823296/125595322-b969eccf-9ab9-427a-9cc2-f0e14b08188c.jpg)

**Comment by bsongis-frsky** [comment]
For German please ask to @EngelMT

**Comment by loetefix** [comment]
Yes , there is no servo in english. Thats absolutely right. And so it should be in german too.

**Comment by EngelMT** [comment]
Can be an issue with German translation. I have to check it. Can be that we need this term for more then this menu or I misinterpreted the English version. I'll have a look at it.

**Comment by loetefix** [comment]
@EngelMT you defined the MIN and MAX in de.txt as "Servoweg min" and "Servoweg max" . Thats wrong because it is not only used vor the Servo-outputs from now. i think only "Min" and "Max" is the best solution.

**Comment by EngelMT** [comment]
@loetefix

Yes, you are right. My problem, and I think this applies to everyone who works on the various translations, is that we don't know the background of the function when we translate. I.e. I translate because I think I know what the function behind it is. Here I thought, for example, that you could set at which telemetry value a servo should make which deflection. E.g. tow release open at 500 m altitude. That is why I had chosen "servo travel". I did not know that in the end it is only a matter of setting the step size larger or finer when setting values.

But no problem. It has been changed and will be included in the next update published by Bertrand.

**Comment by loetefix** [comment]
Yes i know . It was no reproach.  ;) Some things are also not realy easy to translate.

**Comment by loetefix** [comment]
Why closed? it was not only the translation problem.
