### ISSUE TITLE
Enhancement: allow selection of throttle source for timers

### ISSUE THREAD

**Issue by MrD-RC** [FrSkyRC/ETHOS-Feedback-Community#654]
It would be great if the throttle source can be selected. At the moment it seems to be based on the throttle input. But it would be great if the pilot could change the source to, for example, output channel 3. This would mean that no matter how the throttle is set up, with any forms of cuts, kill switches, or curves; the timers will always only react to the true throttle value.

**Comment by Droptank** [comment]
+1

Currently this is a problem for helis.  Throttle stick is at midpoint even before spool up but the timer starts because of stick position.  Need the throttle output to trigger the timer after releasing throttle hold instead of simple stick position.

**Comment by Hobby4life** [comment]
If you start at midstick.. then there is a control that starts your engine..
That control starts your timer.. no sense to trigger timer with throttle then.

Personally I dont see any point to trigger timers with Throttle positions for heli's.
Motor on/off switch triggers timers.

**Comment by Droptank** [comment]
Sure that works but the point is it’s not a true throttle trigger.  It’s just a stick position trigger.  Trying to refine the programing.  If Frsky wants Ethos to be the bridge to bring in new users who’ve never used Opentx then we need to clean up a few things.  Just because there’s a way to “make it work” doesn’t mean we can’t make it better and streamlined.  It’s kind of hokey to see the timer going while throttle hold is on just because the stick was moved.  Also annoying to be working on the bench and doing some programing to then hear the countdown warnings all while throttle hold is on.

**Comment by centertrim** [comment]
https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/98

**Comment by mawzthefinn** [comment]
The current implementation tracks the throttle mixer output and now obeys curves, cuts/holds, etc.

**Comment by pstasek** [comment]
> The current implementation tracks the throttle mixer output and now obeys curves, cuts/holds, etc.

This is still not enough. For example, it would be nice to be able to use a virtual channel output with a custom curve for Gasser models that would be active only when the ignition is on. Carburettors are not linear and the fuel consumption is different than throttle curve. +1 for the option to be able to select a throttle source for the Throttle percentage stopwatch active condition, please.

**Comment by mawzthefinn** [comment]
This is now addressed in 1.5.0 Nightly, where any proportional source can be selected for timer scaling.
