### ISSUE TITLE
BUG:  Standard Critical Akku Voltage to Low 

### ISSUE THREAD

**Issue by Beastyboy80** [FrSkyRC/ETHOS-Feedback-Community#728]
The Standard Critical Voltage Alarm (6.4V ) is too Low for a Lipo Battery

**Comment by hrenz** [comment]
Warning threshold set to 7.0V
the first warning transmitter batt low comes at <7.0V
the transmitter switches off at 6.0V
This gives you about 10-15 minutes to land.

It would be better set  to 7.1V - 7.2V. for LiPo batt

**Comment by bsongis-frsky** [comment]
Modified to 7.2V by default

**Comment by Joetrin** [comment]
How does this affect those that put 18650 batteries, the warning levels should be variable depending on the chemistry of battery used, please.

Specifications:
Capacity: 3000mAh
Nominal Voltage: 3.7V
Cut-off Voltage: 2.5B
Internal Impedance: ≤ 180 Milli-Ohms
Cycle Performance: 90% of initial capacity at 400 cycles
Charge Cycles: 500
Charging Current: 0.5C (~1500mA) Voltage = 4.2 V End Current = 0.01 mA
Discharging Current: 0.5C (~1500mA) End Voltage = 3.0V
Dimensions:
Diameter: 18.6+/-0.2 mm *
66.5+/- 0.2mm
Weight: 48g

**Comment by MIKE-DAILEY** [comment]
The alarm setting is user adjustable.

**Comment by Joetrin** [comment]
Hi Mike,

I'm aware of that for 1.0.10, but this thread implies that it will be changed to 7.2.  The reason I bumped it up is to make sure that it remains adjustable.

Thank You

**Comment by MIKE-DAILEY** [comment]
He is just setting the default.  The user can still change the value.

**Comment by EngelMT** [comment]
The problem is that FrSky offered first time LiIon Batteries for the X20. And in some instructions you find that LiIon are used too. But they deliver with LiPo. So if the customers do not check the settings he get the warnings to late. Here some customers crashed their planes by this issue because the time between warning and radio "OFF" is to short for landing. So it will be better to set the default to 7,2V like Bertrand will do it in 1.0.11.

Later the customer can do what he want.
