### ISSUE TITLE
Counter at special function

### ISSUE THREAD

**Issue by hrenz** [FrSkyRC/ETHOS-Feedback-Community#759]
Improvement
Need a counter function in the special functions
with the functions Inc, Dec, Steps, Range, 
Autoreset of Range, Set, Reset, Preset
from -1024 to +1024
The counter value must be stored in a variable.

**Comment by dwheeld** [comment]
I agree. Control of counter should be accessible to all switches, trim switches, logical switches, telemetry, and mixes.  The counter value should be available to all functions and mixes. Counter value should be persistent between model sessions.

**Comment by hrenz** [comment]
Counter at Spezailfunctions
Counter at GVAR

**Comment by mawzthefinn** [comment]
T believe this would be either part of the GVAR implementation proposed in #779 or a special case of VAR mixers to allow them to run on -1023 to + 1024 signed binary range instead of mapping that to the current percent, then adding the adjuster proposed in #1602 

Either way, this does need to get addressed.

**Comment by mawzthefinn** [comment]
Closing as it's in VAR's for 1.5.0
