### ISSUE TITLE
Feature Request: Variable X value in logic  with source for Telemetry sensors

### ISSUE THREAD

**Issue by PD5DJ** [FrSkyRC/ETHOS-Feedback-Community#763]
I would like to request a variable X value for telemetry sensors.

Example.

I do a lot of glider tow work for competitions.
Everytime I set an alarm if I hit a altitude.
But next round can be another altitude.
Now I have to dig into logic and change the X value for the alarm trigger.

A > X
A = Altitude Sensor
X = Variable value with min and max range. with source control.

It would be nice to have X variable controlled by a source.
User has to set limits,, MIN value = 100m, Max value = 300m
With a pot I can quickly dial to any value in between.
Then it would be nice to read this value out in a widget.

You can use the min and max value as default of every telemetry sensor.

**Comment by miksterr** [comment]
Yes please.

**Comment by mawzthefinn** [comment]
Yes, this would be nice.

A Lua could probably also be written for the specific application, but testing against an adjustable target that isn't -100% to 100% would be valuable

**Comment by bsongis-frsky** [comment]
This is my VFAS Sensor, with range 0-12.25V:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/8bedb863-fe1c-4a6c-acc5-20139225fe98)

I am using Rudder as Value(X). 

Rudder = 100%:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/80a84b6e-8afb-4878-8751-521e7976a9d6)

Rudder = -100%:
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/424ca8cc-42bb-403b-8675-7f57ee9d7131)

And of course you may use a Var instead of an Analog and it will work the same!

**Comment by agibson2** [comment]
This looks like a great feature.  If you want the valid ranges of X to be different than the telemetry min/max, It sounds like you would need to set rudder (for this example) to less than 100% and work out what that means for the values with some basic math.  Is that correct?

**Comment by bsongis-frsky** [comment]
RCG is there for that purpose!

**Comment by bsongis-frsky** [comment]
> This looks like a great feature. If you want the valid ranges of X to be different than the telemetry min/max, It sounds like you would need to set rudder (for this example) to less than 100% and work out what that means for the values with some basic math. Is that correct?
> 
> Ethos needs a blog to talk about new features and capabilities and what that can mean for model setups. I bet most people don't even know other good stuff like this.

Exact. You may also use a Var for that purpose
