### ISSUE TITLE
System beeps and alarm sounds

### ISSUE THREAD

**Issue by Mordee** [FrSkyRC/ETHOS-Feedback-Community#781]
Would love to see system sounds with the option of different alarm and/or buzzer sounds. similar to alarm1 alarm2 etc from opentx

**Comment by mawzthefinn** [comment]
Could be neat. You can do your own custom alarms today of course, but this would be good for many users

**Comment by builda1** [comment]
Since my request the same got closed, can i second getting this functionality added to ETHOS (select sound in Special functions, and the Rings/ratata/siren etc OTX had) as it was VERY useful and way better than a radio screaming "low battery" or something. I used to set a logical switch that warned me when the voltage dropped below 3.8v/cell so i would ease off the gas a bit and maximise my flight times. Was SUPER useful, having a voice do it is bloody annoying as already too many voice alerts (and i use hardly any) 

Thanks Bertrand and co for all the hard work you do for guys like me to be spoiled with the OS we have that is ETHOS👍

**Comment by builda1** [comment]
> Could be neat. You can do your own custom alarms today of course, but this would be good for many users

How do we do this Mawz? Can we copy the OTX ones over and use them?? Forgive the ignorance but im not a Software Dev etc 👍

**Comment by mawzthefinn** [comment]
They would be in system sounds if added in the OS< if you do your own they would be in /audio like any custom audio files

**Comment by builda1** [comment]
These "OTX tones/Beeps" etc I actually found them on here somewhere (Github) on a users own page (cant remember who), but @mawzthefinn and @Mordee when I AM on my PC I will upload the folder with all those classic OTX beeps, bleeps, siren, Ratata etc that we all love ok. I even added Amber to my Ethos cause you kinda get used to it after a decade you know lol. Will try to get it done this week.
