### ISSUE TITLE
italian translation

### ISSUE THREAD

**Issue by valefe75** [FrSkyRC/ETHOS-Feedback-Community#817]
When italian translation???

**Comment by Hobby4life** [comment]
If someone that can translate english to italian.. the .txt file is with the simulator

**Comment by Ceeb182** [comment]
Here is the English message for Ethos 1.0.11rc1 : [en.txt](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7010599/en.txt)
1. Make a copy of this file and rename it "it.txt" for Italian
2. Use a text editor to edit the messages to be translated (with UTF-8 encoding)
3. Attach the completed file to this issue so that Bertrand can integrate it into the next version of Ethos

**Comment by bsongis-frsky** [comment]
When ready please open a new issue so that we can follow up easily

**Comment by pld74** [comment]
I will help with this...

**Comment by pld74** [comment]
@bsongis-frsky If I wanted to create the Italian TXT file, do I edit everything from English to Italian OR only the wording in the quotations?

**Comment by pld74** [comment]
> When italian translation???

Ti aiuterò con questo e farò rivedere i miei genitori per garantire l'accuratezza
