### ISSUE TITLE
I wish I could assign a channel to the custom button

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#856]
I don´t know if it´s possible to assign a channel to a custom button. Thanks

**Comment by Hobby4life** [comment]
yes, create a free mix, and use a button as source

**Comment by jasalca** [comment]
It is not possible to use a custom button as a source

https://user-images.githubusercontent.com/87758703/130814562-6cd826a2-4dbb-45fe-80d6-bd081907bb86.mp4

**Comment by bsongis-frsky** [comment]
MAX as a source and Function Switch as Active Condition?

**Comment by FBarrao** [comment]
Not the same, since this way gives an output of  +100 ( or the value that you select) when active, but  0 when dissable. 
And the needed  is  +100 and -100  and not +100 and 0   to control an on -off channel like a light, gear... 

And yes, it can be made with a logic switch like hobby4life proposses a few posts above, activating a logic switch with the function switch, ( since you can select the function switch to activate the logic switch),  and later use the logic switch as source in the mixer, ( since you can select  the logic switch as source in a free mix), but..... It should be much easier to be able so select directly the Function switch as a source in the free mix.

**Comment by jasalca** [comment]
An example:I need move one servo that makes a journey from -25 to+ 50 and that does it with a function Switch...
With Max as a source and Function Switch as Active Condition .It doesn't.

**Comment by jasalca** [comment]
I only ask to include Function Switch as Source . Do you understand me now? Thanks

**Comment by mawzthefinn** [comment]
FSW's are physical equivalents of logical switches in the implementation.

You can turn them into a source or just send arbitrary values to a channel by using a VAR mix, which accepts FSW's as weight conditions.

**Comment by bsongis-frsky** [comment]
![image](https://user-images.githubusercontent.com/50834778/193989555-7d7306bd-e015-45a5-8508-0aa6b72bebe7.png)
