### ISSUE TITLE
Play Track can't play system files

### ISSUE THREAD

**Issue by guycnicholas** [FrSkyRC/ETHOS-Feedback-Community#879]
I have done some experimentation moving sound files around and have come up with this. For the radio to play sounds like, "welcome to Ethos" they need to be on the SD card inside audio/en/system. If I move them anywhere but there, they will not play. Likewise with something like "play value" I will not hear the sounds played unless they are in the aforementioned folder.   However, if I try to "play track" like in the special function area, the only files that show up are the ones at the root of the audio folder.  What I was originally trying to do was add a simple low battery warning and I couldn't. The low-batter.wav file is unavailable to me from withing the special functions area.

**Comment by MIKE-DAILEY** [comment]
That is correct.  The "Play Tack" in special faction is for user provided sounds.  Here is the detail on all the file paths. 

*File Storage*

The X20 series uses a SD card that is 32gig or less formatted fat32. I'm using a SanDisk Ultra Micro SDHC Class 10 16gig card. Files will be on the FRSky website.

The X20 uses an internal virtual USB flash memory drive and the SD card for file storage. Some of the folders the system will create if the user does not create them like Logs, Models and Screenshots. The Firmware folder I created to keep my device firmware like receivers, etc.

The following is how the files are currently arranged on the X20 systems. The audio folder is listed twice because it is showing the paths.

*USB Drive path*

USB Drive (drive letter)/bitmaps/system (the bit maps that are used for the screen displays and icons are stored here)

*SD Card paths*

SD Card (drive letter)/audio/ (user sound files)
SD Card (drive letter)/audio/en/system (system sound files)
SD Card (drive letter)/bitmaps/user/ (user model images. Image size for the main X20 screen is 300x280 and 180x166 for the X10)
SD Card (drive letter)/bitmaps/gps (maps for GPS location display)
SD Card (drive letter)/Firmware/ (Store firmware for flashing receivers and other devices)
SD Card (drive letter)/Logs/ (Data logging stored here)
SD Card (drive letter)/models/ (Model files stored here)
SD Card (drive letter)/screenshots/ (Screenshots stored here)
SD Card (drive letter)/radio.bin (the radio file is created by the system when first used and stores system settings)
SD Card (drive letter)/ (ETHOS firmware bin placed here to flash system. File is deleted by system after flash complete)

**Comment by guycnicholas** [comment]
How could I then play something like the low battery file?  I am coming from OTX and this basically seemed to be the same functionality, create a logical switch based on a particular battery voltage, then add a special function activated by that switch that plays the sound file.

**Comment by OldGazer** [comment]
COPY the file and PASTE it into the root of  the /audio folder.  ETHOS will see it as a user sound file and a system sound file.

**Comment by guycnicholas** [comment]
Well sure, but to be honest that is lame. IMHO the code should enumerate the audio folder restricting to the current locale when in a folder of locales.

**Comment by bsongis-frsky** [comment]
If you change your locale settings, your custom sounds will still be working. 
This is not the case in OpenTX if I am not mistaken.

**Comment by guycnicholas** [comment]
Wait, so @bsongis-frsky  you are saying that for me to use play-track to play a system sound I have to move the sound file out to the root of the sound folder?

**Comment by Hobby4life** [comment]
> Wait, so @bsongis-frsky you are saying that for me to use play-track to play a system sound I have to move the sound file out to the root of the sound folder?

I can answer also with yes

**Comment by bsongis-frsky** [comment]
Yes

**Comment by MIKE-DAILEY** [comment]
> Wait, so @bsongis-frsky you are saying that for me to use play-track to play a system sound I have to move the sound file out to the root of the sound folder?

The main function for "Play Track" is to play your own custom sounds.  You provide the sound files you want to use. If there is a system sound you want to use then you can copy it to the audio folder.  But, again it is for playing your own custom sounds that you put in the audio folder.
