### ISSUE TITLE
Rssi basso

### ISSUE THREAD

**Issue by Albi95** [FrSkyRC/ETHOS-Feedback-Community#905]
Frsky x20 con telemetria attiva mi segnala rssi basso e rssi critico nelle impostazioni é impostato a 35db il basso  e 32 db il critico, se faccio la riduzione del segnale a circa 5 mt mi dice segnale critico cosa devo fare per risolvere?

**Comment by Ceeb182** [comment]
(`it`) Poiché gli sviluppatori e i tester sono internazionali, per favore scrivi il tuo messaggio in inglese. Questo rende più facile il trattamento del tuo problema.
(`en`) As the developers and testers are international, please write your message in English. This makes it easier to process your issue.


> **Translation of your issue** 
> With my Frsky X20 radio, the telemetry reports me a low RSSI and a critical RSSI. For information, in the parameters the limit of the low RSSI is set at 35dB and the limit of the critical RSSI is set at 32 dB. When I do a range test, the radio announces a `critical signal` at about 5 meters: what should I do to solve this problem?



The missing information is as follows:
1. Please specify the characteristics of your hardware:
- the version of the Ethos firmware used
- the firmware version of your 2.4GHz and 868/900MHz HF module
- the name of the receiver used
- the protocol used ACCESS or ACCST
2. Please post a picture showing the position of your receiver and its antennas
3. Is this problem related to a particular aircraft or is the problem the same for all your aircraft ?

Here are the elements to check on your side:
1. Does your receiver have the latest firmware available on frsky-rc.com?
2. For 2.4GHz it is important that the antennas are not hidden, and they should be positioned at 90° to each other
3. Try another receiver to see if the problem is not a faulty one

**Comment by centertrim** [comment]
Also check that you have not accidentally selected the external antenna option in the RF settings.

**Comment by Albi95** [comment]
> Verificare inoltre di non aver selezionato accidentalmente l'opzione dell'antenna esterna nelle impostazioni RF.

I DID NOT UNDERSTAND, WHAT DO YOU RECOMMEND ME TO DO?

**Comment by pld74** [comment]
@Albi95 Cercherò di aiutarte come italocanadese ;-) 

1) Deve essere sicuro che se le antenna sono a 90 gradi l'uno dall'altro.
2) Che le antenna non sono vicino a magneti, fibra di carbonio, metallo e altre fonti di rumore come regolatore di velocità e accensione.
3) Più alta sulla fusoliera è meglio.

Un tip: Pensa a RF come una linea di sito per aiutarte. Più è chiaro in tutte le direzioni, più è probabile che il segnale sia migliore in tutti gli orientamenti.

E abbiamo bisogno di altro informazioni per auitarte in piu:

1) Modello radio, sistema operativo, firmware della radio (RF)
3) Ricevitore Modello e firmware (RF)
4) Qualsiasi immagine per mostrare la rata dell'antenna
