### ISSUE TITLE
Emergency Alerts and Volume

### ISSUE THREAD

**Issue by pld74** [FrSkyRC/ETHOS-Feedback-Community#919]
May I suggest that emergency alerts such as radio battery low, receiver battery low, and other flight critical values that their volumes are not overridden by the user volume level. 

An example would be that the user would set the volume accidentally to zero while in flight and the low battery alert will not be heard. If emergency alerts were always preset at a default level, maybe Half to Full Volume, those alerts would always go through and thus help a few flyers with silenced radios avoid incidents.

**Comment by mawzthefinn** [comment]
I would not be in favour of this, this would drive me up the wall, because usually when I get these alerts I'm working on the bench with the radio in silent mode. The radio already warns on Silent Mode on model change and I think that's more than enough.

Overriding user choice is more of a Spektrum thing (see their recent RF warning change in NX 3.07 and the backlash to it)

**Comment by mawzthefinn** [comment]
Closing this off, as no additional comments in support have arrived despite references. Experience with the backlash to a similar change in Airware 3.07 suggests the users would not react well to the system ignoring Silent Mode. 

This issue is stale at this time.
