### ISSUE TITLE
Emergency Mode in 1.0.11 - When opening RF Menu ?

### ISSUE THREAD

**Issue by FLYRAPTOR** [FrSkyRC/ETHOS-Feedback-Community#962]
i have installed the last firmware version, 1.0.11 and when i hav navigated in the menu' of RF radio is crashed in emergency mode, i have shut off , and now work, but another people have the same issue, please check

**Comment by MIKE-DAILEY** [comment]
No issues here.  X20S 1.0.11 and ISRM 1.2.9.

**Comment by FLYRAPTOR** [comment]
it happened me during navigation in the RF  menu', another customers the same thing

**Comment by bsongis-frsky** [comment]
when did it happen, just when entering this page? or later when pressing a button? long pressing a button?

**Comment by FLYRAPTOR** [comment]
> when did it happen, just when entering this page? or later when pressing a button? long pressing a button?

i have make the update, i have rebot the radio, and after i have go in the RF MENU', when i have touch on/off the 2,4 ghz radio have go in emergency mode

**Comment by FLYRAPTOR** [comment]
this customer JOHN J. ALLEN 
![Uploading 2.jpg…]()
 when have edited the mix , have go in emergency mode with 1.0.11 RC4

**Comment by FLYRAPTOR** [comment]
this customer JUSTIN WYATT, after the update have go in emergency mode
![1](https://user-images.githubusercontent.com/88722045/133446875-bc07ce13-ee06-45a8-92d0-d5928b322376.jpg)

**Comment by FLYRAPTOR** [comment]
> when did it happen, just when entering this page? or later when pressing a button? long pressing a button?

check the picture of this customer JUSTIN WYATT
![3](https://user-images.githubusercontent.com/88722045/133448901-074bb3fc-d4f4-495b-b48d-79c42605d85c.jpg)

**Comment by bsongis-frsky** [comment]
Anyone is able to reproduce this issue?

**Comment by bsongis-frsky** [comment]
@FLYRAPTOR Which is the language of your radio?

**Comment by FLYRAPTOR** [comment]
> @FLYRAPTOR Which is the language of your radio?

english language, i have replaced the stock micro sd 4gb with a new other brand kingstone 16gb, and i have navigated in all the menu’ and at present radio don’t have the issue of ‘’ emergency mode’’

**Comment by RudrigoMaciel** [comment]
Hi!
I don't know what is the frequency and what is the dependence of Ethos / X20s to read and write to the SD card to work correctly. I'm an engineer and we've developed mission critical systems and we've learned that relying on reading and writing memory cards can cause serious problems. Nowadays, the market is flooded with clone cards, which use the brand of the original cards and it is very difficult to differentiate the original card from a clone card (false brand), and this makes things even worse. In my case, the card that came with the X20s was unstable, sometimes it got in, sometimes it didn't carry anything. I bought a new card and had no more problems. But... because I don't know the level of dependence of the Ethos / X20S when in flight, that is, the radio turned on normally, plane flying. Is it still critical continues to have access to the card? If it fails, what happens? Does the radio stop? Freezes? Does the radio keep resetting until it can read the card? What if the radio can't read the card? On my jeti radio, for boot speed reasons, I put an industrial SD card. These cards have a very low MTBF and are tested in extreme conditions. Maybe that's the case. I don't know how much the lack of an SD card in flight can compromise the safety and functioning of the radio and the operating system.

**Comment by FLYRAPTOR** [comment]
today again radio in emergency mode, i still navigating in the menu', i still editing the name of aileron and .....bam , emergency mode

**Comment by bsongis-frsky** [comment]
In 1.0.11, translations from HB version are very bad. There should be no HB (or CN) in editable fields. It's perfectly normal to get an Emergency reboot when editing HB in such fields.

**Comment by mgsanna** [comment]
no issue at all....  1.0.11 final version... as suggested to Flyraptor in rcgroups, maybe it as to upgrade also sd contents and make a clean reinstall of firmware

**Comment by RudrigoMaciel** [comment]
mgsanna, how to do it? " it as to upgrade also sd contents and make a clean reinstall of firmware".
Do I need to format the sd card and install 1.0.11 from github? Is it possible to save the setup of the airplanes or will I have to adjust one by one again after the new installation?

**Comment by mgsanna** [comment]
@RudrigoMaciel , you must update the sd card with latest content, your models and also pictures of your model should be saved and copied on the sd card again.. nothing more nothing less.... it's important to update flash contents and also sd contents...
normally it would be enough to just unrar/unzip the downloaded file inside the sd card.....
