### ISSUE TITLE
Helicopter setup, channel error

### ISSUE THREAD

**Issue by Paolotandemx20s** [FrSkyRC/ETHOS-Feedback-Community#999]
Run firmware 1.0.11 on my X20S, in ely configuration find this channel assignment error via wilzard. CYC, Starting from channel 5 and no from channel 
![IMG_20210925_125754](https://user-images.githubusercontent.com/86721010/134769382-0d389e7e-f5c9-4ade-93ff-1ce8d45fa27f.jpg)
1.

**Comment by DJMacGregor** [comment]
I get the same problem with the heli wizard, and have to manually change all the channel numbers. Most frustrating.

**Comment by Hobby4life** [comment]
Correct, mostly in AETR it is 1,2 and 6
Channels should follow the AETR or TAER etc mode...

**Comment by mawzthefinn** [comment]
Disabling 'First Four channels fixed' in System->Sticks will ensure correct channel assignment when creating a heli model.

**Comment by mawzthefinn** [comment]
This should be fixed in 1.4.7, please test

**Comment by LuHaGH** [comment]
Not it is not fixed in 1.4.7 för all SPTypes. Only FBL and H1-90deg are OK. Where is the difference of these two types? Normally this is all the same.

The Icons and Mixes of H-3 120deg and HR-3 120deg are not OK. One is a 140deg Mixer and Icon.

![20230224_142535](https://user-images.githubusercontent.com/93262335/221198975-97b94745-8df3-4a9d-8e1c-7a958d6302c4.jpg)
![20230224_142556](https://user-images.githubusercontent.com/93262335/221198980-5ee70ce0-b27d-4ebe-8276-0c7aa339f637.jpg)
![20230224_142619](https://user-images.githubusercontent.com/93262335/221198984-0d1d1bda-92c8-4013-88f2-28599f39628b.jpg)

Please take a look at https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2218 There is a good explanation of the different SPs

**Comment by mawzthefinn** [comment]
@LuHaGH - That is not the issue reported here. 

The issue reported here was heli channels being assigned starting at ch5 instead of ch1, due to the 'First Four Channels Fixed' setting 

Please open a separate and new issue for what you are seeing. That needs to be fixed, but is a different issue.

**Comment by mawzthefinn** [comment]
Closing this off as it is fixed as of 1.4.7

The issue with incorrect swash icons is a separate issue and should be reported as one.
